import test from 'node:test';import assert from 'node:assert/strict';
import {foreignKeyViolations, hasTable, openTestDb} from './test-db.mjs';import {createApp} from '../src/app.mjs';
import {WORK_PAGES,SALES_PAGES,SHARED_PAGES,normalizePage,pageArea} from '../src/navigation.mjs';
async function setup(t){const db=await openTestDb({t}),app=createApp({db});const auth=async(email)=>{const r=await app.request('/api/local/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})});return r.headers.get('set-cookie').split(';')[0]};const admin=await auth('admin@openingnight.invalid');const call=async(path,b,cookie=admin)=>{const r=await app.request('/api'+path,{method:b?'POST':'GET',headers:{cookie,'content-type':'application/json'},body:b?JSON.stringify(b):undefined});return {status:r.status,data:await r.json()}};return {db,app,auth,call}}
const input=()=>({baseRevision:0,synopsis_long:'架空作品の長いあらすじ',synopsis_short:'短いあらすじ',catch_long:'長いコピー',catch_short:'短いコピー',production_year:2025,creation_year:2024,source_reference:'架空検証資料',credits:[{role:'director',name:'架空監督',detail:''},{role:'cast',name:'架空俳優',detail:'主人公'}],editions:[{edition_key:'theatrical',name:'劇場版',runtime_seconds:5430,aspect_ratio:'1.85:1',rating_authority:'架空審査機関',rating_code:'G',country:['日本','フランス'],language:['日本語'],music_society:['架空団体']}],bindings:[{product_id:1,edition_key:'theatrical'}]});
test('catalog stores normalized editions, credits and product links; retains revisions and rejects stale updates atomically',async(t)=>{const {db,call}=await setup(t);try{
 const before=await db.all('SELECT * FROM works');let r=await call('/work-catalog/1',input());assert.equal(r.status,201,JSON.stringify(r.data));r=await call('/work-catalog');const w=r.data.works.find(w=>w.id===1);assert.equal(w.profile.editions[0].runtime_seconds,5430);assert.deepEqual(w.profile.editions[0].country.sort(),['フランス','日本']);assert.equal(w.profile.bindings[0].product_id,1);
 const updated={...input(),baseRevision:1,synopsis_long:'改訂版',credits:[],editions:[],bindings:[]};const results=await Promise.all([call('/work-catalog/1',updated),call('/work-catalog/1',updated)]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);
 const history=await call('/work-catalog/1/history?revision=1');assert.equal(history.data.versions.length,2);assert.equal(history.data.profile.credits.length,2);assert.equal(history.data.profile.synopsis_long,'架空作品の長いあらすじ');assert.deepEqual(await db.all('SELECT * FROM works'),before);
 await assert.rejects(db.run('UPDATE catalog_profiles SET synopsis_long=? WHERE work_id=1',['overwrite']));await assert.rejects(db.run('DELETE FROM catalog_editions WHERE work_id=1'));assert.deepEqual(await foreignKeyViolations(db),[]);
 }finally{await db.close()}});
test('catalog validates foreign keys, unauthorized actors, missing and invalid metadata without partial writes',async(t)=>{const {db,call,auth}=await setup(t);try{
 const production=await auth('production@openingnight.invalid'),outsider=await auth('outsider@other.invalid');assert.equal((await call('/work-catalog/1',input(),production)).status,403);assert.equal((await call('/work-catalog/1',input(),outsider)).status,403);
 assert.ok((await call('/work-catalog',null,production)).data.works.every(w=>w.canEdit===false));assert.ok(!(await call('/work-catalog',null,outsider)).data.works.some(w=>w.id===1));
 for(const patch of [{production_year:'invalid'},{credits:[{role:'unknown',name:'test'}]},{bindings:[{product_id:999,edition_key:'theatrical'}]},{bindings:[{product_id:1,edition_key:'missing'}]},{source_reference:''}])assert.ok((await call('/work-catalog/1',{...input(),...patch})).status>=400);
 assert.equal((await db.get('SELECT count(*) n FROM catalog_profiles')).n,0);
 await db.run('INSERT INTO projects(id,org_id,code,title) VALUES(90,1,?,?)',['PRIVATE','restricted']);await db.run('INSERT INTO works(id,org_id,project_id,code,title) VALUES(90,1,90,?,?)',['PRIVATE-W','restricted work']);await db.run('INSERT INTO product_works VALUES(1,1,90,5000)');const editor=await auth('editor@openingnight.invalid');assert.ok(!(await call('/work-catalog',null,editor)).data.products.some(p=>p.id===1));assert.ok((await call('/work-catalog/1',input(),editor)).status>=400);
 }finally{await db.close()}});
test('product windows retain independent product/work relations, immutable prior terms and exact dates',async(t)=>{const {db,call,auth}=await setup(t);try{
 const b={work_id:1,product_id:1,distribution_code:'D004',territory:'日本',window_key:'通常',baseRevision:0,release_on:'2026-10-01',sales_end_on:'2027-09-30',terms_text:'架空の販売条件',source_reference:'架空契約',status:'confirmed'};
 assert.equal((await call('/work-catalog/windows',{...b,sales_end_on:null})).status,409);assert.equal((await call('/work-catalog/windows',{...b,sales_end_on:'2025-01-01'})).status,409);assert.equal((await call('/work-catalog/windows',{...b,product_id:999})).status,403);
 let r=await call('/work-catalog/windows',b);assert.equal(r.status,201,JSON.stringify(r.data));assert.equal((await call('/work-catalog/windows',b)).status,409);
 assert.equal((await call('/work-catalog/windows',{...b,baseRevision:1,status:'withdrawn'})).status,201);
 assert.equal((await call('/work-catalog')).data.windows[0].status,'withdrawn');assert.equal((await db.get('SELECT count(*) n FROM catalog_product_windows')).n,2);assert.equal((await db.get('SELECT status FROM catalog_product_windows WHERE revision=1')).status,'confirmed');
 const prod=await auth('production@openingnight.invalid');assert.deepEqual((await call('/work-catalog',null,prod)).data.windows,[]);assert.equal((await call('/work-catalog/windows',b,prod)).status,403);assert.deepEqual(await foreignKeyViolations(db),[]);
 }finally{await db.close()}});
test('business and sales tabs share common tools; retired distribution tab resolves to sales',()=>{
 assert.ok(WORK_PAGES.includes('作品・商品マスタ'));assert.ok(SALES_PAGES.includes('帳票センター'));assert.ok(SHARED_PAGES.includes('設計・定義'));assert.equal(normalizePage('流通マスタ'),'売上');assert.equal(pageArea('月別消込'),'sales');assert.equal(pageArea('作品・商品マスタ'),'work');assert.equal(pageArea('設計・定義'),null);assert.equal(new Set([...WORK_PAGES,...SALES_PAGES,...SHARED_PAGES]).size,WORK_PAGES.length+SALES_PAGES.length+SHARED_PAGES.length);
});

test('semantic definitions are authenticated, versioned and refer to actual schema tables',async(t)=>{const {db,app,call}=await setup(t);try{assert.equal((await app.request('/api/semantic-definitions')).status,401);const r=await call('/semantic-definitions');assert.equal(r.status,200);assert.ok(r.data.version);for(const metric of r.data.metrics){assert.ok(metric.grain&&metric.rule&&metric.month);for(const name of metric.source.split(' / '))assert.ok(await hasTable(db,name),name)}assert.ok(r.data.limitations.some(x=>x.includes('MCP')))}finally{await db.close()}});
