import test from 'node:test';
import assert from 'node:assert/strict';
import {openTestDb} from './test-db.mjs';
import {createApp} from '../src/app.mjs';
import {toCsv} from '../src/csv.mjs';

async function setup(t){const db=await openTestDb({t}),app=createApp({db});const login=await app.request('/api/local/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'admin@openingnight.invalid'})}),cookie=login.headers.get('set-cookie').split(';')[0];async function post(path,body){const response=await app.request(`/api${path}`,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(body)});return {status:response.status,body:await response.json()}}return {db,post};}

test('mapped commit replays its immutable mapping and keeps the physical source row',async(t)=>{const {db,post}=await setup(t);try{const profile=await post('/mapping-profiles',{partnerId:2,kind:'digital',name:'社内検証'}),profileId=profile.body.profileId;const definition={ignoredColumns:[],mappings:[{target:'report_key',mode:'literal',valueType:'string',value:'OWN-MAP-1'},{target:'partner_id',mode:'literal',valueType:'integer',value:'2'},{target:'product_id',mode:'literal',valueType:'integer',value:'1'},{target:'period_from',mode:'source',source:'開始'},{target:'period_to',mode:'source',source:'終了'},{target:'quantity',mode:'source',source:'数量'},{target:'amount_ex_tax',mode:'multiply',operands:['数量','単価']},{target:'tax_amount',mode:'source',source:'税'},{target:'amount_inc_tax',mode:'source',source:'税込'},{target:'recognition_basis_id',mode:'literal',valueType:'integer',value:'2'},{target:'report_received_on',mode:'source',source:'受領日'},{target:'basis_reason',mode:'literal',valueType:'string',value:'受領月'}]};const version=await post(`/mapping-profiles/${profileId}/versions`,definition);assert.equal(version.status,201);const raw=toCsv(['開始','終了','数量','単価','税','税込','受領日'],[['2026-09-01','2026-09-30','2','1000','200','2200','2026-10-02'],['2026-09-01','2026-09-30','3','1000','300','3300','2026-10-02']]);const preview=await post('/mapped-imports/preview',{workId:1,mappingVersionId:version.body.mappingVersionId,text:raw});assert.equal(preview.status,200);assert.deepEqual(preview.body.rows.map(row=>row.rowNo),[2,3]);const stored=JSON.parse((await db.get('SELECT payload_json FROM import_previews WHERE token=?',[preview.body.token])).payload_json);stored.rows[0].data.amount_ex_tax=2001;stored.rows[0].data.tax_amount=199;await db.run('UPDATE import_previews SET payload_json=? WHERE token=?',[JSON.stringify(stored),preview.body.token]);const rejected=await post('/mapped-imports/commit',{token:preview.body.token});assert.equal(rejected.status,409);assert.equal((await db.get('SELECT COUNT(*) AS n FROM report_imports')).n,0);}finally{await db.close();}});

test('FR-PLAN-ACQ-001 intake revisions keep the original snapshot and relationship unchanged',async(t)=>{const {db,post}=await setup(t);try{const base={workId:1,caseCode:'OWN-I1',title:'受託draft',intakeType:'entrusted',documents:[{}],scopes:[{}],participants:[{partyKind:'partner',partnerId:null,role:''}]},first=await post('/intakes',base);assert.equal(first.status,201);const second=await post('/intakes',{...base,caseCode:'OWN-I2',sourceCaseId:first.body.caseId,documents:[{title:'参照',reference:'保管番号',versionLabel:'v2'}]});assert.equal(second.status,201);assert.equal(second.body.snapshotVersion,2);assert.equal((await db.get('SELECT source_case_id FROM rights_intake_cases WHERE id=?',[second.body.caseId])).source_case_id,first.body.caseId);assert.equal((await db.get('SELECT COUNT(*) AS n FROM rights_intake_cases')).n,2);}finally{await db.close();}});
