import test from 'node:test';
import assert from 'node:assert/strict';
import {setupExpense} from './req6-expense-fixture.mjs';
import {encodeXlsx} from '../src/xlsx.mjs';
import {unzipSync,zipSync,strFromU8,strToU8} from 'fflate';
import {sampleRows,templateHeaders} from '../src/expense-sheet/expense-workbook.mjs';
async function prepare({t}={}){const f=await setupExpense({t}),row=sampleRows('legacy22')[0];row[19]='DEMO-EXP-PAYEE';const payload=rows=>({expectedVersion:0,reason:'境界の検証（架空）',file_name:'DEMO-boundary.xlsx',original_base64:Buffer.from(encodeXlsx([{name:'経費入力',rows:[templateHeaders('legacy22'),...rows]}])).toString('base64'),supplement:{project_id:1,incurred_on:'2026-09-14',closing_on:'2026-09-30',due_on:'2026-10-31',tax_category_version_id:f.settings.taxes['10'],withholding_category_version_id:f.settings.withholding.NONE,common_expense:true,each_row_invoice:true}});return {...f,row,payload};}
test('手入力の未確認額は保留へ保存し、整備後に一度だけ請求書つき経費へ解消する',async(t)=>{const f=await setupExpense({t});try{const p=await f.post('/expense-pending',{code:'DEMO-MANUAL-HOLD',project_id:1,reason:'未確認（架空）',payload:{actual_ex_tax:null,description:'未確認の手入力（架空）'}});assert.equal((await f.call('/expense-pending')).data.rows[0].payload.actual_ex_tax,null);assert.equal((await f.db.get('SELECT COUNT(*) n FROM expenses')).n,0);const b={...f.payload(),expectedVersion:0};await f.post(`/expense-pending/${p.id}/resolve`,b);assert.equal((await f.call('/expense-pending')).data.rows.length,0);assert.equal((await f.call(`/expense-pending/${p.id}/resolve`,b)).status,409);assert.equal((await f.db.get('SELECT COUNT(*) n FROM expenses')).n,1);assert.equal(JSON.parse((await f.db.get('SELECT raw_payload_json FROM expense_pending_rows')).raw_payload_json).actual_ex_tax,null);}finally{f.db.close();}});
test('数式入りのExcelを拒否し、文字の空白・不正金額・税率別丸め差を0へ変換しない',async(t)=>{const f=await prepare({t});try{const b=f.payload([f.row]),zip=unzipSync(Buffer.from(b.original_base64,'base64'));zip['xl/worksheets/sheet1.xml']=strToU8(strFromU8(zip['xl/worksheets/sheet1.xml']).replace('<v>12000</v>','<f>1+1</f><v>12000</v>'));assert.equal((await f.call('/expense-imports/preview',{...b,original_base64:Buffer.from(zipSync(zip)).toString('base64')})).status,400);const blank=[...f.row];blank[12]=' ';const invalid=[...f.row];invalid[12]='abc';let p=await f.post('/expense-imports/preview',f.payload([blank,invalid]));assert.equal(p.ready,0);assert.equal(p.held,2);const tiny=[...f.row];tiny[12]=5;tiny[13]=0;tiny[15]=5;const source=f.payload([tiny,tiny]);p=await f.post('/expense-imports/preview',{...source,supplement:{...source.supplement,groups:[{key:'tiny',from:2,to:3}]}});assert.equal(p.held,2);assert.match(p.rows[0].issues[0].reason,/丸め差/);const confirmed=await f.post(`/expense-imports/${p.id}/preview`,{expectedVersion:1,reason:'原本の丸めを確認（架空）',supplement:{...source.supplement,groups:[{key:'tiny',from:2,to:3}],tax_difference_note:'原本は各明細で切り捨てと確認（架空）'}});assert.equal(confirmed.ready,2);assert.equal(confirmed.rows[0].payload.tax_amount,0);assert.match(confirmed.rows[0].payload.details.memo,/原本は各明細/);}finally{f.db.close();}});
test('参照版が変わった下見は409。書込の途中失敗で請求書・経費・リンク・監査を全て戻す',async(t)=>{const f=await prepare({t});try{const b=f.payload([f.row]),p=await f.post('/expense-imports/preview',b);const old=await f.db.get('SELECT * FROM expense_tax_category_versions WHERE id=?',[f.settings.taxes['10']]);await f.post('/expense-accounting/taxes',{...old,code:'DEMO-TAX-10',expectedVersion:1,reason:'変更（架空）'});assert.equal((await f.call(`/expense-imports/${p.id}/commit`,{hash:p.hash,expectedVersion:1,reason:'確認'})).status,409);const q=await f.post(`/expense-imports/${p.id}/preview`,{expectedVersion:1,reason:'再確認',supplement:b.supplement});const count=async t=>(await f.db.get(`SELECT COUNT(*) n FROM ${t}`)).n,tables=['expenses','expense_invoices','expense_import_row_commits','audit_log'],before=await Promise.all(tables.map(count));const original=f.db.batch.bind(f.db);f.db.batch=statements=>original([...statements,{sql:'INSERT INTO transaction_guards(value) VALUES(0)',params:[]}]);assert.equal((await f.call(`/expense-imports/${p.id}/commit`,{hash:q.hash,expectedVersion:2,reason:'途中失敗'})).status,409);f.db.batch=original;assert.deepEqual(await Promise.all(tables.map(count)),before);await f.post(`/expense-imports/${p.id}/commit`,{hash:q.hash,expectedVersion:2,reason:'登録'});}finally{f.db.close();}});
test('原行は不変のまま受領値の訂正版から解消する。D1束縛値・1値・batchの上限を実際の登録で検査',async(t)=>{const f=await prepare({t});try{const wrong=[...f.row];wrong[19]='DEMO-MISSING';const b=f.payload([wrong]),p=await f.post('/expense-imports/preview',b);await f.post(`/expense-imports/${p.id}/commit`,{hash:p.hash,expectedVersion:1,reason:'保留の登録'});const hold=(await f.call('/expense-imports/holds')).data.rows[0];const q=await f.post(`/expense-imports/${p.id}/preview`,{expectedVersion:1,reason:'原値訂正',supplement:{...b.supplement,overrides:{2:{corrected_values:f.row}}}});assert.equal(q.ready,1);const original=f.db.batch.bind(f.db);let checked=false;f.db.batch=statements=>{checked=true;assert.ok(statements.length<=480);for(const st of statements){assert.ok(st.params.length<=100);for(const value of st.params)if(typeof value==='string')assert.ok(Buffer.byteLength(value)<131072);}return original(statements);};await f.post(`/expense-imports/rows/${hold.id}/resolve`,{expectedVersion:2,hash:q.hash,reason:'解消'});assert.ok(checked);assert.equal(JSON.parse((await f.db.get('SELECT raw_json FROM expense_import_rows WHERE id=?',[hold.id])).raw_json)[19],'DEMO-MISSING');}finally{f.db.close();}});
