import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {setupExpense} from './req6-expense-fixture.mjs';
import {buildExpenseSamples} from '../scripts/build-expense-samples.mjs';
import {decodeXlsx,encodeXlsx} from '../src/xlsx.mjs';
import {expenseTemplate,sampleRows,templateHeaders} from '../src/expense-sheet/expense-workbook.mjs';
async function fixture({t}={}){const f=await setupExpense({t});const p=await f.post('/partners',{code:'DEMO-PARTNER-EOM',name:'月末払いの支払先（架空）',kind:'vendor'});await f.post('/expense-accounting/payment-terms',{partner_id:p.id,expectedVersion:0,reason:'試験（架空）',effective_from:'2026-01-01',closing_rule:'month_end',payment_rule:'month_end',payment_month_offset:1,payment_method:'transfer'});return {...f,p,supplement:{project_id:1,incurred_on:'2026-09-14',tax_category_version_id:f.settings.taxes['10'],withholding_category_version_id:f.settings.withholding.NONE,common_expense:true,each_row_invoice:true}};}
const body=(f,bytes=expenseTemplate('legacy22',{samples:true}))=>({file_name:'DEMO-expense-22.xlsx',original_base64:Buffer.from(bytes).toString('base64'),expectedVersion:0,reason:'下見（架空）',supplement:f.supplement});
test('サンプル22列・25列を指定フォルダへ生成し読み戻す。各1件登録可・2件保留、空欄を0にしない',async(t)=>{const f=await fixture({t}),dir=await mkdtemp(fileURLToPath(new URL('../.req6-samples-',import.meta.url)));try{const paths=await buildExpenseSamples(dir);for(const [n,path] of paths.entries()){const bytes=await readFile(path),book=decodeXlsx(bytes);assert.equal(book[0].rows[0].length,n===0?22:25);assert.deepEqual(book.map(s=>s.name),['経費入力','入力ガイド','記入例','版情報']);const p=await f.post('/expense-imports/preview',{...body(f,bytes),file_name:path.split(/[\\/]/).at(-1)});assert.deepEqual([p.ready,p.held,p.excluded,p.known_ex_tax,p.unknown],[1,2,0,24000,1]);assert.match(p.rows[1].issues[0].reason,/支払先/);assert.match(p.rows[2].issues[0].reason,/金額/);}assert.equal((await f.db.get('SELECT COUNT(*) n FROM expenses')).n,0);}finally{f.db.close();await rm(dir,{recursive:true,force:true});}});
test('下見の改ざん・不足版・参照版変更を拒否。登録再送・保留解消・取消は追記で二重登録しない',async(t)=>{const f=await fixture({t});try{const p=await f.post('/expense-imports/preview',body(f));assert.equal((await f.call(`/expense-imports/${p.id}/commit`,{hash:p.hash,reason:'確認'})).status,428);assert.equal((await f.call(`/expense-imports/${p.id}/commit`,{hash:'changed',expectedVersion:1,reason:'確認'})).status,409);const commit={hash:p.hash,expectedVersion:1,reason:'確認（架空）'};await f.post(`/expense-imports/${p.id}/commit`,commit);const replay=await f.post(`/expense-imports/${p.id}/commit`,commit);assert.equal(replay.replayed,true);assert.equal((await f.db.get('SELECT COUNT(*) n FROM expenses')).n,1);const holds=(await f.call('/expense-imports/holds')).data.rows,hold=holds.find(r=>r.row_no===3);const p2=await f.post(`/expense-imports/${p.id}/preview`,{expectedVersion:1,reason:'支払先確認（架空）',supplement:{...f.supplement,overrides:{3:{partner_id:f.p.id}}}});assert.equal(p2.ready,2);await f.post(`/expense-imports/rows/${hold.id}/resolve`,{hash:p2.hash,expectedVersion:2,reason:'解消（架空）'});assert.equal((await f.call(`/expense-imports/rows/${hold.id}/resolve`,{hash:p2.hash,expectedVersion:2,reason:'解消'})).status,409);assert.equal((await f.db.get('SELECT COUNT(*) n FROM expenses')).n,2);await f.post(`/expense-imports/${p.id}/cancel`,{expectedVersion:2,voided_on:'2026-09-28',reason:'取消（架空）'});assert.equal((await f.call('/expense-sheet')).data.total,0);assert.equal((await f.db.get('SELECT COUNT(*) n FROM expense_import_rows')).n,3);assert.equal((await f.db.get('SELECT COUNT(*) n FROM expense_line_voids')).n,2);}finally{f.db.close();}});
test('税額・源泉・実出金日の不一致は保留、未知形式・数式は拒否する',async(t)=>{const f=await fixture({t});try{const rows=sampleRows('standard25');rows[0][13]=999;rows[1][19]='DEMO-PARTNER-EOM';rows[1][24]='2026-10-05';const bytes=encodeXlsx([{name:'経費入力',rows:[templateHeaders('standard25'),...rows]}]);const p=await f.post('/expense-imports/preview',body(f,bytes));assert.equal(p.ready,0);assert.match(p.rows[0].issues[0].reason,/税額不一致/);assert.match(p.rows[1].issues[0].reason,/出金日/);const bad=encodeXlsx([{name:'経費入力',rows:[['不明'],['値']]}]);assert.equal((await f.call('/expense-imports/preview',body(f,bad))).status,400);}finally{f.db.close();}});
test('同じ請求書の複数明細を一括で登録し、期限切れを拒否し、通常480文を超える行も圧縮した1batchで確定する',async(t)=>{const f=await fixture({t});try{const row=sampleRows('legacy22')[0],bytes=encodeXlsx([{name:'経費入力',rows:[templateHeaders('legacy22'),row,[...row]]}]);const p=await f.post('/expense-imports/preview',{...body(f,bytes),supplement:{...f.supplement,groups:[{key:'1',from:2,to:3,invoice_number:'DEMO-GROUP（架空）'}]}});assert.equal(p.ready,2);const c=await f.call(`/expense-imports/${p.id}/commit`,{expectedVersion:1,hash:p.hash,reason:'登録（架空）'});assert.equal(c.status,201,JSON.stringify(c));assert.equal((await f.db.get('SELECT COUNT(*) n FROM expense_invoices')).n,1);assert.equal((await f.db.get('SELECT COUNT(*) n FROM expenses')).n,2);
 const originalNow=Date.now;Date.now=()=>originalNow()-3600000;let old;try{old=await f.post('/expense-imports/preview',body(f));}finally{Date.now=originalNow;}assert.equal((await f.call(`/expense-imports/${old.id}/commit`,{expectedVersion:1,hash:old.hash,reason:'期限'})).status,409);
 const many=encodeXlsx([{name:'経費入力',rows:[templateHeaders('legacy22'),...Array.from({length:40},()=>row)]}]);const m=await f.post('/expense-imports/preview',body(f,many));const audit=(await f.db.get('SELECT COUNT(*) n FROM audit_log')).n;assert.equal((await f.call(`/expense-imports/${m.id}/commit`,{expectedVersion:1,hash:m.hash,reason:'上限'})).status,201);assert.equal((await f.db.get('SELECT COUNT(*) n FROM expenses')).n,42);assert.ok((await f.db.get('SELECT COUNT(*) n FROM audit_log')).n>audit);
 }finally{f.db.close();}});
test('支払済み束の取消と制作の下見を拒否。原行のUPDATE・DELETEも禁止',async(t)=>{const f=await fixture({t});try{const p=await f.post('/expense-imports/preview',body(f));await f.post(`/expense-imports/${p.id}/commit`,{expectedVersion:1,hash:p.hash,reason:'登録'});const e=await f.db.get('SELECT id FROM expenses');await f.post('/expense-payments',{expenseId:e.id,expectedVersion:1,paidOn:'2026-10-05',amountYen:5000,withheldYen:0,cashAccountClassVersionId:f.settings.classes['1100'],reason:'一部払い'});const r=await f.call(`/expense-imports/${p.id}/cancel`,{expectedVersion:1,voided_on:'2026-10-06',reason:'取消'});assert.equal(r.status,409);const prod=await f.login('production@openingnight.invalid');assert.equal((await f.call('/expense-imports/preview',body(f),prod)).status,403);await assert.rejects(f.db.run('UPDATE expense_import_rows SET row_no=99'));await assert.rejects(f.db.run('DELETE FROM expense_import_versions'));}finally{f.db.close();}});
