import test from 'node:test';
import assert from 'node:assert/strict';
import {openTestDb} from './test-db.mjs';
import {seedSalesDemo} from '../scripts/seed-sales-demo.mjs';
import {seedPlbsDemo} from '../scripts/seed-plbs-demo.mjs';
import {seedExpenseDemo} from '../scripts/seed-expense-demo.mjs';
import {tableCounts,countDifferences,recordingDatabase,d1LimitViolations,businessBatches} from '../scripts/seed-all-demo.mjs';
test('投入済みの架空経費と旧出金は整備APIで補い、元の行・金額・日付を変えない',async(t)=>{const db=await openTestDb({t});try{const {orgId}=await seedSalesDemo(db);const project=await db.get('SELECT id FROM projects WHERE org_id=? ORDER BY id LIMIT 1',[orgId]),user=await db.get("SELECT user_id FROM memberships WHERE org_id=? AND role='admin'",[orgId]);const old=await db.get("INSERT INTO expenses(org_id,project_id,incurred_on,accounting_month,category,description,actual_ex_tax,tax_amount,actual_inc_tax) VALUES(?,?,'2026-09-01','2026-09','事務費','既存の経費（架空）',1000,100,1100) RETURNING id",[orgId,project.id]);const paid=await db.get("INSERT INTO expense_payments(org_id,expense_id,paid_on,amount_yen,method,created_by) VALUES(?,?,'2026-09-02',600,'transfer',?) RETURNING id",[orgId,old.id,user.user_id]);const original=await db.get('SELECT * FROM expenses WHERE id=?',[old.id]),payment=await db.get('SELECT * FROM expense_payments WHERE id=?',[paid.id]);const out=await seedExpenseDemo(db);assert.equal(out.unready,0);assert.deepEqual(await db.get('SELECT * FROM expenses WHERE id=?',[old.id]),original);assert.deepEqual(await db.get('SELECT * FROM expense_payments WHERE id=?',[paid.id]),payment);assert.equal((await db.get('SELECT withheld_yen FROM expense_payment_accounting WHERE payment_id=?',[paid.id])).withheld_yen,0);}finally{await db.close();}});
test('既定の架空組織に請求書つきで作成し、再投入は監査も増やさない。残高を独立に照合',async(t)=>{const base=await openTestDb({t}),db=recordingDatabase(base);try{const sales=await seedSalesDemo(db);await seedPlbsDemo(db);const out=await seedExpenseDemo(db);assert.equal(out.orgId,sales.orgId);assert.equal(out.unready,0);assert.ok(out.scheduled>0);assert.equal(await db.get("SELECT id FROM organizations WHERE code='DEMO-EXPENSES'"),null);assert.deepEqual(d1LimitViolations(db.batches),[]);const before=await tableCounts(db);db.batches=[];const second=await seedExpenseDemo(db);assert.equal(second.skipped,true);assert.deepEqual(countDifferences(before,await tableCounts(db)),[]);assert.equal(businessBatches(db.batches).length,0);const wh=await db.get("SELECT e.actual_inc_tax-(SELECT SUM(p.amount_yen) FROM expense_payments p WHERE p.org_id=e.org_id AND p.expense_id=e.id)-(SELECT SUM(a.withheld_yen) FROM expense_payment_accounting a JOIN expense_payments p ON p.org_id=a.org_id AND p.id=a.payment_id WHERE p.org_id=e.org_id AND p.expense_id=e.id) AS debt FROM expenses e JOIN expense_details d ON d.org_id=e.org_id AND d.expense_id=e.id JOIN expense_invoices i ON i.org_id=d.org_id AND i.id=d.invoice_id WHERE i.org_id=? AND i.code='DEMO-INVOICE-WH-PARTIAL'",[out.orgId]);assert.equal(wh.debt,13300);assert.deepEqual(d1LimitViolations(db.batches),[]);}finally{await base.close();}});
