import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{openTestDb}from'./test-db.mjs';import{createApp}from'../src/app.mjs';import{extractDocument}from'../src/local-extractor.mjs';
test('integrated raw report uses existing mapped preview and atomically records lineage',async(t)=>{const db=await openTestDb({t}),app=createApp({db,extractDocument:x=>extractDocument({...x,pythonPath:process.env.ON_PYTHON || (process.platform === 'win32' ? 'python' : 'python3')})});try{let login=await app.request('/api/local/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'admin@openingnight.invalid'})}),cookie=login.headers.get('set-cookie').split(';')[0];async function post(path,b){let r=await app.request('/api'+path,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(b)});return{status:r.status,data:await r.json()}}const original=await readFile(new URL('../fixtures/report.csv',import.meta.url)),bytes=Buffer.from('架空報告の表題\n'+original.toString('utf8').replace('\n','\n\n')),up=await post('/workflow/artifacts/extract',{kind:'sales_report',workId:1,name:'report.csv',base64:bytes.toString('base64')});assert.equal(up.status,201);const sel=await post(`/workflow/reports/${up.data.artifactId}/selection`,{sheetName:'CSV',headerRow:2});assert.deepEqual(sel.data.sourceRowNumbers,[4]);assert.equal((await post(`/workflow/reports/${up.data.artifactId}/selection`,{sheetName:'CSV',headerRow:2,importedAiSuggestions:[{target:'org_id',mode:'source',source:'report id'}]})).status,422);const profile=await post('/mapping-profiles',{partnerId:2,kind:'digital',name:'workflow e2e'}),m=(target,source)=>({target,mode:'source',source}),lit=(target,value,valueType='string')=>({target,mode:'literal',value:String(value),valueType}),version=await post(`/mapping-profiles/${profile.data.profileId}/versions`,{ignoredColumns:[],mappings:[m('report_key','report id'),m('period_from','start date'),m('period_to','end date'),m('report_received_on','received date'),m('quantity','qty'),m('amount_ex_tax','net sales'),m('tax_amount','tax'),m('amount_inc_tax','gross sales'),lit('partner_id',2,'integer'),lit('product_id',1,'integer'),lit('recognition_basis_id',2,'integer'),lit('basis_reason','受領月')]});const preview=await post('/mapped-imports/preview',{workId:1,mappingVersionId:version.data.mappingVersionId,text:sel.data.canonicalCsv,workflowSelectionId:sel.data.selectionId});assert.equal(preview.status,200);assert.deepEqual(preview.data.workflowSourceRows,[4]);
const newer=await post(`/workflow/reports/${up.data.artifactId}/selection`,{sheetName:'CSV',headerRow:2});assert.equal(newer.status,201);
assert.equal((await post('/mapped-imports/commit',{token:preview.data.token})).status,409);
assert.equal((await db.get('SELECT count(*) n FROM workflow_report_commits')).n,0);
const current=await post('/mapped-imports/preview',{workId:1,mappingVersionId:version.data.mappingVersionId,text:newer.data.canonicalCsv,workflowSelectionId:newer.data.selectionId});assert.equal(current.status,200);
const commit=await post('/mapped-imports/commit',{token:current.data.token});assert.ok(commit.status<300);const lineage=await db.get('SELECT * FROM workflow_report_commits WHERE artifact_id=?',[up.data.artifactId]);assert.equal(lineage.selection_id,newer.data.selectionId);assert.equal(lineage.mapping_version_id,version.data.mappingVersionId);assert.ok(lineage.report_id);assert.equal((await post('/mapped-imports/preview',{workId:1,mappingVersionId:version.data.mappingVersionId,text:sel.data.canonicalCsv,workflowSelectionId:sel.data.selectionId})).status,409)}finally{await db.close()}});

test('ragged raw report refuses silent truncation or padding',async(t)=>{
 const db=await openTestDb({t});const app=createApp({db,extractDocument:x=>extractDocument({...x,pythonPath:process.env.ON_PYTHON || (process.platform === 'win32' ? 'python' : 'python3')})});
 try{const login=await app.request('/api/local/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'admin@openingnight.invalid'})}),cookie=login.headers.get('set-cookie').split(';')[0];
 const post=async(path,payload)=>app.request('/api'+path,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(payload)});
 for(const csv of ['report id,net sales\nR1,100,999','report id,net sales\nR2']){
 const res=await post('/workflow/artifacts/extract',{kind:'sales_report',workId:1,name:'ragged.csv',base64:Buffer.from(csv).toString('base64')});assert.equal(res.status,201);const raw=await res.json();
 assert.equal((await post(`/workflow/reports/${raw.artifactId}/selection`,{sheetName:'CSV',headerRow:1})).status,422);
 } assert.equal((await db.get('SELECT count(*) n FROM workflow_report_selections')).n,0);
 }finally{await db.close()}
});
