const iso=/^\d{4}-\d{2}-\d{2}$/;
function date(value){if(!iso.test(value))throw new Error(`日付はYYYY-MM-DD形式です: ${value}`);const [y,m,d]=value.split('-').map(Number),out=new Date(Date.UTC(y,m-1,d));if(out.getUTCFullYear()!==y||out.getUTCMonth()!==m-1||out.getUTCDate()!==d)throw new Error(`存在しない日付です: ${value}`);return out}
const text=value=>value.toISOString().slice(0,10);
const nextDay=value=>{const out=date(value);out.setUTCDate(out.getUTCDate()+1);return text(out)};
const days=(from,to)=>(date(to)-date(from))/86400000;
function monthClose(previous,interval,closeDay){const base=date(previous),target=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+interval,1)),last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate(),day=closeDay==='eom'?last:Math.min(Number(closeDay),last);return text(new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth(),day)))}
export function validateCommitteeTerms(input){
  const members=Array.isArray(input.members)?input.members:[],windows=Array.isArray(input.windows)?input.windows:[],phases=Array.isArray(input.phases)?input.phases:[];
  if(members.length<1||members.length>50)throw new Error('委員会メンバーは1〜50者です');const partnerIds=new Set();let shares=0;for(const member of members){if(!Number.isSafeInteger(member.partnerId)||member.partnerId<1)throw new Error('委員会メンバーの取引先IDが必要です');if(partnerIds.has(member.partnerId))throw new Error('委員会メンバーが重複しています');partnerIds.add(member.partnerId);if(!Number.isInteger(member.shareBps)||member.shareBps<0||member.shareBps>10000)throw new Error('持分は0〜10000bpです');shares+=member.shareBps}if(shares!==10000)throw new Error('委員会メンバーの持分合計は10000bpが必要です');
  if(input.managerPartnerId!=null&&!partnerIds.has(input.managerPartnerId))throw new Error('幹事は委員会メンバーから選択してください');
  if(windows.length<1||windows.length>20)throw new Error('販路窓口は1〜20件です');const kinds=new Set();for(const window of windows){if(!['theatrical','digital','package','broadcast','other'].includes(window.kind))throw new Error('販路種別を確認してください');if(kinds.has(window.kind))throw new Error('同じ販路種別の窓口が重複しています');kinds.add(window.kind);if(!partnerIds.has(window.windowPartnerId))throw new Error('販路窓口は委員会メンバーから選択してください');if(!['direct','via_manager'].includes(window.route))throw new Error('支払経路を確認してください');for(const key of ['platformRateBps','windowFeeBps','managerFeeBps'])if(!Number.isInteger(window[key])||window[key]<0||window[key]>10000)throw new Error(`${key}は0〜10000bpで明示してください`);if(!['window_first','manager_first'].includes(window.feeOrder))throw new Error('手数料控除順を明示してください');if(window.feeOrder==='window_first'&&(window.windowFeeBasis!=='platform_net'||!['platform_net','after_window'].includes(window.managerFeeBasis)))throw new Error('窓口先引きの基礎は窓口=platform_net、幹事=platform_netまたはafter_windowです');if(window.feeOrder==='manager_first'&&(window.managerFeeBasis!=='platform_net'||!['platform_net','after_manager'].includes(window.windowFeeBasis)))throw new Error('幹事先引きの基礎は幹事=platform_net、窓口=platform_netまたはafter_managerです');if((window.route==='via_manager'||window.managerFeeBps>0)&&input.managerPartnerId==null)throw new Error('幹事経由または幹事手数料ありの販路には幹事が必要です');}
  if(phases.length<1||phases.length>20)throw new Error('日程フェーズは1〜20件です');const sorted=[...phases].sort((a,b)=>a.startsOn.localeCompare(b.startsOn));for(let index=0;index<sorted.length;index++){const phase=sorted[index];date(phase.startsOn);date(phase.endsOn);date(phase.firstCloseOn);date(phase.referenceDate);if(phase.endsOn<phase.startsOn||phase.firstCloseOn<phase.startsOn||phase.firstCloseOn>phase.endsOn)throw new Error('フェーズ期間または初回締め日が逆転しています');if(index&&phase.startsOn!==nextDay(sorted[index-1].endsOn))throw new Error('日程フェーズに重複または欠落があります');if(!Number.isInteger(phase.intervalMonths)||phase.intervalMonths<1||phase.intervalMonths>12)throw new Error('締め間隔は1〜12か月です');if(phase.closeDay!=='eom'&&(!Number.isInteger(phase.closeDay)||phase.closeDay<1||phase.closeDay>31))throw new Error('締め日はeomまたは1〜31です');for(const key of ['reportOffsetMonths','paymentOffsetMonths'])if(!Number.isInteger(phase[key])||phase[key]<0||phase[key]>24)throw new Error(`${key}は0〜24か月です`);for(const key of ['reportDay','paymentDay'])if(phase[key]!=='eom'&&(!Number.isInteger(phase[key])||phase[key]<1||phase[key]>31))throw new Error(`${key}はeomまたは1〜31です`);if(!['release','first_sales','first_report','contract_specific'].includes(phase.referenceType))throw new Error('日程基準種別を明示してください');}if(days(sorted[0].startsOn,sorted.at(-1).endsOn)>3660)throw new Error('日程は最大10年です');const normalized={...input,members,windows,phases:sorted};committeePeriods(sorted);return normalized;
}
function offsetDate(close,months,day){const base=date(close),target=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+months,1)),last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate(),resolved=day==='eom'?last:Math.min(Number(day),last);return text(new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth(),resolved)))}
export function committeePeriods(phases){const periods=[];let index=1;for(const phase of phases){let start=phase.startsOn,close=phase.firstCloseOn;while(start<=phase.endsOn){const end=close<=phase.endsOn?close:phase.endsOn,stub=close>phase.endsOn,reportOn=offsetDate(end,phase.reportOffsetMonths,phase.reportDay),paymentOn=offsetDate(end,phase.paymentOffsetMonths,phase.paymentDay);if(reportOn<end)throw new Error('報告予定日は締め日以降にしてください');if(paymentOn<reportOn)throw new Error('支払予定日は報告予定日以降にしてください');periods.push({index:index++,phaseOrder:phase.phaseOrder,start,end,closeOn:end,reportOn,paymentOn,stub,referenceType:phase.referenceType,referenceDate:phase.referenceDate,holidayAdjustment:'none'});if(end===phase.endsOn)break;start=nextDay(end);close=monthClose(close,phase.intervalMonths,phase.closeDay)}}return periods}
function safeSum(rows,key){let total=0n;for(const row of rows){const value=row[key];if(!Number.isSafeInteger(value))throw new Error('委員会報告の金額が安全な整数ではありません');total+=BigInt(value)}if(total>BigInt(Number.MAX_SAFE_INTEGER)||total<BigInt(Number.MIN_SAFE_INTEGER))throw new Error('委員会報告の金額が安全な整数範囲を超えています');return Number(total)}
const fee=(amount,bps)=>{if(!Number.isSafeInteger(amount)||!Number.isInteger(bps))throw new Error('手数料計算は整数円・整数bpが必要です');const sign=amount<0?-1n:1n,result=sign*(BigInt(Math.abs(amount))*BigInt(bps)/10000n),number=Number(result);if(!Number.isSafeInteger(number))throw new Error('手数料が安全な整数範囲を超えています');return number};
export function calculateCommitteeWindow({window,reports,expenses,members,deductions=[]}){const grossReported=safeSum(reports.filter(row=>row.reportBasis==='gross'),'amount'),netRows=reports.filter(row=>row.reportBasis==='net'),netReported=safeSum(netRows,'amount'),platformFee=safeSum(reports.filter(row=>row.reportBasis==='gross').map(row=>({amount:fee(row.amount,window.platformRateBps)})),'amount'),platformNet=grossReported-platformFee+netReported;if(platformNet<0)throw new Error('プラットフォーム控除後原資が負のため保存できません');let windowFee,managerFee;if(window.feeOrder==='window_first'){windowFee=fee(window.windowFeeBasis==='platform_net'?platformNet:platformNet,window.windowFeeBps);managerFee=fee(window.managerFeeBasis==='after_window'?platformNet-windowFee:platformNet,window.managerFeeBps)}else{managerFee=fee(window.managerFeeBasis==='platform_net'?platformNet:platformNet,window.managerFeeBps);windowFee=fee(window.windowFeeBasis==='after_manager'?platformNet-managerFee:platformNet,window.windowFeeBps)}const expenseTotal=safeSum(expenses,'amount'),royaltyDeductions=safeSum(deductions.filter(r=>r.category==='royalty').map(r=>({amount:r.amountYen})),'amount'),productionRecoupDeductions=safeSum(deductions.filter(r=>r.category==='production_recoup').map(r=>({amount:r.amountYen})),'amount'),pool=platformNet-windowFee-managerFee-expenseTotal-royaltyDeductions-productionRecoupDeductions;if(pool<0)throw new Error('手数料・費用控除後の分配原資が負のため保存できません');const payouts=members.map(member=>({partnerId:member.partnerId,shareBps:member.shareBps,amount:fee(pool,member.shareBps),route:window.route,investmentRecipient:true,windowFeeRecipient:member.partnerId===window.windowPartnerId,managerFeeRecipient:member.partnerId===window.managerPartnerId})),paid=safeSum(payouts,'amount'),residual=pool-paid;return {kind:window.kind,label:window.label,grossReported,netReported,platformFeeKnown:platformFee,hasNetBasis:netRows.length>0,platformNet,windowFee,managerFee,expenseTotal,royaltyDeductions,productionRecoupDeductions,distributionPool:pool,payouts,residual,conservation:{source:platformNet,total:windowFee+managerFee+expenseTotal+royaltyDeductions+productionRecoupDeductions+paid+residual,balanced:platformNet===windowFee+managerFee+expenseTotal+royaltyDeductions+productionRecoupDeductions+paid+residual},route:window.route,windowFeeBps:window.windowFeeBps,managerFeeBps:window.managerFeeBps,platformRateBps:window.platformRateBps,feeOrder:window.feeOrder,windowFeeBasis:window.windowFeeBasis,managerFeeBasis:window.managerFeeBasis}}
