import {isDbConflict, dbErrorKind} from './data-platform/db-errors.mjs';
const ISO=/^\d{4}-\d{2}-\d{2}$/;
const MONTH=/^\d{4}-(0[1-9]|1[0-2])$/;
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const clean=(v,n,max=300)=>{const s=String(v??'').trim();if(!s||s.length>max)throw fail(`${n}は1〜${max}文字で入力してください`);return s};
const id=v=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<1)throw fail('IDを確認してください');return n};
const yen=(v,n='金額')=>{if(v===null||v===undefined||typeof v==='boolean'||(typeof v==='string'&&!v.trim()))throw fail(`${n}を入力してください`);const x=Number(v);if(!Number.isSafeInteger(x)||x<0)throw fail(`${n}は0以上の整数円で入力してください`);return x};
const date=(v,n='日付')=>{const s=String(v);if(!ISO.test(s))throw fail(`${n}はYYYY-MM-DD形式で入力してください`);const [y,m,d]=s.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));if(x.getUTCFullYear()!==y||x.getUTCMonth()!==m-1||x.getUTCDate()!==d)throw fail(`${n}に存在する日付を入力してください`);return s};
const nextDay=s=>{const d=new Date(`${date(s)}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)};
const offset=(base,months,day)=>{const d=new Date(`${date(base)}T00:00:00Z`),first=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+months,1)),last=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate(),resolved=day==='eom'?last:Math.min(Number(day),last);return new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth(),resolved)).toISOString().slice(0,10)};
const marks=a=>a.map(()=>'?').join(',');
const newId=()=>{const words=new Uint32Array(2);crypto.getRandomValues(words);return (words[0]&1048575)*4294967296+words[1]+1};
export const newMgId=newId;

// 当期報告の4金額の呼び名（画面・取込・サーバーのエラー文で共通）。
export const MG_AMOUNT_LABELS=Object.freeze({reportedEligibleYen:'消化対象',appliedRecoupYen:'実充当',reportedOverageYen:'超過報告',recognizedYen:'計上'});
export const MG_LEDGER_INSERT_SQL='INSERT INTO mg_ledger_entries(id,org_id,term_version_id,product_id,period_from,period_to,report_received_on,accounting_month,source_reference,reported_eligible_yen,applied_recoup_yen,reported_overage_yen,recognized_yen,status,acknowledgement,confirmation_reason,reverses_entry_id,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
const reasonWithDifference=(reason,x)=>{const d=x.differenceReason==null||!String(x.differenceReason).trim()?null:clean(x.differenceReason,'候補との差の理由',500);return reason&&d?`${reason}／候補との差: ${d}`:reason||(d?`候補との差: ${d}`:null)};
// 台帳行の検証（手入力 POST /api/mg/ledger と Excel取込で共通）。確認状態・了承・訂正理由 → 訂正元のDB確認 → 月・日付・資料参照・金額 の順に検査する。
export function mgLedgerReview(x){const status=String(x.status||'unverified'),ack=x.acknowledgement===true?1:0;if(!['unverified','reviewed'].includes(status))throw fail('確認状態を確認してください');if(status==='reviewed'&&!ack)throw fail('確認済みには手動値であることへの了承が必要です');const replaces=x.reversesEntryId?id(x.reversesEntryId):null,reason=status==='reviewed'||replaces?clean(x.confirmationReason,'確認・訂正理由',500):null;return {status,acknowledgement:ack,reversesEntryId:replaces,confirmationReason:reasonWithDifference(reason,x)}}
export function mgLedgerValues(x){const accounting=String(x.accountingMonth);if(!MONTH.test(accounting))throw fail('計上月はYYYY-MM形式で入力してください');const v={accountingMonth:accounting,periodFrom:date(x.periodFrom,'対象開始日'),periodTo:date(x.periodTo,'対象終了日'),reportReceivedOn:x.reportReceivedOn?date(x.reportReceivedOn,'実報告受領日'):null,sourceReference:clean(x.sourceReference,'報告資料参照'),reportedEligibleYen:yen(x.reportedEligibleYen,MG_AMOUNT_LABELS.reportedEligibleYen),appliedRecoupYen:yen(x.appliedRecoupYen,MG_AMOUNT_LABELS.appliedRecoupYen),reportedOverageYen:yen(x.reportedOverageYen,MG_AMOUNT_LABELS.reportedOverageYen),recognizedYen:yen(x.recognizedYen,MG_AMOUNT_LABELS.recognizedYen)};if(v.periodTo<v.periodFrom)throw fail('対象終了日は対象開始日以降にしてください',409);return v}
export async function checkMgCorrection(db,orgId,{termVersionId,productId,reversesEntryId}){const old=await db.get('SELECT * FROM mg_ledger_entries WHERE org_id=? AND id=?',[orgId,reversesEntryId]);if(!old||old.term_version_id!==termVersionId||old.product_id!==productId)throw fail('訂正元は同じ条件版・商品の報告を指定してください',409);if(await db.get('SELECT 1 FROM mg_ledger_entries WHERE org_id=? AND reverses_entry_id=?',[orgId,reversesEntryId]))throw fail('この報告には既に訂正版があります',409)}

export function mgPeriods(phases){
 if(!Array.isArray(phases)||phases.length<1||phases.length>20)throw fail('日程フェーズは1〜20件です');
 const result=[];let previous=null;
 for(const raw of phases){
  const p={...raw,startsOn:date(raw.startsOn),endsOn:date(raw.endsOn),firstCloseOn:date(raw.firstCloseOn)};
  for(const k of ['intervalMonths','reportOffsetMonths','reportDay','payOffsetMonths','payDay'])if(!Number.isInteger(p[k]))throw fail('日程の周期・日付は整数で入力してください');
  const close=p.closeDay??'31',closeNumber=Number(close);
  if(!(close==='eom'||Number.isInteger(closeNumber)&&closeNumber>=1&&closeNumber<=31)||![1,3,6,12].includes(p.intervalMonths)||p.reportOffsetMonths<0||p.reportOffsetMonths>24||p.payOffsetMonths<0||p.payOffsetMonths>24||p.reportDay<1||p.reportDay>31||p.payDay<1||p.payDay>31||p.endsOn<p.startsOn||p.firstCloseOn<p.startsOn||p.firstCloseOn>p.endsOn)throw fail('日程フェーズを確認してください');
  if(previous&&p.startsOn!==nextDay(previous))throw fail('日程フェーズに重複または欠落があります');
  if((new Date(`${p.endsOn}T00:00:00Z`)-new Date(`${p.startsOn}T00:00:00Z`))/86400000>3660)throw fail('日程は10年以内にしてください');
  let from=p.startsOn,closeOn=p.firstCloseOn;
  while(from<=p.endsOn){const to=closeOn<=p.endsOn?closeOn:p.endsOn,reportOn=offset(to,p.reportOffsetMonths,p.reportDay),payOn=offset(to,p.payOffsetMonths,p.payDay);if(reportOn<to||payOn<reportOn)throw fail('報告予定日・支払予定日の順序を確認してください');result.push({periodFrom:from,periodTo:to,closeOn:to,reportOn,payOn,stub:closeOn>p.endsOn});if(to===p.endsOn)break;from=nextDay(to);closeOn=offset(closeOn,p.intervalMonths,close)}
  previous=p.endsOn;
 }
 return result;
}

export function normalizeMgVersion(input){
 const products=Array.isArray(input.products)?input.products:[];if(!products.length)throw fail('商品を1件以上選択してください');
 const seen=new Set(),normalized=products.map(r=>{const productId=id(r.productId);if(seen.has(productId))throw fail('同じ商品が重複しています');seen.add(productId);return {productId,evaluationYen:yen(r.evaluationYen,'商品評価額')}});
 const amount=yen(input.mgAmountYen,'契約MG額'),total=normalized.reduce((n,r)=>n+BigInt(r.evaluationYen),0n);if(total!==BigInt(amount))throw fail('商品評価額の合計を契約MG額と一致させてください');
 const mode=String(input.mode);if(!['single','cross','special'].includes(mode))throw fail('回収モードを確認してください');if(mode==='single'&&normalized.length!==1)throw fail('単独モードは商品を1件だけ選択してください');if(mode==='special'&&input.specialUnverified!==true)throw fail('特殊条件は未確認の手動条件として明示してください');
 const startsOn=date(input.startsOn,'契約開始日'),endsOn=date(input.endsOn,'契約終了日');if(endsOn<startsOn)throw fail('契約終了日は開始日以降にしてください');
 const phases=(Array.isArray(input.phases)?input.phases:[]).map((p,index)=>({order:index+1,startsOn:date(p.startsOn),endsOn:date(p.endsOn),intervalMonths:Number(p.intervalMonths),closeDay:String(p.closeDay??'31'),firstCloseOn:date(p.firstCloseOn),reportOffsetMonths:Number(p.reportOffsetMonths),reportDay:Number(p.reportDay),payOffsetMonths:Number(p.payOffsetMonths),payDay:Number(p.payDay)}));
 mgPeriods(phases);if(phases[0]?.startsOn!==startsOn||phases.at(-1)?.endsOn!==endsOn)throw fail('日程フェーズは契約期間全体を覆ってください');
 return {amount,mode,products:normalized,startsOn,endsOn,reason:clean(input.reason,'登録理由',500),sourceReference:clean(input.sourceReference,'条件根拠'),specialUnverified:mode==='special'?1:0,phases};
}

async function requireProducts(db,identity,products,settlementWork){const ids=products.map(r=>r.productId),found=await db.all(`SELECT id FROM products WHERE org_id=? AND id IN (${marks(ids)})`,[identity.org_id,...ids]);if(found.length!==ids.length)throw fail('商品を確認してください',404);const rows=await db.all(`SELECT product_id,work_id FROM product_works WHERE org_id=? AND product_id IN (${marks(ids)})`,[identity.org_id,...ids]);for(const productId of ids){const works=rows.filter(r=>r.product_id===productId);if(!works.length)throw fail('作品未割当の商品は登録できません');for(const work of works)if(!await settlementWork(identity,work.work_id))throw fail('商品の全作品に財務権限が必要です',403)}}
async function canVersion(db,identity,versionId,settlementWork){const products=await db.all('SELECT product_id FROM mg_version_products WHERE org_id=? AND term_version_id=?',[identity.org_id,versionId]);if(!products.length)return false;try{await requireProducts(db,identity,products.map(r=>({productId:r.product_id})),settlementWork);return true}catch{return false}}
async function requireContract(db,identity,direction,contractId,settlementWork){const versions=await db.all(`SELECT id FROM mg_term_versions WHERE org_id=? AND ${direction}_contract_id=?`,[identity.org_id,contractId]);if(!versions.length)throw fail('MG契約がありません',404);for(const v of versions)if(!await canVersion(db,identity,v.id,settlementWork))throw fail('既存条件版を含む全商品の財務権限が必要です',403)}
const productSql=(org,version,rows)=>rows.map(r=>({sql:'INSERT INTO mg_version_products(org_id,term_version_id,product_id,evaluation_yen) VALUES(?,?,?,?)',params:[org,version,r.productId,r.evaluationYen]}));
const phaseSql=(org,version,rows)=>rows.map(r=>({sql:'INSERT INTO mg_version_phases(org_id,term_version_id,phase_order,starts_on,ends_on,interval_months,close_day,first_close_on,report_offset_months,report_day,pay_offset_months,pay_day) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',params:[org,version,r.order,r.startsOn,r.endsOn,r.intervalMonths,r.closeDay,r.firstCloseOn,r.reportOffsetMonths,r.reportDay,r.payOffsetMonths,r.payDay]}));
const routeError=(c,bad,e)=>bad(c,e.message,e.status||(isDbConflict(e)?409:400),undefined,e);

export async function canContractVersion(db,i,versionId,sw){const v=await db.get('SELECT incoming_contract_id,outgoing_contract_id FROM mg_term_versions WHERE org_id=? AND id=?',[i.org_id,versionId]);if(!v)return false;try{await requireContract(db,i,v.incoming_contract_id?'incoming':'outgoing',v.incoming_contract_id||v.outgoing_contract_id,sw);return true}catch{return false}}
export function registerMgRoutes(app,{db,bad,body,settlementWork}){
 app.use('/api/mg/*',async(c,next)=>{if(c.get('identity')?.role==='production')return bad(c,'制作権限ではMG契約・台帳を参照できません',403);await next()});
 app.get('/api/mg/catalog',async c=>{try{const i=c.get('identity'),[suppliers,partners,products]=await Promise.all([db.all('SELECT * FROM mg_suppliers WHERE org_id=? ORDER BY code',[i.org_id]),db.all('SELECT id,code,name FROM partners WHERE org_id=? ORDER BY code',[i.org_id]),db.all('SELECT id,sku,name,channel FROM products WHERE org_id=? ORDER BY sku',[i.org_id])]),allowed=[];for(const p of products)try{await requireProducts(db,i,[{productId:p.id}],settlementWork);allowed.push(p)}catch{}return c.json({ok:true,suppliers,partners,products:allowed})}catch(e){return routeError(c,bad,e)}});
 app.post('/api/mg/suppliers',async c=>{try{const i=c.get('identity'),x=await body(c),code=clean(x.code,'仕入先コード',40);if(!code.startsWith('SUP-'))throw fail('仕入先コードはSUP-で始めてください');const supplierId=newId();await db.run('INSERT INTO mg_suppliers(id,org_id,code,name,note,created_by) VALUES(?,?,?,?,?,?)',[supplierId,i.org_id,code,clean(x.name,'仕入先名'),String(x.note??''),i.user_id]);return c.json({ok:true,supplierId},201)}catch(e){return routeError(c,bad,e)}});
 app.get('/api/mg/contracts',async c=>{try{const i=c.get('identity'),direction=c.req.query('direction')||'incoming';if(!['incoming','outgoing'].includes(direction))throw fail('契約方向を確認してください');const contracts=await db.all(`SELECT * FROM mg_${direction}_contracts WHERE org_id=? ORDER BY id DESC`,[i.org_id]),out=[];for(const contract of contracts){const versions=await db.all(`SELECT * FROM mg_term_versions WHERE org_id=? AND ${direction}_contract_id=? ORDER BY version DESC`,[i.org_id,contract.id]);if(!versions.length||!(await Promise.all(versions.map(v=>canVersion(db,i,v.id,settlementWork)))).every(Boolean))continue;for(const v of versions){v.products=await db.all('SELECT vp.*,p.sku,p.name FROM mg_version_products vp JOIN products p ON p.org_id=vp.org_id AND p.id=vp.product_id WHERE vp.org_id=? AND vp.term_version_id=?',[i.org_id,v.id]);v.phases=await db.all('SELECT * FROM mg_version_phases WHERE org_id=? AND term_version_id=? ORDER BY phase_order',[i.org_id,v.id])}out.push({...contract,party_id:contract[direction==='incoming'?'partner_id':'supplier_id'],versions})}return c.json({ok:true,contracts:out})}catch(e){return routeError(c,bad,e)}});
 app.post('/api/mg/contracts',async c=>{try{const i=c.get('identity'),x=await body(c),direction=String(x.direction);if(!['incoming','outgoing'].includes(direction))throw fail('契約方向を確認してください');const v=normalizeMgVersion(x);await requireProducts(db,i,v.products,settlementWork);const contractId=newId(),versionId=newId(),party=direction==='incoming'?'partner_id':'supplier_id';await db.batch([{sql:`INSERT INTO mg_${direction}_contracts(id,org_id,code,title,${party},contract_date,source_reference,created_by) VALUES(?,?,?,?,?,?,?,?)`,params:[contractId,i.org_id,clean(x.code,'契約コード',60),clean(x.title,'契約名'),id(direction==='incoming'?x.partnerId:x.supplierId),date(x.contractDate,'契約締結日'),clean(x.contractSourceReference,'契約資料参照'),i.user_id]},{sql:`INSERT INTO mg_term_versions(id,org_id,${direction}_contract_id,version,mode,mg_amount_yen,starts_on,ends_on,reason,source_reference,special_unverified,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,params:[versionId,i.org_id,contractId,1,v.mode,v.amount,v.startsOn,v.endsOn,v.reason,v.sourceReference,v.specialUnverified,i.user_id]},...productSql(i.org_id,versionId,v.products),...phaseSql(i.org_id,versionId,v.phases)]);return c.json({ok:true,contractId,versionId},201)}catch(e){return routeError(c,bad,e)}});
 app.post('/api/mg/contracts/:direction/:contractId/versions',async c=>{try{const i=c.get('identity'),direction=c.req.param('direction'),contractId=id(c.req.param('contractId'));if(!['incoming','outgoing'].includes(direction))throw fail('契約方向を確認してください');await requireContract(db,i,direction,contractId,settlementWork);const x=await body(c),v=normalizeMgVersion(x),base=Number(x.baseVersion);await requireProducts(db,i,v.products,settlementWork);if(!Number.isInteger(base)||base<1)throw fail('基準版を確認してください');const versionId=newId();await db.batch([{sql:`INSERT INTO transaction_guards(value) SELECT 0 WHERE ?<>(SELECT COALESCE(MAX(version),0) FROM mg_term_versions WHERE org_id=? AND ${direction}_contract_id=?)`,params:[base,i.org_id,contractId]},{sql:`INSERT INTO mg_term_versions(id,org_id,${direction}_contract_id,version,mode,mg_amount_yen,starts_on,ends_on,reason,source_reference,special_unverified,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,params:[versionId,i.org_id,contractId,base+1,v.mode,v.amount,v.startsOn,v.endsOn,v.reason,v.sourceReference,v.specialUnverified,i.user_id]},...productSql(i.org_id,versionId,v.products),...phaseSql(i.org_id,versionId,v.phases)]);return c.json({ok:true,versionId},201)}catch(e){if(dbErrorKind(e)==='check')e.status=409;return routeError(c,bad,e)}});
 app.get('/api/mg/periods',async c=>{try{const i=c.get('identity'),version=id(c.req.query('termVersionId'));if(!await canContractVersion(db,i,version,settlementWork))throw fail('条件版を参照できません',403);const phases=await db.all('SELECT starts_on startsOn,ends_on endsOn,interval_months intervalMonths,close_day closeDay,first_close_on firstCloseOn,report_offset_months reportOffsetMonths,report_day reportDay,pay_offset_months payOffsetMonths,pay_day payDay FROM mg_version_phases WHERE org_id=? AND term_version_id=? ORDER BY phase_order',[i.org_id,version]);return c.json({ok:true,periods:mgPeriods(phases)})}catch(e){return routeError(c,bad,e)}});
 app.post('/api/mg/ledger',async c=>{try{const i=c.get('identity'),x=await body(c),version=id(x.termVersionId),product=id(x.productId);if(!await canContractVersion(db,i,version,settlementWork))throw fail('条件版を参照できません',403);const review=mgLedgerReview(x);if(review.reversesEntryId)await checkMgCorrection(db,i.org_id,{termVersionId:version,productId:product,reversesEntryId:review.reversesEntryId});const v=mgLedgerValues(x),entryId=newId();await db.run(MG_LEDGER_INSERT_SQL,[entryId,i.org_id,version,product,v.periodFrom,v.periodTo,v.reportReceivedOn,v.accountingMonth,v.sourceReference,v.reportedEligibleYen,v.appliedRecoupYen,v.reportedOverageYen,v.recognizedYen,review.status,review.acknowledgement,review.confirmationReason,review.reversesEntryId,i.user_id]);return c.json({ok:true,entryId},201)}catch(e){return routeError(c,bad,e)}});
 app.get('/api/mg/ledger',async c=>{try{const i=c.get('identity'),rows=await db.all(`SELECT l.*,v.incoming_contract_id,v.outgoing_contract_id,p.sku,p.name product_name,EXISTS(SELECT 1 FROM mg_ledger_entries s WHERE s.org_id=l.org_id AND s.reverses_entry_id=l.id) isSuperseded FROM mg_ledger_entries l JOIN mg_term_versions v ON v.org_id=l.org_id AND v.id=l.term_version_id JOIN products p ON p.org_id=l.org_id AND p.id=l.product_id WHERE l.org_id=? ORDER BY l.accounting_month DESC,l.id DESC`,[i.org_id]),visible=[];for(const row of rows)if(await canContractVersion(db,i,row.term_version_id,settlementWork))visible.push(row);return c.json({ok:true,rows:visible})}catch(e){return routeError(c,bad,e)}});
 app.get('/api/mg/links',async c=>{try{const i=c.get('identity'),links=await db.all('SELECT * FROM mg_contract_links WHERE org_id=? ORDER BY id DESC',[i.org_id]),visible=[];for(const link of links)try{await requireContract(db,i,'incoming',link.incoming_contract_id,settlementWork);await requireContract(db,i,'outgoing',link.outgoing_contract_id,settlementWork);visible.push(link)}catch{}return c.json({ok:true,links:visible})}catch(e){return routeError(c,bad,e)}});
 app.post('/api/mg/links',async c=>{try{const i=c.get('identity'),x=await body(c),incoming=id(x.incomingContractId),outgoing=id(x.outgoingContractId);await requireContract(db,i,'incoming',incoming,settlementWork);await requireContract(db,i,'outgoing',outgoing,settlementWork);const linkId=newId();await db.run('INSERT INTO mg_contract_links(id,org_id,incoming_contract_id,outgoing_contract_id,rationale,created_by) VALUES(?,?,?,?,?,?)',[linkId,i.org_id,incoming,outgoing,clean(x.rationale,'関連理由',500),i.user_id]);return c.json({ok:true,linkId},201)}catch(e){return routeError(c,bad,e)}});
}
