import {useEffect,useRef,useState} from 'react';
import {mgPortfolioSheets} from './mg-portfolio.mjs';
import {exportReport} from './report-output.mjs';
import './mg-portfolio.css';

const yen=value=>value==null?'未確認':new Intl.NumberFormat('ja-JP').format(value)+'円';
const rate=value=>value==null?'対象外':new Intl.NumberFormat('ja-JP',{style:'percent',maximumFractionDigits:1}).format(value);
const modes={single:'単品',cross:'クロス',special:'特殊・参考'};
const names={eligibleYen:'消化対象',appliedYen:'実充当',overageYen:'超過報告',recognizedYen:'計上'};
const monthNow=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit'}).format(new Date());

export default function MgPortfolio({request,data,onOpenContract}){
 const [direction,setDirection]=useState('incoming'),[month,setMonth]=useState(monthNow),[report,setReport]=useState(null),[party,setParty]=useState(''),[openId,setOpenId]=useState(null),[selectedProduct,setSelectedProduct]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const sequence=useRef(0);
 async function load(){const id=++sequence.current;setBusy(true);setError('');setReport(null);setOpenId(null);setSelectedProduct(null);try{const result=await request(`/rights-reports/mg-portfolio?direction=${direction}&month=${month}`);if(id===sequence.current)setReport(result.report)}catch(e){if(id===sequence.current)setError(e.message)}finally{if(id===sequence.current)setBusy(false)}}
 useEffect(()=>{load();return()=>{sequence.current++}},[direction,month,request]);
 const current=report?.contracts.find(c=>c.contractId===openId),contracts=report?.contracts.filter(c=>!party||String(c.party.id)===party)||[];
 const changeDirection=event=>{setDirection(event.target.value);setParty('')};
 function output(format){try{exportReport(format,{filename:`mg-portfolio-${report.direction}-${report.accountingMonth}`,title:'MG取引先・契約別集計',subtitle:`${report.direction==='incoming'?'受取MG（販売先）':'支払MG（仕入先）'} ／ ${report.accountingMonth}まで ／ 閲覧権限のある全契約`,sheets:mgPortfolioSheets(report),generatedAt:report.generatedAt})}catch(e){setError(e.message)}}
 return <section className="card mg-portfolio"><header className="section-head"><div><h2>MG取引先・契約別集計</h2><p>保証額は契約ごとに一度だけ集計します。入出金実績は含みません。</p></div><div className="mgp-controls"><label>方向<select value={direction} onChange={changeDirection}><option value="incoming">受取MG（販売先）</option><option value="outgoing">支払MG（仕入先）</option></select></label><label>基準計上月<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="secondary" disabled={busy||!month} onClick={load}>再集計</button></div></header>
 {error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">MG台帳を集計中…</p>}
 {report&&<><div className="mgp-summary">{[['契約数',report.totals.contractCount+'件'],['保証額',yen(report.totals.guaranteeYen)],['累計実充当',yen(report.totals.cumulative.appliedYen)],['未消化残高（実充当）',yen(report.totals.remainingAppliedYen)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <div className="mgp-export"><span>出力：閲覧できる全取引先・全契約</span><button className="secondary" onClick={()=>output('xlsx')}>Excel</button><button className="secondary" onClick={()=>output('html')}>HTML</button><button className="secondary" onClick={()=>output('print')}>印刷・PDF</button></div>
 <div className="table-wrap"><table><caption>取引先別 · {report.accountingMonth}まで</caption><thead><tr><th>取引先</th><th>契約</th><th>保証額</th><th>当期消化対象</th><th>当期実充当</th><th>当期計上</th><th>累計実充当</th><th>未消化残高</th></tr></thead><tbody>{report.parties.map(p=><tr key={p.id}><th><button className="text" onClick={()=>{setParty(String(p.id));setOpenId(null)}}>{p.name}</button></th><td>{p.contractCount}</td><td>{yen(p.guaranteeYen)}</td><td>{yen(p.current.eligibleYen)}</td><td>{yen(p.current.appliedYen)}</td><td>{yen(p.current.recognizedYen)}</td><td>{yen(p.cumulative.appliedYen)}</td><td>{yen(p.remainingAppliedYen)}</td></tr>)}{!report.parties.length&&<tr><td colSpan={8}>基準月までに開始した閲覧可能なMG契約がありません。</td></tr>}</tbody></table></div>
 <div className="mgp-subhead"><h3>契約別</h3><label>取引先<select value={party} onChange={e=>{setParty(e.target.value);setOpenId(null)}}><option value="">すべて</option>{report.parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
 <div className="table-wrap"><table><thead><tr><th>契約／保証額版</th><th>保証額</th><th>消化対象累計</th><th>実充当累計</th><th>実充当到達率／月</th><th>消化対象到達率／月</th><th>未消化残高</th></tr></thead><tbody>{contracts.map(c=><tr key={c.contractId} className={openId===c.contractId?'mgp-selected':''}><th><button className="text" aria-expanded={openId===c.contractId} onClick={()=>{setOpenId(openId===c.contractId?null:c.contractId);setSelectedProduct(null)}}>{c.code} · {c.title}</button><small>{c.party.name} · 第{c.termVersion}版 · {modes[c.mode]}</small></th><td>{yen(c.guaranteeYen)}</td><td>{yen(c.cumulative.eligibleYen)}</td><td>{yen(c.cumulative.appliedYen)}</td><td>{rate(c.appliedRate)}<small>{c.guaranteeYen===0?'保証額0円':c.appliedReachedMonth||'未達'}</small></td><td>{rate(c.eligibleRate)}<small>{c.guaranteeYen===0?'保証額0円':c.eligibleReachedMonth||'未達'}</small></td><td>{yen(c.remainingAppliedYen)}{c.remainingIndicative&&<small>参考値</small>}</td></tr>)}</tbody></table></div>
 {current&&<section className="mgp-detail" aria-label="MG契約の明細"><div className="mgp-subhead"><h3>{current.code} · 商品・作品別</h3>{onOpenContract&&<button className="secondary" onClick={()=>onOpenContract({direction:report.direction,contractId:current.contractId,termVersionId:current.termVersionId,accountingMonth:report.accountingMonth,workId:current.rows[0]?.workId??data?.selectedWorkId})}>MG契約・台帳を開く</button>}</div><p>商品評価額は選択版の値です。クロス契約の商品別回収残高は算出しません。</p>{current.warnings.map(w=><p className="note" key={w}>{w}</p>)}
 <div className="table-wrap"><table><thead><tr><th>作品・商品</th><th>選択版評価額</th><th>指標</th><th>前回まで</th><th>当期</th><th>累計</th></tr></thead><tbody>{current.rows.flatMap(r=>Object.entries(names).map(([key,label],i)=><tr key={`${r.productId}:${r.workId}:${key}`}>{i===0&&<><th rowSpan={4}><button className="text" onClick={()=>setSelectedProduct(r.productId)}>{r.workName} / {r.productName||r.productSku}</button><small>{r.productSku} · 配賦{r.allocationBps/100}%</small></th><td rowSpan={4}>{yen(r.evaluationYen)}</td></>}<th>{label}</th><td>{yen(r.prior[key])}</td><td>{yen(r.current[key])}</td><td>{yen(r.cumulative[key])}</td></tr>))}</tbody></table></div>
 <div className="mgp-subhead"><h4>元台帳 {selectedProduct?`· 商品ID ${selectedProduct}`:'· 契約全体'}</h4>{selectedProduct&&<button className="text" onClick={()=>setSelectedProduct(null)}>全商品を表示</button>}</div><div className="table-wrap"><table><thead><tr><th>台帳ID／商品</th><th>条件版ID</th><th>計上月</th><th>消化対象</th><th>実充当</th><th>超過報告</th><th>計上</th><th>原資料・訂正</th></tr></thead><tbody>{current.sourceEntries.filter(l=>!selectedProduct||l.product_id===selectedProduct).map(l=><tr key={l.id}><th>#{l.id} / {l.product_id}</th><td>{l.term_version_id}</td><td>{l.accounting_month}</td><td>{yen(l.reported_eligible_yen)}</td><td>{yen(l.applied_recoup_yen)}</td><td>{yen(l.reported_overage_yen)}</td><td>{yen(l.recognized_yen)}</td><td>{l.source_reference}<small>{l.reverses_entry_id?`訂正元 #${l.reverses_entry_id} · `:''}{l.status==='reviewed'?'確認済み':'未確認'}</small></td></tr>)}</tbody></table></div></section>}
 <details className="mgp-basis"><summary>集計基準・未確認事項（台帳{report.totals.unverifiedCount}件）</summary><p>{report.versionPolicy}</p><p>{report.reachPolicy}</p>{report.warnings.map(w=><p key={w}>{w}</p>)}</details></>}
 </section>;
}
