import MgPortfolio from './MgPortfolio.jsx';
import JointCommittee from './JointCommittee.jsx';
import {useEffect,useState} from 'react';
import {CommitteeReport,MgReport,RoyaltyReport} from './RightsReports.jsx';
import {REPORT_GROUPS,salesReportSheets} from './report-center-model.mjs';
import {exportReport} from './report-output.mjs';
import './report-center.css';
const money=n=>Number(n||0).toLocaleString('ja-JP');
const modes=[['trend','年間売上推移'],['partner','会社売上・取引先別'],['work','作品別売上'],['product','商品別売上'],['distribution','流通別売上'],['banpan','年間番販集計'],['pnl','作品別収支'],['royalty','ロイヤリティ・支払履歴'],['committee','製作委員会収支報告'],['joint','共同製作・入金基準の収支'],['mg','MG売上・回収現況'],['mg-portfolio','MG取引先別・契約横断']];
function JointReportEntry({data,request}){
 const [workId,setWorkId]=useState(data.selectedWorkId||''),[contracts,setContracts]=useState([]),[message,setMessage]=useState('');
 useEffect(()=>{let live=true;setContracts([]);if(workId)request(`/committee/joint?workId=${workId}`).then(r=>{if(live)setContracts(r.contracts)}).catch(e=>{if(live)setMessage(e.message)});return()=>{live=false}},[workId]);
 return <div className="stack"><section className="card"><label>作品<select value={workId} onChange={e=>setWorkId(e.target.value)}><option value="">選択してください</option>{data.works.map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label><p>共同製作・入金基準の保存結果を表示します。従来の税抜委員会帳票とは計算版が異なります。</p>{message&&<p role="alert">{message}</p>}</section>{contracts.length?<JointCommittee workId={Number(workId)} contractId={contracts[0].id} request={request} initialTab="reports" role={data.currentUser?.role}/>:<section className="card"><p>選択作品に共同製作・入金基準の契約はありません。</p></section>}</div>
}
export default function ReportSalesPanel({data,request,onNavigate,initialMode,embedded=false}){
 const [mode,setMode]=useState(initialMode||'trend'),[start,setStart]=useState(`${new Date().getFullYear()}-01`),[workId,setWorkId]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(0),[drill,setDrill]=useState(null),[drillPage,setDrillPage]=useState(0),[edit,setEdit]=useState(null),[revision,setRevision]=useState(0);
 const specialised=['committee','joint','mg','mg-portfolio','royalty'].includes(mode),query=`start=${start}${workId?`&workId=${workId}`:''}`;
 useEffect(()=>{if(specialised)return;let active=true;setResult(null);setError('');setDrill(null);setPage(0);request(`/report-center?${query}`).then(r=>active&&setResult(r)).catch(e=>active&&setError(e.message));return()=>{active=false}},[query,revision,specialised,request]);
 const group=REPORT_GROUPS[mode],rows=group&&result?result[group.key]||[]:[],pageCount=Math.max(1,Math.ceil(rows.length/40)),currentPage=Math.min(page,pageCount-1),title=modes.find(r=>r[0]===mode)?.[1];
 const drillLines=!result?[]:!drill?[]:result.lines.filter(r=>(!drill.month||r.accounting_month===drill.month)&&(!drill.row||Object.keys(drill.row).every(key=>r[key]===drill.row[key])));
 function showDrill(row=null,month=null){const keys=mode==='banpan'?['kind','department_name','partner_id','distribution_code','service_name','settlement_method']:mode==='partner'?['partner_id','distribution_code']:mode==='product'?['product_id','distribution_code']:mode==='work'?['work_id','distribution_code']:mode==='pnl'?['work_id']:['distribution_code'];setDrill({row:row?Object.fromEntries(keys.map(k=>[k,row[k]])):null,month});setDrillPage(0)}
 function output(format){try{exportReport(format,{filename:`sales-${mode}-${start}`,title,subtitle:`${result.months[0]}〜${result.months.at(-1)} ／ 計上月基準・JPY税抜 ／ ${workId?'選択作品':'会社全体（権限内）'}`,sheets:salesReportSheets(result,mode),generatedAt:result.generatedAt})}catch(e){setError(e.message)}}
 async function classify(e){e.preventDefault();try{await request(edit.mode==='distribution'?'/report-center/classifications':'/report-center/departments',{method:'POST',body:JSON.stringify(edit)});setEdit(null);setRevision(v=>v+1)}catch(e){setError(e.message)}}
 return <div className="stack report-center"><section className="card" hidden={embedded}><h2>帳票センター</h2><div className="toolbar"><label>帳票<select value={mode} onChange={e=>{setMode(e.target.value);setPage(0);setDrill(null);setError('')}}>{modes.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{onNavigate&&<button className="secondary" onClick={()=>onNavigate('分析・Lightdash')}>Lightdash・分析を開く</button>}</div><p>同じ登録明細から、選択した帳票を表示します。</p></section>
 {specialised?(mode==='joint'?<JointReportEntry data={data} request={request}/>:mode==='committee'?<CommitteeReport data={data} request={request}/>:mode==='mg-portfolio'?<MgPortfolio data={data} request={request}/>:mode==='mg'?<MgReport data={data} request={request}/>:<RoyaltyReport data={data} request={request}/>):<>
 <section className="card"><h2>{title}</h2><div className="toolbar"><label>年度の開始月<input type="month" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>対象作品<select value={workId} onChange={e=>setWorkId(e.target.value)}><option value="">会社全体（閲覧権限内）</option>{data.works.map(w=><option key={w.id} value={w.id}>{w.code}｜{w.title}</option>)}</select></label>{result&&<><button className="secondary" onClick={()=>output('csv')}>CSV</button><button className="secondary" onClick={()=>output('xlsx')}>Excel</button><button className="secondary" onClick={()=>output('print')}>印刷・PDF</button><button className="secondary" onClick={()=>output('html')}>印刷用HTML</button></>}</div><p>計上月基準・税抜円。入金と契約額は加算しません。表示ページにかかわらず出力は全件です。</p>{error&&<p role="alert" className="error">{error}</p>}</section>
 {!result?<p role="status">帳票を読み込み中…</p>:<>
 {mode==='trend'&&<section className="card"><h3>年間売上 {money(result.total)} 円</h3><div className="monthly-bars">{result.months.map((month,i)=><button key={month} className="monthly-bar secondary" onClick={()=>showDrill(null,month)}><span>{month}</span><div className="bar-track"><span className={result.totals[i]<0?'negative':''} style={{width:`${Math.abs(result.totals[i])/Math.max(1,...result.totals.map(Math.abs))*100}%`}}/></div><span>{money(result.totals[i])}</span></button>)}</div></section>}
 {group&&<section className="card"><div className="toolbar"><span>{rows.length}行 ／ {currentPage+1} / {pageCount}ページ</span><button className="secondary" disabled={currentPage===0} onClick={()=>setPage(p=>p-1)}>前へ</button><button className="secondary" disabled={currentPage===pageCount-1} onClick={()=>setPage(p=>p+1)}>次へ</button></div>{mode==='banpan'&&<p>部門は明示登録した分類です。構成比はその部門の年間税抜売上を分母とし、0の場合は未算定です。</p>}<div className="table-wrap sheet"><table><thead><tr>{group.columns.map(([key,label])=><th key={key}>{label}</th>)}{result.months.map(m=><th key={m}>{m}</th>)}<th>年間計</th>{mode==='banpan'&&<th>部門内構成比</th>}</tr></thead><tbody>{rows.slice(currentPage*40,(currentPage+1)*40).map((row,index)=><tr key={index}>{group.columns.map(([key])=><th key={key}>{row[key]??'未分類'}</th>)}{row.values.map((value,i)=><td key={i}><button className="report-cell" onClick={()=>showDrill(row,result.months[i])}>{money(value)}</button></td>)}<td><button className="report-cell" onClick={()=>showDrill(row)}>{money(row.total)}</button></td>{mode==='banpan'&&<td>{row.departmentShare==null?'未算定':`${(row.departmentShare*100).toFixed(2)}%`}</td>}</tr>)}<tr className="sheet-total"><th colSpan={group.columns.length}>全件合計</th>{result.totals.map((v,i)=><td key={i}>{money(v)}</td>)}<td>{money(result.total)}</td>{mode==='banpan'&&<td/>}</tr></tbody></table></div>{rows.length===0&&<p>登録済み売上はありません。未受領の報告をゼロ受領とは扱いません。</p>}</section>}
 {mode==='pnl'&&<section className="card"><p>作品へ明示配賦された売上と経費。差額は分配前で、最終利益ではありません。</p><div className="table-wrap"><table><thead><tr><th>作品</th><th>税抜売上</th><th>税抜経費</th><th>分配前差額</th><th>根拠</th></tr></thead><tbody>{result.profitLoss.map(r=><tr key={r.workId}><th>{r.workTitle}</th><td>{money(r.income)}</td><td>{money(r.expense)}</td><td>{money(r.balance)}</td><td><button className="secondary" onClick={()=>showDrill({work_id:r.workId})}>売上明細</button><details><summary>経費明細 {r.expenseIds.length}件</summary>{result.expenses.filter(e=>e.work_id===r.workId).map(e=><p key={e.id}>#{e.id} {e.accounting_month} {e.category} {e.description} {money(e.actual_ex_tax)}円</p>)}</details></td></tr>)}</tbody></table></div><p>作品未配賦の共通経費：{money(result.unallocatedExpenseTotal)}円。作品へ推測で配賦しません。</p></section>}
 {drill&&<section className="card"><div className="toolbar"><h3>元明細 {drill.month||'年度全体'}・{drillLines.length}件</h3><button className="secondary" onClick={()=>setDrill(null)}>明細を閉じる</button><button className="secondary" disabled={drillPage===0} onClick={()=>setDrillPage(p=>p-1)}>前の100件</button><button className="secondary" disabled={(drillPage+1)*100>=drillLines.length} onClick={()=>setDrillPage(p=>p+1)}>次の100件</button></div><div className="table-wrap"><table><thead><tr>{['売上ID／報告ID／原本行','作品／商品','取引先','部門','流通／サービス／方法','計上月','配賦後税抜','分類'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{drillLines.slice(drillPage*100,(drillPage+1)*100).map((r,i)=><tr key={i}><td>{r.id} / {r.report_id} / {r.source_row||'手入力'}</td><td>{r.work_title} / {r.product_sku}</td><td>{r.partner_name}</td><td>{r.department_name}</td><td>{r.distribution_label} / {r.service_name} / {r.settlement_method}</td><td>{r.accounting_month}</td><td>{money(r.amount)}</td><td><button className="secondary" onClick={()=>setEdit({mode:'department',saleId:r.id,baseVersion:r.department_version,department:r.department_name==='未分類'?'':r.department_name,reason:''})}>部門</button><button className="secondary" onClick={()=>setEdit({mode:'distribution',saleId:r.id,baseVersion:r.distribution_version||0,distributionCode:r.distribution_code,territory:r.territory||'',serviceName:r.service_name==='未確認'?'':r.service_name,settlementMethod:r.settlement_method==='未確認'?'unverified':r.settlement_method,reason:''})}>流通</button></td></tr>)}</tbody></table></div></section>}
 {edit&&<section className="card"><form className="grid-form" onSubmit={classify}><h3>売上 #{edit.saleId} の{edit.mode==="distribution"?"流通":"部門"}分類</h3>{edit.mode==="distribution"?<><label>流通<select required value={edit.distributionCode} onChange={e=>setEdit({...edit,distributionCode:e.target.value})}>{result.types.filter(t=>!t.legacy||t.code===edit.distributionCode).map(t=><option key={t.code} value={t.code}>{t.label}</option>)}</select></label><label>地域<input value={edit.territory} onChange={e=>setEdit({...edit,territory:e.target.value})}/></label><label>サービス<input value={edit.serviceName} onChange={e=>setEdit({...edit,serviceName:e.target.value})}/></label><label>取引方法<select value={edit.settlementMethod} onChange={e=>setEdit({...edit,settlementMethod:e.target.value})}>{["unverified","royalty","MG","FLAT","other"].map(v=><option key={v} value={v}>{v==="unverified"?"未確認":v}</option>)}</select></label></>:<label>部門名（空欄は未分類）<input maxLength="100" value={edit.department} onChange={e=>setEdit({...edit,department:e.target.value})}/></label>}<label>根拠・変更理由<input required maxLength="1000" value={edit.reason} onChange={e=>setEdit({...edit,reason:e.target.value})}/></label><button>新版として保存</button><button type="button" className="secondary" onClick={()=>setEdit(null)}>閉じる</button></form></section>}
 <p className="note">{result.scope} ／ 生成 {new Date(result.generatedAt).toLocaleString('ja-JP')}</p></>}
 </>}
 </div>;
}
