import {isDbConflict} from './data-platform/db-errors.mjs';
import {expenseSource} from './expense-sheet/expense-read.mjs';
import {integer,isoDate,month,toCsv} from './csv.mjs';
import {channelName,reportBreakdowns} from './report-center-model.mjs';
import {resolveTerritory,territoryKey,territoryLabel} from './sales-ops/sales-catalog-model.mjs';
import {labelOf} from './ui/labels.mjs';
import {DISTRIBUTION_TYPE_LABEL_SQL} from './distribution-label.mjs';

const text=(v,max=1000,required=false)=>{const s=String(v??'').trim();if(s.length>max||(required&&!s))throw Error('入力文字数または必須項目を確認してください');return s||null};
const safe=v=>typeof v==='string'&&/^[\s]*[=+@\-]/.test(v)?`'${v}`:v;
const sum=(values)=>{const n=values.reduce((a,v)=>a+BigInt(v),0n);if(n>BigInt(Number.MAX_SAFE_INTEGER)||n<BigInt(Number.MIN_SAFE_INTEGER))throw Error('金額合計が安全な整数範囲外です');return Number(n)};
const defaultCode=kind=>({digital:'digital_unknown',package:'package_unknown',theatrical:'theatrical',broadcast:'broadcast_unknown'}[kind]||'other');
export function reportMonths(start){month(start);const [y,m]=start.split('-').map(Number);return Array.from({length:12},(_,i)=>`${y+Math.floor((m-1+i)/12)}-${String((m-1+i)%12+1).padStart(2,'0')}`)}
export function pivotRows(lines,months,keys){const groups=new Map();for(const row of lines){const key=JSON.stringify(keys.map(k=>row[k]));if(!groups.has(key))groups.set(key,{...Object.fromEntries(keys.map(k=>[k,row[k]])),values:months.map(()=>0)});const target=groups.get(key),index=months.indexOf(row.accounting_month);if(index>=0)target.values[index]=sum([target.values[index],row.amount]);}return [...groups.values()].map(row=>({...row,total:sum(row.values)}))}

export function registerReportingRoutes(app,{db,bad,body,permittedProjects,settlementWork,allocatedSaleParts}){
 const wrap=fn=>async c=>{try{return await fn(c)}catch(e){return bad(c,e.message,isDbConflict(e)||/stale|immutable/i.test(e.message)?409:400,undefined,e)}};
 const finance=async c=>{const i=c.get('identity');if(i.role==='production')return null;const projects=await permittedProjects(db,i,true);if(!projects.length)return null;const works=await db.all('SELECT * FROM works WHERE org_id=?',[i.org_id]);return {i,works:works.filter(w=>projects.some(p=>p.id===w.project_id))}};
 const audit=(i,action,entity,id,detail)=>({sql:'INSERT INTO audit_log(org_id,user_id,action,entity_type,entity_id,detail_json) VALUES(?,?,?,?,?,?)',params:[i.org_id,i.user_id,action,entity,String(id),JSON.stringify(detail)]});
 async function distributionTypes(){return db.all(`SELECT t.code,t.family,t.utilization,t.sort_order,m.distribution_name,m.transaction_method,m.sales_type,m.notes,m.source_sha256,m.source_row,CASE WHEN m.code IS NULL THEN 1 ELSE 0 END AS legacy,${DISTRIBUTION_TYPE_LABEL_SQL} AS label FROM distribution_types t LEFT JOIN distribution_master m ON m.code=t.code ORDER BY CASE WHEN m.code IS NULL THEN 1 ELSE 0 END,t.sort_order`)}
 app.get('/api/distribution-master',wrap(async c=>{const rows=await db.all('SELECT * FROM distribution_master ORDER BY source_row');return c.json({ok:true,rows,calculationRulesStatus:'pending',source:'流通マスタ.csv'})}));
 async function saleScope(i,id){const sale=await db.get('SELECT * FROM sale_lines WHERE org_id=? AND id=?',[i.org_id,id]);if(!sale)return null;const maps=sale.product_id?await db.all('SELECT * FROM product_works WHERE org_id=? AND product_id=?',[i.org_id,sale.product_id]):[];const works=[...new Set([sale.work_id,...maps.map(m=>m.work_id)])];for(const w of works)if(!await settlementWork(i,w))return null;return sale}
 async function invoiceScope(i,id){if(i.role==='production')return null;const invoice=await db.get('SELECT * FROM billing_invoices WHERE org_id=? AND id=?',[i.org_id,id]);if(!invoice)return null;const rows=await db.all('SELECT DISTINCT work_id FROM billing_invoice_line_works WHERE org_id=? AND invoice_id=?',[i.org_id,id]);if(!rows.length)return null;for(const row of rows)if(!await settlementWork(i,row.work_id))return null;return invoice}
 async function plans(org,id){return db.all(`SELECT q.*,d.decision,d.version_no,d.effective_on,d.reason AS decision_reason,d.created_by AS decided_by,d.created_at AS decided_at FROM receipt_plan_requests q LEFT JOIN receipt_plan_decisions d ON d.org_id=q.org_id AND d.request_id=q.id WHERE q.org_id=? AND q.invoice_id=? ORDER BY q.id`,[org,id])}
 const currentPlan=(invoice,history,asOf='9999-12-31')=>{const approved=history.filter(x=>x.decision==='approved'&&x.effective_on<=asOf).sort((a,b)=>b.version_no-a.version_no)[0];return {version:approved?.version_no||0,dueDate:approved?.proposed_due_date||invoice.due_date}};
 async function receiptEvents(org,id){return db.all(`SELECT r.id AS receipt_id,r.reference,r.received_on,a.amount_yen,v.reversed_on FROM billing_receipt_allocations a JOIN billing_receipts r ON r.org_id=a.org_id AND r.id=a.receipt_id LEFT JOIN billing_receipt_reversals v ON v.org_id=r.org_id AND v.receipt_id=r.id WHERE a.org_id=? AND a.invoice_id=? ORDER BY r.received_on,r.id`,[org,id])}
 const paidAt=(events,asOf)=>sum(events.filter(e=>e.received_on<=asOf&&(!e.reversed_on||e.reversed_on>asOf)).map(e=>e.amount_yen));
 async function ledger(context,start,asOf){const months=reportMonths(start),rows=[],{i}=context;const invoices=await db.all('SELECT i.*,p.name AS partner_name,v.voided_on FROM billing_invoices i JOIN partners p ON p.org_id=i.org_id AND p.id=i.partner_id LEFT JOIN billing_invoice_voids v ON v.org_id=i.org_id AND v.invoice_id=i.id WHERE i.org_id=? ORDER BY i.invoice_date,i.id',[i.org_id]);for(const inv of invoices){if(inv.invoice_date>asOf||!await invoiceScope(i,inv.id))continue;const [history,events]=await Promise.all([plans(i.org_id,inv.id),receiptEvents(i.org_id,inv.id)]),plan=currentPlan(inv,history,asOf),paid=paidAt(events,asOf),isVoid=!!inv.voided_on&&inv.voided_on<=asOf;rows.push({...inv,history,events,planVersion:currentPlan(inv,history).version,plannedDate:plan.dueDate,paid,balance:isVoid?0:inv.amount_inc_tax-paid,isVoid,values:months.map(m=>sum(events.flatMap(e=>[e.received_on<=asOf&&e.received_on.startsWith(m)?e.amount_yen:0,e.reversed_on&&e.reversed_on<=asOf&&e.reversed_on.startsWith(m)?-e.amount_yen:0])))})}return {ok:true,months,asOf,rows,totals:months.map((m,index)=>({month:m,actual:sum(rows.map(r=>r.values[index])),plannedRemaining:sum(rows.filter(r=>!r.isVoid&&r.plannedDate.startsWith(m)).map(r=>r.balance))}))}}
 app.get('/api/distribution-types',wrap(async c=>c.json({ok:true,rows:await distributionTypes()})));
 app.get('/api/report-center',wrap(async c=>{const ctx=await finance(c);if(!ctx)return bad(c,'帳票への財務権限がありません',403);const {i,works}=ctx,months=reportMonths(c.req.query('start')||`${new Date().getFullYear()}-01`),workId=c.req.query('workId')?integer(c.req.query('workId')):null;if(workId&&!works.some(w=>w.id===workId))return bad(c,'作品への権限がありません',403);
 const sales=await db.all(`SELECT s.*,r.kind,p.name AS partner_name,pr.sku AS product_sku,pr.name AS product_name,d.distribution_code,d.territory,d.service_name,d.settlement_method,d.version_no AS distribution_version FROM sale_lines s JOIN report_imports r ON r.org_id=s.org_id AND r.id=s.report_id JOIN partners p ON p.org_id=s.org_id AND p.id=s.partner_id LEFT JOIN products pr ON pr.org_id=s.org_id AND pr.id=s.product_id LEFT JOIN sale_distribution_versions d ON d.org_id=s.org_id AND d.sale_id=s.id AND d.version_no=(SELECT MAX(x.version_no) FROM sale_distribution_versions x WHERE x.org_id=s.org_id AND x.sale_id=s.id) WHERE s.org_id=? AND r.status='active' AND s.accounting_month BETWEEN ? AND ? ORDER BY s.id`,[i.org_id,months[0],months[11]]);
 const types=await distributionTypes(),maps=await db.all('SELECT * FROM product_works WHERE org_id=?',[i.org_id]),visible=new Map(works.map(w=>[w.id,w])),lines=allocatedSaleParts(sales,maps).filter(x=>visible.has(x.allocated_work_id)&&(!workId||x.allocated_work_id===workId)).map(x=>({id:x.id,source_row:x.source_row,report_id:x.report_id,product_id:x.product_id,product_sku:x.product_sku||'未登録',product_name:x.product_name||'商品未登録',partner_id:x.partner_id,partner_name:x.partner_name,accounting_month:x.accounting_month,territory:x.territory,service_name:x.service_name,settlement_method:x.settlement_method,distribution_version:x.distribution_version,work_id:x.allocated_work_id,work_title:visible.get(x.allocated_work_id).title,distribution_code:x.distribution_code||defaultCode(x.kind),distribution_label:types.find(t=>t.code===(x.distribution_code||defaultCode(x.kind)))?.label||'未確認',amount:x.allocated_amount_ex_tax}));
 const byPartner=pivotRows(lines,months,['partner_id','partner_name','distribution_code','distribution_label']),byWork=pivotRows(lines,months,['work_id','work_title','distribution_code','distribution_label']),byProduct=pivotRows(lines,months,['product_id','product_sku','product_name','distribution_code','distribution_label']),byDistribution=pivotRows(lines,months,['distribution_code','distribution_label']),totals=months.map(m=>sum(lines.filter(x=>x.accounting_month===m).map(x=>x.amount)));
 if(c.req.query('format')==='csv'){const choices={work:{rows:byWork,key:'work_title',label:'作品'},product:{rows:byProduct,key:'product_name',label:'商品'},distribution:{rows:byDistribution,key:'distribution_label',label:'流通'},partner:{rows:byPartner,key:'partner_name',label:'取引先'}},mode=Object.hasOwn(choices,c.req.query('group'))?c.req.query('group'):'partner',{rows,key,label}=choices[mode];c.header('Content-Disposition',`attachment; filename="sales-${mode}-${months[0]}.csv"`);return c.text('\uFEFF'+toCsv([...(mode==='product'?['商品ID','商品コード']:[]),label,'流通ID','流通',...months,'合計'],rows.map(r=>[...(mode==='product'?[r.product_id,safe(r.product_sku)]:[]),safe(r[key]),r.distribution_code,safe(r.distribution_label),...r.values,r.total])))}
 const dimensions=await db.all('SELECT d.* FROM report_sale_dimensions_versions d WHERE d.org_id=? AND d.version_no=(SELECT MAX(v.version_no) FROM report_sale_dimensions_versions v WHERE v.org_id=d.org_id AND v.sale_id=d.sale_id)',[i.org_id]);
 const kindBySale=new Map(sales.map(r=>[r.id,r.kind]));for(const line of lines){const dimension=dimensions.find(d=>d.sale_id===line.id);line.kind=kindBySale.get(line.id);line.major_category_label=channelName(line.kind);line.department_name=dimension?.department_name||'未分類';line.department_version=dimension?.version_no||0;line.service_name=line.service_name||'未確認';line.settlement_method=line.settlement_method||'未確認';}
 const expenses=(await db.all(`SELECT * FROM ${expenseSource()} WHERE org_id=? AND accounting_month BETWEEN ? AND ? ORDER BY id`,[i.org_id,months[0],months[11]])).filter(e=>workId?e.work_id===workId:e.work_id?visible.has(e.work_id):works.some(w=>w.project_id===e.project_id));
 return c.json({ok:true,generatedAt:new Date().toISOString(),months,totals,total:sum(totals),byPartner,byWork,byProduct,byDistribution,lines,types,expenses,...reportBreakdowns(lines,months,works.filter(w=>!workId||w.id===workId),expenses),scope:'閲覧できる作品への配賦済み税抜売上。総額・作品別・取引先別は同じ明細の別集計で、相互に足しません。'})}));
 app.post('/api/report-center/departments',wrap(async c=>{const i=c.get('identity'),b=await body(c),saleId=integer(b.saleId);if(!await saleScope(i,saleId))return bad(c,'明細の全配賦作品への財務権限が必要です',403);const base=integer(b.baseVersion),last=await db.get('SELECT COALESCE(MAX(version_no),0) AS n FROM report_sale_dimensions_versions WHERE org_id=? AND sale_id=?',[i.org_id,saleId]);if(last.n!==base)return bad(c,'部門分類が更新されています。再読込してください',409);const department=text(b.department,100),reason=text(b.reason,1000,true);await db.batch([{sql:'INSERT INTO report_sale_dimensions_versions(org_id,sale_id,version_no,department_name,reason,created_by) VALUES(?,?,?,?,?,?)',params:[i.org_id,saleId,base+1,department,reason,i.user_id]},audit(i,'classify_department','sale',saleId,{version:base+1,department,reason})]);return c.json({ok:true,version:base+1},201)}));
 app.post('/api/report-center/classifications',wrap(async c=>{const i=c.get('identity'),b=await body(c),saleId=integer(b.saleId),sale=await saleScope(i,saleId);if(!sale)return bad(c,'明細の全配賦作品への財務権限が必要です',403);const type=await db.get('SELECT * FROM distribution_types WHERE code=?',[String(b.distributionCode)]);if(!type)throw Error('流通区分を選択してください');const base=integer(b.baseVersion),last=await db.get('SELECT COALESCE(MAX(version_no),0) AS n FROM sale_distribution_versions WHERE org_id=? AND sale_id=?',[i.org_id,saleId]);if(last.n!==base)return bad(c,'区分が更新されています。再読込してください',409);if(!['unverified','royalty','MG','FLAT','other'].includes(b.settlementMethod))throw Error('精算方式を確認してください');const reason=text(b.reason,1000,true);await db.batch([{sql:'INSERT INTO sale_distribution_versions(org_id,sale_id,version_no,distribution_code,territory,service_name,settlement_method,reason,created_by) VALUES(?,?,?,?,?,?,?,?,?)',params:[i.org_id,saleId,base+1,type.code,text(b.territory,100),text(b.serviceName,100),b.settlementMethod,reason,i.user_id]},audit(i,'classify','sale',saleId,{version:base+1,reason})]);return c.json({ok:true,version:base+1},201)}));
 app.get('/api/receipt-sheet',wrap(async c=>{const ctx=await finance(c);if(!ctx)return bad(c,'入金表への財務権限がありません',403);const result=await ledger(ctx,c.req.query('start')||`${new Date().getFullYear()}-01`,isoDate(c.req.query('asOf')||new Date().toISOString().slice(0,10)));if(c.req.query('format')==='csv'){c.header('Content-Disposition','attachment; filename="receipt-sheet.csv"');return c.text('\uFEFF'+toCsv(['請求番号','取引先','請求日','契約期日','入金予定日','請求額','入金済','残高',...result.months],result.rows.map(r=>[safe(r.invoice_number),safe(r.partner_name),r.invoice_date,r.due_date,r.plannedDate,r.amount_inc_tax,r.paid,r.balance,...r.values])))}return c.json(result)}));
 app.post('/api/receipt-plan/requests',wrap(async c=>{const i=c.get('identity'),b=await body(c),invoiceId=integer(b.invoiceId),invoice=await invoiceScope(i,invoiceId);if(!invoice)return bad(c,'請求書の全作品への財務権限が必要です',403);if(invoice.status!=='issued')return bad(c,'取消済み請求です',409);const plan=currentPlan(invoice,await plans(i.org_id,invoiceId));if(integer(b.baseVersion)!==plan.version)return bad(c,'入金予定が更新されています',409);const due=isoDate(b.proposedDueDate),reason=text(b.reason,1000,true);if(due<invoice.invoice_date||due===plan.dueDate)throw Error('請求日以降の異なる予定日を指定してください');const events=await receiptEvents(i.org_id,invoiceId);if(paidAt(events,'9999-12-31')>=invoice.amount_inc_tax)return bad(c,'完済済み請求の予定は変更できません',409);const result=await db.get('INSERT INTO receipt_plan_requests(org_id,invoice_id,base_version,previous_due_date,proposed_due_date,reason,created_by) VALUES(?,?,?,?,?,?,?) RETURNING id',[i.org_id,invoiceId,plan.version,plan.dueDate,due,reason,i.user_id]);return c.json({ok:true,id:result.id},201)}));
 app.post('/api/receipt-plan/requests/:id/decide',wrap(async c=>{const i=c.get('identity');if(i.role!=='admin')return bad(c,'予定変更の承認・却下は管理者が行います',403);const q=await db.get('SELECT * FROM receipt_plan_requests WHERE org_id=? AND id=?',[i.org_id,integer(c.req.param('id'))]);if(!q)return bad(c,'申請がありません',404);const invoice=await invoiceScope(i,q.invoice_id);if(!invoice)return bad(c,'請求書の権限がありません',403);const b=await body(c),decision=String(b.decision),reason=text(b.reason,1000,true),effective=isoDate(b.effectiveOn||new Date().toISOString().slice(0,10));if(!['approved','rejected'].includes(decision))throw Error('承認か却下を選択してください');const history=await plans(i.org_id,invoice.id);if(history.some(x=>x.id===q.id&&x.decision))return bad(c,'申請は決定済みです',409);if(decision==='approved'){if(invoice.status!=='issued'||currentPlan(invoice,history).version!==q.base_version)return bad(c,'請求・予定が変更されています。再申請してください',409);if(effective<invoice.invoice_date||history.some(x=>x.decision==='approved'&&x.effective_on>effective))throw Error('請求日・前回変更日以降を指定してください');if(paidAt(await receiptEvents(i.org_id,invoice.id),'9999-12-31')>=invoice.amount_inc_tax)return bad(c,'完済済みです',409)}await db.batch([{sql:'INSERT INTO receipt_plan_decisions(org_id,request_id,invoice_id,decision,version_no,effective_on,reason,created_by) VALUES(?,?,?,?,?,?,?,?)',params:[i.org_id,q.id,q.invoice_id,decision,decision==='approved'?q.base_version+1:null,effective,reason,i.user_id]},audit(i,decision,'receipt_plan',q.id,{effective,reason})]);return c.json({ok:true})}));
 app.get('/api/sales-catalog',wrap(async c=>{const ctx=await finance(c);if(!ctx)return bad(c,'営業一覧への権限がありません',403);const {i,works}=ctx,asOf=isoDate(c.req.query('asOf')||new Date(Date.now()+9*36e5).toISOString().slice(0,10)),types=await distributionTypes(),rows=await db.all(`SELECT v.*,w.title AS work_title,t.label AS distribution_label,t.family FROM sales_availability_versions v JOIN works w ON w.org_id=v.org_id AND w.id=v.work_id JOIN distribution_types t ON t.code=v.distribution_code WHERE v.org_id=? AND v.version_no=(SELECT MAX(x.version_no) FROM sales_availability_versions x WHERE x.org_id=v.org_id AND x.work_id=v.work_id AND x.distribution_code=v.distribution_code AND x.territory=v.territory) ORDER BY w.id,t.sort_order,v.territory`,[i.org_id]),agreementRows=await db.all(`SELECT a.work_id,a.contract_code,t.channel,t.territory,t.license_start,t.license_end FROM sales_agreements a JOIN sales_agreement_term_versions t ON t.org_id=a.org_id AND t.agreement_id=a.id WHERE a.org_id=? AND t.version_no=(SELECT MAX(z.version_no) FROM sales_agreement_term_versions z WHERE z.org_id=a.org_id AND z.agreement_id=a.id)`,[i.org_id]);const visible=rows.filter(r=>works.some(w=>w.id===r.work_id)).map(r=>{const overlaps=agreementRows.filter(a=>a.work_id===r.work_id&&(a.channel===r.family||r.family==='unverified')&&(!a.territory||territoryKey(a.territory)===territoryKey(r.territory))&&(!a.license_end||!r.release_on||a.license_end>=r.release_on)&&(!a.license_start||!r.sales_end_on||a.license_start<=r.sales_end_on));const master=types.find(t=>t.code===r.distribution_code);return {...r,distribution_label:master?.label||r.distribution_label,distribution_name:master?.distribution_name,transaction_method:master?.transaction_method,sales_type:master?.sales_type,territory_label:territoryLabel(r.territory),overlaps,state:r.status==='withdrawn'?labelOf('availabilityStatus','withdrawn'):r.status!=='confirmed'||!r.release_on||!r.sales_end_on?labelOf('availabilityStatus','draft'):asOf<r.release_on?'解禁前':asOf>r.sales_end_on?'販売終了':overlaps.length?'販売契約との重複を確認':'期間内・条件確認済み'}});const missing=works.filter(w=>!visible.some(r=>r.work_id===w.id)).map(w=>({work_id:w.id,work_title:w.title,state:'流通条件未登録'}));
 if(c.req.query('format')==='csv'){c.header('Content-Disposition','attachment; filename="sales-catalog.csv"');return c.text('\uFEFF'+toCsv(['作品','流通ID','流通','地域','解禁日','販売終了日','状態','販売条件','根拠','版'],[...visible,...missing].map(r=>[r.work_title,r.distribution_code,r.distribution_label,r.territory,r.release_on,r.sales_end_on,r.state,r.terms_text,r.source_reference,r.version_no].map(safe))))}return c.json({ok:true,asOf,rows:visible,missing,types,works,intakes:(await db.all('SELECT id,work_id,case_code,title FROM rights_intake_cases WHERE org_id=?',[i.org_id])).filter(r=>works.some(w=>w.id===r.work_id)),documents:await db.all('SELECT d.id,d.intake_case_id,d.title,d.reference FROM rights_intake_documents d JOIN rights_intake_cases c ON c.org_id=d.org_id AND c.id=d.intake_case_id WHERE d.org_id=? AND c.work_id IN ('+(works.map(()=>'?').join(',')||'NULL')+')',[i.org_id,...works.map(w=>w.id)])})}));
 app.post('/api/sales-catalog',wrap(async c=>{const i=c.get('identity'),b=await body(c),workId=integer(b.workId);if(!await settlementWork(i,workId))return bad(c,'作品への財務権限がありません',403);const code=String(b.distributionCode),type=await db.get('SELECT code FROM distribution_types WHERE code=?',[code]);if(!type)throw Error('流通を選んでください');const series=await db.all('SELECT territory,MAX(version_no) AS version_no FROM sales_availability_versions WHERE org_id=? AND work_id=? AND distribution_code=? GROUP BY territory',[i.org_id,workId,code]),resolved=resolveTerritory(String(b.territory??''),series);if(resolved.error)throw Error(resolved.error);const territory=resolved.territory,base=integer(b.baseVersion),last=await db.get('SELECT COALESCE(MAX(version_no),0) AS n FROM sales_availability_versions WHERE org_id=? AND work_id=? AND distribution_code=? AND territory=?',[i.org_id,workId,code,territory]);if(last.n!==base)return bad(c,resolved.match==='alias'&&base===0?`「${resolved.aliasOf}」は登録済みの「${territory}」と同じ地域です。一覧の「${territory}」の行から新しい版を作ってください（現在 第${last.n}版）`:'同じ作品・流通・地域の条件が更新されています。最新版から修正してください',409);const inherit=base>0&&!Object.hasOwn(b,'intakeCaseId')&&!Object.hasOwn(b,'documentId'),previous=inherit?await db.get('SELECT intake_case_id,document_id FROM sales_availability_versions WHERE org_id=? AND work_id=? AND distribution_code=? AND territory=? AND version_no=?',[i.org_id,workId,code,territory,base]):null;const start=b.releaseOn?isoDate(b.releaseOn):null,end=b.salesEndOn?isoDate(b.salesEndOn):null,terms=text(b.terms,5000,b.status==='confirmed'),source=text(b.sourceReference,1000,true),caseId=inherit?previous?.intake_case_id??null:b.intakeCaseId?integer(b.intakeCaseId):null,docId=inherit?previous?.document_id??null:b.documentId?integer(b.documentId):null;if(!['draft','confirmed','withdrawn'].includes(b.status)||!['unknown','exclusive','nonexclusive'].includes(b.exclusivity))throw Error('状態・独占条件を確認してください');if(b.status==='confirmed'&&(!start||!end))throw Error('条件確認済みには解禁日と終了日が必要です');if(start&&end&&end<start)throw Error('販売終了日は解禁日以降です');await db.batch([{sql:'INSERT INTO sales_availability_versions(org_id,work_id,distribution_code,territory,version_no,release_on,sales_end_on,terms_text,source_reference,intake_case_id,document_id,exclusivity,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',params:[i.org_id,workId,code,territory,base+1,start,end,terms||'',source,caseId,docId,b.exclusivity,b.status,i.user_id]},audit(i,'version','sales_availability',workId,{code,territory,territoryInput:String(b.territory??''),territoryMatch:resolved.match,version:base+1,intakeCaseId:caseId,documentId:docId})]);return c.json({ok:true,version:base+1,territory,territoryMatch:resolved.match,intakeCaseId:caseId,documentId:docId},201)}));
 app.get('/api/sales-catalog/versions',wrap(async c=>{const ctx=await finance(c);if(!ctx)return bad(c,'営業一覧への権限がありません',403);const {i,works}=ctx,workId=integer(c.req.query('workId')||''),code=String(c.req.query('distributionCode')||''),territory=String(c.req.query('territory')||'');if(!works.some(w=>w.id===workId))return bad(c,'作品への財務権限がありません',403);const rows=await db.all('SELECT v.id,v.work_id,v.distribution_code,v.territory,v.version_no,v.release_on,v.sales_end_on,v.terms_text,v.source_reference,v.intake_case_id,v.document_id,v.exclusivity,v.status,v.created_at,u.display_name AS created_by_name FROM sales_availability_versions v LEFT JOIN users u ON u.id=v.created_by WHERE v.org_id=? AND v.work_id=? AND v.distribution_code=? AND v.territory=? ORDER BY v.version_no DESC',[i.org_id,workId,code,territory]);return c.json({ok:true,rows})}));
}
