import {isDbConflict} from './data-platform/db-errors.mjs';
import {committeeHistory} from './committee-finance.mjs';
import {splitByAllocation} from './money-allocation.mjs';
import {isoDate} from './csv.mjs';
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const int=value=>{const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw fail('IDを確認してください');return n};
const month=value=>{const s=String(value||'');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(s))throw fail('計上月はYYYY-MM形式で指定してください');return s};
const safe=n=>{const x=typeof n==='bigint'?n:BigInt(n||0);if(x>BigInt(Number.MAX_SAFE_INTEGER)||x<BigInt(Number.MIN_SAFE_INTEGER))throw fail('金額が安全な整数範囲を超えています',409);return Number(x)};
const sum=(rows,key)=>safe(rows.reduce((n,row)=>n+BigInt(row[key]||0),0n));
const fields=['grossReported','netReported','platformFeeKnown','platformNet','windowFee','managerFee','expenseTotal','royaltyDeductions','productionRecoupDeductions','distributionPool','residual'];
const add=(target,source)=>{for(const key of fields)target[key]=safe(BigInt(target[key])+BigInt(source[key]||0));return target};
const zero=()=>Object.fromEntries(fields.map(key=>[key,0]));
const csvSafe=value=>{const s=String(value??'');return /^[=+\-@\t\r]/.test(s)?`'${s}`:s};
export function toCsv(headers,rows){const q=v=>`"${csvSafe(v).replaceAll('"','""')}"`;return '\ufeff'+[headers,...rows].map(row=>row.map(q).join(',')).join('\r\n')}

export function buildCommitteeReport(rows,selectedId,recipientPartnerId=null){
 const selected=rows.find(row=>Number(row.id)===Number(selectedId));if(!selected)throw fail('保存済み委員会報告がありません',404);
 if(recipientPartnerId&&!rows.some(row=>row.contract_id===selected.contract_id&&row.period_to<=selected.period_to&&row.calculation.windows.some(w=>w.payouts.some(p=>Number(p.partnerId)===Number(recipientPartnerId)))))throw fail('この契約の対象報告に存在する権利先を選択してください',400);
 const candidates=rows.filter(row=>row.contract_id===selected.contract_id&&row.period_from<=selected.period_to).sort((a,b)=>a.period_from.localeCompare(b.period_from)||a.id-b.id);if(candidates.some(row=>row.period_date_basis!==selected.period_date_basis))throw fail('同一契約の期間基準が混在しているため累計を作れません',409);
 for(let i=0;i<candidates.length;i++){if(i&&candidates[i].period_from<=candidates[i-1].period_to)throw fail('同一契約の報告期間が重複しているため累計を作れません',409)}const same=candidates.filter(row=>row.period_to<=selected.period_to);
 const gaps=[];for(let i=1;i<same.length;i++){const next=new Date(`${same[i-1].period_to}T00:00:00Z`);next.setUTCDate(next.getUTCDate()+1);if(next.toISOString().slice(0,10)!==same[i].period_from)gaps.push({afterSnapshotId:same[i-1].id,beforeSnapshotId:same[i].id})}
 const summarize=list=>{const total=zero(),members=new Map();for(const row of list){for(const window of row.calculation.windows)add(total,window);for(const window of row.calculation.windows)for(const payout of window.payouts){if(recipientPartnerId&&Number(payout.partnerId)!==Number(recipientPartnerId))continue;const old=members.get(payout.partnerId)||{partnerId:payout.partnerId,amount:0};old.amount=safe(BigInt(old.amount)+BigInt(payout.amount));members.set(payout.partnerId,old)}}return {...total,memberDistributions:[...members.values()]}};
 const previous=same.filter(row=>row.id!==selected.id&&row.period_to<selected.period_from),current=[selected],cumulative=same.filter(row=>row.period_to<=selected.period_to);
 const byChannel=[...new Set(cumulative.flatMap(row=>row.calculation.windows.map(w=>w.kind)))].map(kind=>({kind,label:cumulative.flatMap(row=>row.calculation.windows).find(w=>w.kind===kind)?.label||kind,...Object.fromEntries([['previous',previous],['current',current],['cumulative',cumulative]].map(([key,list])=>[key,list.flatMap(r=>r.calculation.windows).filter(w=>w.kind===kind).reduce((total,w)=>add(total,w),zero())]))}));
 const sourceLines=cumulative.flatMap(row=>(row.calculation.lines||[]).map(line=>({...line,snapshotId:row.id,workId:row.work_id})));
 const details=selected.calculation.windows.map(window=>({...window,payouts:recipientPartnerId?window.payouts.filter(p=>Number(p.partnerId)===Number(recipientPartnerId)):window.payouts}));
 const currentTotal=summarize(current),allMemberSum=safe(selected.calculation.windows.flatMap(w=>w.payouts).reduce((n,p)=>n+BigInt(p.amount),0n)),currentLines=(selected.calculation.lines||[]);const reconciliation={sourceLineCount:currentLines.length,sourceDifferenceYen:currentLines.length?safe(currentLines.reduce((n,l)=>n+BigInt(l.allocatedAmountExTax),0n))-currentTotal.grossReported-currentTotal.netReported:null,conservationDifferenceYen:currentTotal.platformNet-currentTotal.windowFee-currentTotal.managerFee-currentTotal.expenseTotal-currentTotal.royaltyDeductions-currentTotal.productionRecoupDeductions-currentTotal.distributionPool,memberDifferenceYen:currentTotal.distributionPool-allMemberSum-currentTotal.residual};
 return {funding:selected.calculation.funding||null,members:selected.calculation.members||[],history:committeeHistory(cumulative),deductions:cumulative.flatMap(r=>(r.calculation.deductions||[]).map(d=>({...d,snapshotId:r.id,periodFrom:r.period_from,periodTo:r.period_to}))),reconciliation,byChannel,sourceLines,kind:'committee_income',status:'draft_unverified',paymentStatus:'not_payment',generatedAt:new Date().toISOString(),selected:{snapshotId:selected.id,contractId:selected.contract_id,termVersionId:selected.term_version_id,workId:selected.work_id,periodFrom:selected.period_from,periodTo:selected.period_to,periodDateBasis:selected.period_date_basis,calculationVersion:selected.calculation_version,createdAt:selected.created_at,contractCode:selected.calculation.contract?.code||selected.calculation.contract?.contractCode||selected.calculation.contract?.contract_code,title:selected.calculation.contract?.title},recipientPartnerId:recipientPartnerId?Number(recipientPartnerId):null,partialDisplay:Boolean(recipientPartnerId),warnings:gaps.length?[`保存済み報告の間に${gaps.length}件の期間欠落があります。`]:[],gaps,totals:{previous:summarize(previous),current:summarize(current),cumulative:summarize(cumulative)},details,sourceSnapshotIds:cumulative.map(row=>row.id),sourceSnapshots:cumulative.map(row=>({snapshotId:row.id,termVersionId:row.term_version_id,periodFrom:row.period_from,periodTo:row.period_to,closeOn:row.close_on,reportOn:row.report_on,paymentOn:row.payment_on,createdAt:row.created_at})),sourceReports:(selected.calculation.selectedReports||[]).map(row=>({reportId:row.reportId,windowId:row.windowId,reportBasis:row.reportBasis})),sourceExpenses:(selected.calculation.selectedExpenses||[]).map(row=>({expenseId:row.expenseId,windowId:row.windowId,amount:row.amount}))};
}

function allocate(value,shares){const parts=splitByAllocation(safe(value),shares);return shares.map(share=>({...share,amount:parts.get(share.work_id)}))}
export function buildMgReport({direction,contract,versions,ledger,mappings,products,selectedVersionId,accountingMonth}){
 const selected=versions.find(v=>Number(v.id)===Number(selectedVersionId));if(!selected)throw fail('選択した契約の条件版ではありません',409);
 const ids=new Set(ledger.map(r=>Number(r.id))),replaced=new Set(ledger.filter(r=>r.reverses_entry_id&&ids.has(Number(r.reverses_entry_id))).map(r=>Number(r.reverses_entry_id)));
 const effective=ledger.filter(r=>!replaced.has(Number(r.id))&&r.accounting_month<=accountingMonth),versionById=new Map(versions.map(v=>[Number(v.id),v])),selectedEvaluations=new Map((selected.products||[]).map(p=>[Number(p.product_id),p.evaluation_yen]));
 const allProducts=new Set([...effective.map(r=>Number(r.product_id)),...(selected.products||[]).map(p=>Number(p.product_id))]),rows=[];for(const productId of allProducts){const shares=mappings.filter(m=>Number(m.product_id)===productId).sort((a,b)=>a.work_id-b.work_id);if(!shares.length||sum(shares,'allocation_bps')!==10000)throw fail('商品配賦が未設定または100%ではないため帳票を作れません',409);const product=products.find(p=>Number(p.id)===productId)||{},entries=effective.filter(r=>Number(r.product_id)===productId),sources=entries.map(row=>({entryId:row.id,termVersionId:row.term_version_id,termVersion:versionById.get(Number(row.term_version_id))?.version??null,accountingMonth:row.accounting_month,sourceReference:row.source_reference,reversesEntryId:row.reverses_entry_id,status:row.status})),workRows=shares.map(s=>({workId:s.work_id,allocationBps:s.allocation_bps,prior:zeroMg(),current:zeroMg(),cumulative:zeroMg()}));for(const entry of entries){const period=entry.accounting_month===accountingMonth?'current':'prior';for(const [key,column] of Object.entries({eligibleYen:'reported_eligible_yen',appliedYen:'applied_recoup_yen',overageYen:'reported_overage_yen',recognizedYen:'recognized_yen'}))for(const part of allocate(entry[column],shares)){const target=workRows.find(r=>r.workId===part.work_id);target[period][key]=safe(BigInt(target[period][key])+BigInt(part.amount))}}for(const target of workRows)for(const key of Object.keys(zeroMg()))target.cumulative[key]=safe(BigInt(target.prior[key])+BigInt(target.current[key]));const evaluations=selectedEvaluations.has(productId)?allocate(selectedEvaluations.get(productId),shares):[];for(const allocated of workRows)rows.push({...allocated,productId,productSku:product.sku||'',productName:product.name||'',evaluationYen:selectedEvaluations.has(productId)?evaluations.find(x=>x.work_id===allocated.workId).amount:null,evaluationStatus:selectedEvaluations.has(productId)?'selected_version':'unknown_historical',sources,unverifiedCount:entries.filter(r=>r.status==='unverified').length})}
 const cumulativeApplied=sum(effective,'applied_recoup_yen'),guarantee=safe(selected.mg_amount_yen),remaining=Math.max(0,guarantee-cumulativeApplied),exceed=Math.max(0,cumulativeApplied-guarantee),difference=safe(BigInt(sum(effective,'reported_eligible_yen'))-BigInt(cumulativeApplied));
 return {kind:'mg_status',status:'draft_unverified',generatedAt:new Date().toISOString(),knowledgeBasis:'current_known_corrections',direction,accountingMonth,contract:{id:contract.id,code:contract.code,title:contract.title,sourceReference:contract.source_reference},selectedVersion:{id:selected.id,version:selected.version,mode:selected.mode,guaranteeYen:guarantee,startsOn:selected.starts_on,endsOn:selected.ends_on,sourceReference:selected.source_reference,specialUnverified:Boolean(selected.special_unverified)},headline:{guaranteeYen:guarantee,cumulativeAppliedYen:cumulativeApplied,contractRemainingYen:remaining,appliedExceedYen:exceed,eligibleAppliedDifferenceYen:difference,remainingIndicative:selected.mode==='special'},warnings:[...(selected.mode==='special'?['特殊条件の残額は参考値です。手動確認してください。']:[]),...(difference!==sum(effective,'reported_overage_yen')?['消化対象額と、実充当・超過報告の合計が一致しません。原報告を確認してください。']:[])],rows,sourceEntryIds:effective.map(r=>r.id),unverifiedCount:effective.filter(r=>r.status==='unverified').length};
}
const zeroMg=()=>({eligibleYen:0,appliedYen:0,overageYen:0,recognizedYen:0});

export function registerRightsReportRoutes(app,{db,bad,settlementWork}){
 const routeError=(c,e)=>bad(c,e.message,e.status||500,undefined,e);app.use('/api/rights-reports/*',async(c,next)=>{if(c.get('identity')?.role==='production')return bad(c,'制作権限では権利先・MG帳票を参照できません',403);await next()});
 async function paymentScope(identity,settlementId,snapshotId){
  const target=settlementId?await db.get('SELECT work_id FROM settlement_contracts WHERE org_id=? AND id=?',[identity.org_id,settlementId]):await db.get('SELECT work_id FROM committee_report_snapshots WHERE org_id=? AND id=?',[identity.org_id,snapshotId]);
  if(!target||!await settlementWork(identity,target.work_id))throw fail('支払対象への財務権限がありません',403);return target;
 }
 app.get('/api/rights-reports/payments',async c=>{try{const i=c.get('identity'),workId=int(c.req.query('workId'));if(!await settlementWork(i,workId))throw fail('作品の財務権限がありません',403);const rows=await db.all(`SELECT e.*,p.name AS partner_name,COALESCE(c.contract_code,'委員会報告 #'||s.id) AS target_label FROM rights_payment_events e JOIN partners p ON p.org_id=e.org_id AND p.id=e.partner_id LEFT JOIN settlement_contracts c ON c.org_id=e.org_id AND c.id=e.settlement_contract_id LEFT JOIN committee_report_snapshots s ON s.org_id=e.org_id AND s.id=e.committee_snapshot_id WHERE e.org_id=? AND (c.work_id=? OR s.work_id=?) ORDER BY e.paid_on,e.id`,[i.org_id,workId,workId]);return c.json({ok:true,workId,rows,recordedNetYen:safe(rows.reduce((n,r)=>n+BigInt(r.amount_yen)*(r.reverses_event_id?-1n:1n),0n)),status:'recorded_events_not_bank_connection'})}catch(e){return routeError(c,e)}});
 app.post('/api/rights-reports/payments',async c=>{try{const i=c.get('identity'),b=await c.req.json(),settlementId=b.settlementContractId?int(b.settlementContractId):null,snapshotId=b.committeeSnapshotId?int(b.committeeSnapshotId):null;if(Boolean(settlementId)===Boolean(snapshotId))throw fail('支払対象を一つ選択してください');await paymentScope(i,settlementId,snapshotId);const partner=int(b.partnerId),amount=int(b.amountYen),paidOn=isoDate(b.paidOn),reference=String(b.reference||'').trim(),reason=String(b.reason||'').trim(),reverses=b.reversesEventId?int(b.reversesEventId):null;if(!reference||reference.length>160||!reason||reason.length>1000)throw fail('支払識別番号と根拠を入力してください');const result=await db.get('INSERT INTO rights_payment_events(org_id,settlement_contract_id,committee_snapshot_id,partner_id,amount_yen,paid_on,reference,reverses_event_id,reason,created_by) VALUES(?,?,?,?,?,?,?,?,?,?) RETURNING id',[i.org_id,settlementId,snapshotId,partner,amount,paidOn,reference,reverses,reason,i.user_id]);return c.json({ok:true,id:result.id},201)}catch(e){return routeError(c,Object.assign(e,{status:e.status||(isDbConflict(e)||/mismatch/i.test(e.message)?409:400)}))}});
 app.get('/api/rights-reports/committee',async c=>{try{const i=c.get('identity'),workId=int(c.req.query('workId')),snapshotId=int(c.req.query('snapshotId'));if(!await settlementWork(i,workId))throw fail('作品の財務権限がありません',403);const rows=(await db.all('SELECT * FROM committee_report_snapshots WHERE org_id=? AND work_id=? ORDER BY period_from,id',[i.org_id,workId])).map(r=>({...r,calculation:JSON.parse(r.calculation_json)}));const recipient=c.req.query('recipientPartnerId')?int(c.req.query('recipientPartnerId')):null,report=buildCommitteeReport(rows,snapshotId,recipient),snapshotIds=report.sourceSnapshotIds,allocatedWorks=snapshotIds.length?await db.all('SELECT DISTINCT pw.work_id FROM committee_snapshot_lines l JOIN sale_lines s ON s.org_id=l.org_id AND s.id=l.sale_id JOIN product_works pw ON pw.org_id=s.org_id AND pw.product_id=s.product_id WHERE l.org_id=? AND l.snapshot_id IN ('+snapshotIds.map(()=>'?').join(',')+')',[i.org_id,...snapshotIds]):[];for(const row of allocatedWorks)if(!await settlementWork(i,row.work_id))throw fail('報告元商品の全配賦作品への財務権限が必要です',403);const work=await db.get('SELECT code,title FROM works WHERE org_id=? AND id=?',[i.org_id,workId]),partners=await db.all('SELECT id,code,name FROM partners WHERE org_id=?',[i.org_id]);report.work=work;report.partners=partners.filter(p=>Object.values(report.totals).some(t=>t.memberDistributions.some(x=>Number(x.partnerId)===Number(p.id))));return c.json({ok:true,report})}catch(e){return routeError(c,e)}});
 app.get('/api/rights-reports/mg',async c=>{try{const i=c.get('identity'),direction=String(c.req.query('direction')||'');if(!['incoming','outgoing'].includes(direction))throw fail('契約方向を確認してください');const contractId=int(c.req.query('contractId')),selectedVersionId=int(c.req.query('termVersionId')),accountingMonth=month(c.req.query('month')),contract=await db.get(`SELECT * FROM mg_${direction}_contracts WHERE org_id=? AND id=?`,[i.org_id,contractId]);if(!contract)throw fail('MG契約がありません',404);const versions=await db.all(`SELECT * FROM mg_term_versions WHERE org_id=? AND ${direction}_contract_id=? ORDER BY version`,[i.org_id,contractId]);const productIds=[];for(const version of versions){version.products=await db.all('SELECT * FROM mg_version_products WHERE org_id=? AND term_version_id=?',[i.org_id,version.id]);productIds.push(...version.products.map(p=>p.product_id))}const unique=[...new Set(productIds)],mappings=unique.length?await db.all(`SELECT * FROM product_works WHERE org_id=? AND product_id IN (${unique.map(()=>'?').join(',')})`,[i.org_id,...unique]):[];for(const workId of [...new Set(mappings.map(m=>m.work_id))])if(!await settlementWork(i,workId))throw fail('全条件版の全配賦作品への財務権限が必要です',403);const ledger=await db.all(`SELECT l.* FROM mg_ledger_entries l JOIN mg_term_versions v ON v.org_id=l.org_id AND v.id=l.term_version_id WHERE l.org_id=? AND v.${direction}_contract_id=? ORDER BY l.id`,[i.org_id,contractId]),products=unique.length?await db.all(`SELECT id,sku,name FROM products WHERE org_id=? AND id IN (${unique.map(()=>'?').join(',')})`,[i.org_id,...unique]):[];return c.json({ok:true,report:buildMgReport({direction,contract,versions,ledger,mappings,products,selectedVersionId,accountingMonth})})}catch(e){return routeError(c,e)}});
}
