import {useEffect,useState} from 'react';
import {exportReport} from './report-output.mjs';
const money=n=>n==null?'未確認':Number(n).toLocaleString('ja-JP');
export default function RoyaltyReport({data,request}){
 const [workId,setWorkId]=useState(data.selectedWorkId||data.works[0]?.id||''),[result,setResult]=useState(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[form,setForm]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;setResult(null);setForm(null);setError('');Promise.all([request(`/settlement/preview?workId=${workId}`),request(`/settlement/contracts?workId=${workId}`),request(`/committee/snapshots?workId=${workId}`),request(`/rights-reports/payments?workId=${workId}`)]).then(([preview,contracts,snapshots,payments])=>active&&setResult({preview,contracts:contracts.contracts,snapshots:snapshots.rows,payments})).catch(e=>active&&setError(e.message));return()=>{active=false}},[workId,revision,request]);
 const partyName=id=>data.partners.find(p=>Number(p.id)===Number(id))?.name||`権利先 ${id}`;
 const signed=r=>r.reverses_event_id?-r.amount_yen:r.amount_yen;
 function output(format){try{exportReport(format,{filename:`royalties-${workId}`,title:'ロイヤリティ・記録した支払履歴',subtitle:`${data.works.find(w=>Number(w.id)===Number(workId))?.title||''} ／ JPY・全登録期間`,sheets:[{name:'ロイヤリティ試算',rows:[['契約','種別','PF控除後','手数料','権利元試算額','記録した支払'],...result.preview.contractSummaries.map(r=>[r.contractCode,r.contractType,r.platformNet,r.agencyFee,r.holderAmount??'未確認',result.payments.rows.filter(e=>e.settlement_contract_id===r.contractId).reduce((s,e)=>s+signed(e),0)])]},{name:'支払履歴',rows:[['イベントID','対象','権利先','実支払日・取消日','正味額','識別番号','取消元ID','根拠'],...result.payments.rows.map(r=>[r.id,r.target_label,r.partner_name,r.paid_on,signed(r),r.reference,r.reverses_event_id,r.reason])]},{name:'元売上明細',rows:[['契約ID','条件版ID','報告ID','売上ID','原本行','計上月','PF控除後','手数料','権利元試算'],...result.preview.lineResults.map(r=>[r.contractId,r.termVersionId,r.reportId,r.saleId,r.sourceRow,r.accountingMonth,r.platformNet,r.agencyFee,r.holderAmount])]},{name:'照合',rows:[['項目','値'],['記録した正味支払',result.payments.recordedNetYen],['イベント合計との差',result.payments.recordedNetYen-result.payments.rows.reduce((s,r)=>s+signed(r),0)],['未紐付け報告数',result.preview.unlinkedCount],['支払の意味','実施済み支払の証憑を登録した履歴。銀行照合・送金指示ではありません'],['試算の意味',result.preview.scopeNote]]}]})}catch(e){setError(e.message)}}
 const fresh=()=>({settlementContractId:'',committeeSnapshotId:'',partnerId:'',paidOn:new Date().toLocaleDateString('sv-SE'),amountYen:'',reference:'',reason:'',reversesEventId:''});
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await request('/rights-reports/payments',{method:'POST',body:JSON.stringify(form)});setRevision(v=>v+1);setForm(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const reversed=new Set(result?.payments.rows.map(e=>e.reverses_event_id).filter(Boolean)||[]);
 const recipients=!form?[]:form.settlementContractId?[result?.contracts.find(c=>String(c.id)===String(form.settlementContractId))?.holder_partner_id].filter(Boolean):[...new Set(result?.snapshots.find(s=>String(s.id)===String(form.committeeSnapshotId))?.calculation.windows.flatMap(w=>w.payouts.map(p=>p.partnerId))||[])];
 return <div className="stack"><section className="card"><h2>ロイヤリティ・支払履歴</h2><div className="toolbar"><label>作品<select value={workId} onChange={e=>setWorkId(e.target.value)}>{data.works.map(w=><option key={w.id} value={w.id}>{w.code}｜{w.title}</option>)}</select></label>{result&&<><button className="secondary" onClick={()=>output('csv')}>CSV</button><button className="secondary" onClick={()=>output('xlsx')}>Excel</button><button className="secondary" onClick={()=>output('print')}>印刷・PDF</button><button className="secondary" onClick={()=>output('html')}>印刷用HTML</button><button onClick={()=>setForm(fresh())}>支払実績を記録</button></>}</div><p>権利元への試算額と、証憑を確認して記録した支払実績を分けて表示します。下書き分配額から支払済みを推測しません。</p>{error&&<p role="alert" className="error">{error}</p>}</section>
 {result&&<><section className="card"><h3>個別権利契約のロイヤリティ試算（全登録期間）</h3><div className="rr-table"><table><thead><tr>{['契約','PF控除後','手数料','権利元試算','記録した支払','元明細'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{result.preview.contractSummaries.map(r=><tr key={r.contractId}><th>{r.contractCode}｜{r.title}</th><td>{money(r.platformNet)}</td><td>{money(r.agencyFee)}</td><td>{money(r.holderAmount)}</td><td>{money(result.payments.rows.filter(e=>e.settlement_contract_id===r.contractId).reduce((s,e)=>s+signed(e),0))}</td><td><details><summary>{r.lineCount}件</summary>{result.preview.lineResults.filter(l=>l.contractId===r.contractId).map(l=><p key={l.saleId}>報告#{l.reportId} 売上#{l.saleId} 条件版#{l.termVersionId} {l.accountingMonth} {money(l.platformNet)}円</p>)}</details></td></tr>)}</tbody></table></div>{result.preview.contractSummaries.length===0&&<p>個別権利契約は登録されていません。</p>}<p className="note">{result.preview.scopeNote}</p></section>
 <section className="card"><h3>製作委員会の分配下書きと支払記録</h3><div className="rr-table"><table><thead><tr><th>報告</th><th>対象期</th><th>権利先</th><th>分配下書き額</th><th>記録した支払</th></tr></thead><tbody>{result.snapshots.flatMap(s=>{const ids=[...new Set(s.calculation.windows.flatMap(w=>w.payouts.map(p=>p.partnerId)))];return ids.map(id=><tr key={`${s.id}-${id}`}><td>#{s.id}</td><td>{s.period_from}〜{s.period_to}</td><th>{partyName(id)}</th><td>{money(s.calculation.windows.flatMap(w=>w.payouts).filter(p=>p.partnerId===id).reduce((n,p)=>n+p.amount,0))}</td><td>{money(result.payments.rows.filter(e=>e.committee_snapshot_id===s.id&&e.partner_id===id).reduce((n,e)=>n+signed(e),0))}</td></tr>)})}</tbody></table></div>{!result.snapshots.length&&<p>保存済み分配下書きはありません。</p>}</section>
 <section className="card"><h3>支払イベント履歴</h3><p>正味記録額 {money(result.payments.recordedNetYen)} 円</p><div className="rr-table"><table><thead><tr>{['ID','対象／権利先','支払・取消日','金額','識別番号／根拠','操作'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{result.payments.rows.map(r=><tr key={r.id}><td>#{r.id}{r.reverses_event_id&&`（#${r.reverses_event_id}の取消）`}</td><td>{r.target_label} / {r.partner_name}</td><td>{r.paid_on}</td><td>{money(signed(r))}</td><td>{r.reference}<small>{r.reason}</small></td><td>{!r.reverses_event_id&&!reversed.has(r.id)&&<button className="secondary" onClick={()=>setForm({...fresh(),settlementContractId:r.settlement_contract_id||'',committeeSnapshotId:r.committee_snapshot_id||'',partnerId:r.partner_id,amountYen:r.amount_yen,reversesEventId:r.id,reference:`${r.reference}-取消`})}>取消を記録</button>}</td></tr>)}</tbody></table></div>{!result.payments.rows.length&&<p>支払実績は未登録です。</p>}</section></>}
 {form&&result&&<section className="card"><h3>{form.reversesEventId?`支払 #${form.reversesEventId} の取消記録`:'実施済み支払の記録'}</h3><form className="grid-form" onSubmit={save}><fieldset disabled={Boolean(form.reversesEventId)||busy}><label>対象<select required value={form.settlementContractId?`contract:${form.settlementContractId}`:form.committeeSnapshotId?`snapshot:${form.committeeSnapshotId}`:''} onChange={e=>{const [type,id]=e.target.value.split(':');setForm({...form,settlementContractId:type==='contract'?id:'',committeeSnapshotId:type==='snapshot'?id:'',partnerId:''})}}><option value="">選択してください</option>{result.contracts.filter(c=>c.holder_partner_id).map(c=><option key={`c${c.id}`} value={`contract:${c.id}`}>個別権利契約 {c.contract_code}</option>)}{result.snapshots.map(s=><option key={`s${s.id}`} value={`snapshot:${s.id}`}>委員会報告 #{s.id} {s.period_from}〜{s.period_to}</option>)}</select></label><label>権利先<select required value={form.partnerId} onChange={e=>setForm({...form,partnerId:e.target.value})}><option value="">選択してください</option>{recipients.map(id=><option key={id} value={id}>{partyName(id)}</option>)}</select></label><label>実支払額（円）<input required type="number" min="1" step="1" value={form.amountYen} onChange={e=>setForm({...form,amountYen:e.target.value})}/></label></fieldset><label>{form.reversesEventId?'取消日':'実支払日'}<input required type="date" value={form.paidOn} onChange={e=>setForm({...form,paidOn:e.target.value})}/></label><label>支払識別番号<input required maxLength="160" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label>証憑参照・理由<textarea required maxLength="1000" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button disabled={busy}>記録を保存</button><button type="button" className="secondary" onClick={()=>setForm(null)}>閉じる</button></form></section>}
 </div>;
}
