// 使い捨てDB・DEMO-SALES・demo-adminで実行。sampleはこのレシピ専用の一時フォルダへ生成する。
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {buildExpenseSamples} from '../../../../../apps/integrated-prototype/scripts/build-expense-samples.mjs';
import {openSubArea,openPage,until,runId} from './_sales.mjs';
const json=async(api,path)=>(await api.get('/api'+path)).json();
export default async({page,shot,step,api})=>{
 const directory=await mkdtemp(join(tmpdir(),'req6-browser-')),run=runId();
 try{
  const [sample]=await buildExpenseSamples(directory),options=await json(api,'/expense-sheet/options'),settings=(await json(api,'/expense-accounting/settings')).settings;
  const project=options.projects.find(p=>p.code==='DEMO-EXP-COMMON'),partner=options.partners.find(p=>p.code==='DEMO-PARTNER-EOM'),tax=settings.taxes.find(t=>t.code==='DEMO-TAX-10'),wh=settings.withholding.find(w=>w.code==='DEMO-WH-NONE');assert.ok(project&&partner&&tax&&wh,'seed-all-demoで依頼6の架空データを投入してください');
  await openSubArea(page,'計上',{expectPage:'帳票センター'});await page.getByRole('navigation',{name:'売上基幹・計上',exact:true}).getByRole('link',{name:/^経費集計シート/}).click();await page.getByRole('heading',{name:'経費集計シート',level:2,exact:true}).waitFor();
  const tabs=page.getByRole('group',{name:'経費の業務'}),sets=page.getByRole('group',{name:'列セット'});await page.getByLabel('基準日',{exact:true}).fill('2026-11-30');
  for(const [label,count,last] of [['基本25列',25,'出金日'],['旧22列',22,'費用区分'],['会計の確認',7,'状態'],['出金予定',6,'支払残額']]){await sets.getByRole('button',{name:label,exact:true}).click();const table=page.getByRole('table',{name:'経費集計シート',exact:true});await until(async()=>table.locator('thead th[data-key]').count(),n=>n===count,{label:label+'の列数'});assert.equal((await table.locator('thead th[data-key]').last().innerText()).replace(/[▲▼]/g,'').trim(),last);}
  step('expense-sheet-columns: 25・22・7・6列と末尾の見出し');await shot('expense-columns');await sets.getByRole('button',{name:'基本25列',exact:true}).click();
  const rows=(await json(api,'/expense-sheet?pageSize=500&asOf=2026-11-30')).rows,partial=rows.find(r=>r.invoice?.invoice_number?.includes('DEMO-INVOICE-PARTIAL'));assert.ok(partial);await page.getByLabel('支払先で絞る',{exact:true}).selectOption(String(partial.partner_id));await page.getByRole('table',{name:'経費集計シート',exact:true}).getByRole('row').filter({has:page.getByRole('cell',{name:String(partial.id),exact:true})}).click();const detail=page.locator('[aria-label="経費の詳細"]');for(const date of ['2026-09-14','2026-09-30','2026-10-31'])assert.ok((await detail.innerText()).includes(date));await detail.getByRole('heading',{name:'支払の履歴'}).waitFor();await shot('expense-dates-payments');step('expense-sheet-detail: 請求日・締め日・予定日と実出金の履歴');
  await tabs.getByRole('button',{name:'出金予定',exact:true}).click();await page.getByLabel('出金予定の基準日').fill('2026-11-30');for(const value of ['partner','closing']){await page.getByLabel('集計の切り口').selectOption(value);await page.getByRole('table',{name:'出金予定の集計',exact:true}).waitFor();await shot('payout-'+value);}step('expense-payout-groups: 支払先別・締め日別、除外件数');
  await tabs.getByRole('button',{name:'取込と保留',exact:true}).click();await page.getByLabel('取込ファイル').setInputFiles({name:'DEMO-expense-22.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await readFile(sample)});await page.getByLabel('取込先の案件').selectOption(String(project.id));await page.getByLabel('取込の発生日').fill('2026-09-14');await page.getByLabel('取込の税区分').selectOption(String(tax.id));await page.getByLabel('取込の源泉区分').selectOption(String(wh.id));await page.getByLabel('作品なしの共通経費として確認').check();await page.getByLabel('各行を別の領収書として確認').check();await page.getByLabel('取込・解消・取消の理由').fill('ブラウザ検証（架空） '+run);await page.getByRole('button',{name:'取込の下見',exact:true}).click();await page.getByRole('status').filter({hasText:'登録可 1件／保留 2件'}).waitFor();await shot('import-preview');await page.getByRole('button',{name:'この下見で登録',exact:true}).click();
  await until(async()=>json(api,'/expense-imports'),r=>r.rows.some(b=>b.events.some(e=>e.kind==='committed')),{label:'取込確定'});const batches=(await json(api,'/expense-imports')).rows,batch=batches.find(b=>b.file_name==='DEMO-expense-22.xlsx'),hold=(await json(api,'/expense-imports/holds')).rows.find(r=>r.batch_id===batch.id&&r.row_no===3);assert.ok(hold);
  await page.getByRole('table',{name:'保留の一覧',exact:true}).getByRole('row').filter({hasText:'支払先が見つかりません'}).first().click();await page.getByLabel('解消する支払先').selectOption(String(partner.id));await page.getByRole('button',{name:'取込の下見',exact:true}).click();await page.getByRole('status').filter({hasText:'登録可 2件／保留 1件'}).waitFor();await page.getByRole('button',{name:'保留を解消して登録',exact:true}).click();await until(async()=>json(api,'/expense-imports/holds'),r=>!r.rows.some(x=>x.id===hold.id),{label:'支払先の保留解消'});await shot('hold-resolved');step('expense-import-resolve: サンプル下見1可2保留→支払先1件を解消');
  // 新規取込の「支払先確認」は元のサンプルの2行目。一部払いで13,200−5,000=8,200。
  const bsBeforePayment=await json(api,'/reports/pl-bs?from=2026-09&to=2026-11&asOf=2026-11');
  const imported=(await json(api,'/expense-sheet?pageSize=500')).rows.find(r=>r.description==='支払先確認（架空）');assert.ok(imported);await tabs.getByRole('button',{name:'出金予定',exact:true}).click();await page.getByLabel('出金予定の基準日').fill('2026-11-30');await page.getByRole('table',{name:'出金予定の明細',exact:true}).getByRole('row').filter({hasText:'支払先確認（架空）'}).click();const form=page.getByRole('form',{name:'出金の記録',exact:true});await form.getByLabel('出金日',{exact:true}).fill('2026-10-05');await form.getByLabel('出金額（円）').fill('5000');await form.getByLabel('今回の源泉控除額（円）').fill('0');const cash=settings['account-classes'].find(c=>c.settlement_role==='cash'&&c.active);await form.getByLabel('現預金科目',{exact:true}).selectOption(String(cash.id));await form.getByLabel('出金の理由').fill('一部払いの検証（架空）');await form.getByRole('button',{name:'出金を記録',exact:true}).click();await until(async()=>json(api,`/expense-sheet/${imported.id}?asOf=2026-11-30`),r=>r.row.cash_due_yen===8200,{label:'一部払い後の残'});await shot('partial-payment');step('expense-partial-payment: 税込13,200円−出金5,000円=支払残8,200円');
  const bsAfterPayment=await json(api,'/reports/pl-bs?from=2026-09&to=2026-11&asOf=2026-11');const payable=r=>r.companyBs.rows.find(x=>x.key==='expense_payable').value;assert.equal(payable(bsBeforePayment)-payable(bsAfterPayment),5000);assert.equal(bsBeforePayment.companyPl.netIncome.period,bsAfterPayment.companyPl.netIncome.period);step('expense-plbs-payment: 出金で会社BSの未払金が5,000円減り、PLは変わらない');
  await tabs.getByRole('button',{name:'会計の設定',exact:true}).click();const cat=settings.categories.find(c=>c.code==='DEMO-EXP-work_other_expense');await page.getByRole('button',{name:`${cat.name}／版${cat.version_no}`,exact:true}).click();await page.getByLabel('変更理由',{exact:true}).fill('費用区分の版を確認（架空） '+run);await page.getByRole('button',{name:'版を追加',exact:true}).click();await until(async()=>json(api,'/expense-accounting/settings'),r=>r.settings.categories.some(c=>c.category_id===cat.category_id&&c.version_no===cat.version_no+1),{label:'費用区分の次版'});await shot('accounting-version');step('expense-settings-version: 理由つきの次版を追加、既存経費の参照版は維持');
 }finally{await rm(directory,{recursive:true,force:true});}
};
