const OPS=new Set(['select','rename','type','filter','replace','split','concat','calculate','sort','join','append','dedupe','group','pivot','unpivot']);
export const engineVersion='workbench-1';
const canonical=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
export async function hashValue(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(typeof v==='string'?v:canonical(v)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const clone=v=>structuredClone(v);
const keys=rows=>[...new Set(rows.flatMap(r=>Object.keys(r).filter(k=>k!=='_lineage')))];
const reserved=new Set(['_source','_lineage','id','version']);
function outputKey(k){if(typeof k!=='string'||!k||reserved.has(k))throw new Error(`出力列名が許可されていません: ${k}`);return k}
function need(row,key){if(!Object.hasOwn(row,key))throw new Error(`列がありません: ${key}`);return row[key]}
function typed(v,type){if(v==null||v==='')return null;if(type==='string')return String(v);if(type==='integer'){const n=Number(v);if(!Number.isSafeInteger(n))throw new Error(`安全な整数ではありません: ${v}`);return n}if(type==='number'){const n=Number(v);if(!Number.isFinite(n))throw new Error(`数値ではありません: ${v}`);return n}if(type==='boolean'){if(v===true||v==='true'||v===1||v==='1')return true;if(v===false||v==='false'||v===0||v==='0')return false;throw new Error(`真偽値ではありません: ${v}`)}if(type==='date'){const s=String(v),m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s),d=m&&new Date(Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3])));if(!m||d.toISOString().slice(0,10)!==s)throw new Error(`日付ではありません: ${v}`);return s}throw new Error(`型が許可されていません: ${type}`)}
function compare(a,op,b){if(op==='eq')return a===b;if(op==='neq')return a!==b;if(op==='gt')return a>b;if(op==='gte')return a>=b;if(op==='lt')return a<b;if(op==='lte')return a<=b;if(op==='contains')return String(a??'').includes(String(b));if(op==='is_null')return a==null;if(op==='not_null')return a!=null;throw new Error(`比較が許可されていません: ${op}`)}
function calc(row,p){const raw=(p.columns||[]).map(k=>need(row,k));if(raw.some(v=>v==null||v===''))throw new Error('計算列にnullがあります');const vals=raw.map(Number);if(vals.some(v=>!Number.isFinite(v)))throw new Error('計算列に数値以外があります');let n;if(p.operator==='add')n=vals.reduce((a,b)=>a+b,Number(p.constant||0));else if(p.operator==='subtract'&&vals.length===2)n=vals[0]-vals[1];else if(p.operator==='multiply')n=vals.reduce((a,b)=>a*b,p.constant==null?1:Number(p.constant));else if(p.operator==='divide'&&vals.length===2){if(vals[1]===0)throw new Error('0で除算できません');n=vals[0]/vals[1]}else throw new Error(`計算が許可されていません: ${p.operator}`);if(!Number.isFinite(n)||((p.round||vals.every(Number.isSafeInteger))&&Number.isInteger(n)&&!Number.isSafeInteger(n)))throw new Error('計算結果が安全な数値範囲外です');return p.round==='floor'?Math.floor(n):p.round==='ceil'?Math.ceil(n):p.round==='round'?Math.round(n):n}
const lin=r=>Array.isArray(r._lineage)?r._lineage:[];
function aggregate(rows,p){if(p==='count')return rows.length;const vs=rows.map(r=>r.value).filter(v=>v!=null).map(Number);if(vs.some(v=>!Number.isFinite(v)))throw new Error('集計対象に数値以外があります');if(p==='sum')return vs.reduce((a,b)=>a+b,0);if(p==='min')return vs.length?Math.min(...vs):null;if(p==='max')return vs.length?Math.max(...vs):null;if(p==='avg')return vs.length?vs.reduce((a,b)=>a+b,0)/vs.length:null;throw new Error(`集計が許可されていません: ${p}`)}
export function executeTransform(inputRows,steps=[],options={}){
 if(!Array.isArray(inputRows)||!Array.isArray(steps))throw new Error('rowsとstepsは配列で指定してください');let rows=clone(inputRows).map((r,i)=>({...r,_lineage:r._lineage||[{source:options.source||'input',row:i+1,key:r._source?.key??null}]}));const traces=[];
 for(const [index,step] of steps.entries()){if(!step||!OPS.has(step.operation))throw new Error(`step ${index+1}: 操作が許可されていません`);const p=step.parameters||{};const before=rows.length;
  if(step.operation==='select'){const cs=p.columns||[];rows=rows.map(r=>Object.fromEntries([...cs.map(k=>[k,need(r,k)]),...(r._source?[['_source',r._source]]:[]),['_lineage',lin(r)]]))}
  else if(step.operation==='rename'){const m=p.mapping||{};rows=rows.map(r=>{const n={...r};for(const [a,b] of Object.entries(m)){outputKey(b);if(a===b)continue;if(Object.hasOwn(n,b))throw new Error(`名前変更先が重複します: ${b}`);n[b]=need(n,a);delete n[a]}return n})}
  else if(step.operation==='type')rows=rows.map(r=>({...r,[p.column]:typed(need(r,p.column),p.type)}));
  else if(step.operation==='filter')rows=rows.filter(r=>compare(need(r,p.column),p.operator,p.value));
  else if(step.operation==='replace')rows=rows.map(r=>({...r,[p.column]:need(r,p.column)===p.from?p.to:need(r,p.column)}));
  else if(step.operation==='split'){(p.into||[]).forEach(outputKey);rows=rows.map(r=>{const parts=String(need(r,p.column)??'').split(String(p.delimiter));const n={...r};(p.into||[]).forEach((k,i)=>{if(Object.hasOwn(n,k))throw new Error(`出力列が重複します: ${k}`);n[k]=parts[i]??null});return n})}
  else if(step.operation==='concat'){outputKey(p.into);if(rows.some(r=>Object.hasOwn(r,p.into)))throw new Error(`出力列が重複します: ${p.into}`);rows=rows.map(r=>({...r,[p.into]:(p.columns||[]).map(k=>String(need(r,k)??'')).join(p.separator??'')}))}
  else if(step.operation==='calculate'){outputKey(p.into);if(rows.some(r=>Object.hasOwn(r,p.into)))throw new Error(`出力列が重複します: ${p.into}`);rows=rows.map(r=>({...r,[p.into]:calc(r,p)}))}
  else if(step.operation==='sort'){const by=p.by||[];rows=[...rows].sort((a,b)=>{for(const s of by){const av=need(a,s.column),bv=need(b,s.column);if(av===bv)continue;const c=av==null?1:bv==null?-1:av<bv?-1:1;return s.direction==='desc'?-c:c}return 0})}
  else if(step.operation==='join'){if(!['left','inner'].includes(p.kind))throw new Error('JOIN種別はleftまたはinnerを明示してください');const right=options.lookups?.[p.lookup];if(!Array.isArray(right))throw new Error(`参照表がありません: ${p.lookup}`);const rk=p.rightKey||p.leftKey,map=new Map(),available=new Set(keys(right));for(const col of p.columns||[])if(!available.has(col))throw new Error(`参照表に列がありません: ${col}`);for(const rr of right){const k=need(rr,rk);if(map.has(k))throw new Error(`JOIN参照キーが重複しています: ${k}`);map.set(k,rr)}const out=[];for(const r of rows){const rr=map.get(need(r,p.leftKey)),cols=(p.columns||keys(right)).filter(k=>k!==rk&&k!=='_source'),pairs=cols.map(k=>{const outKey=outputKey(p.prefix?`${p.prefix}${k}`:`${p.lookup}_${k}`);if(Object.hasOwn(r,outKey))throw new Error(`JOIN出力列が重複します: ${outKey}`);return [outKey,rr?.[k]??null]});if(rr)out.push({...r,...Object.fromEntries(pairs),_lineage:[...lin(r),...(rr._lineage||[{source:p.lookup,key:rr[rk]}])]});else if(p.kind==='left')out.push({...r,...Object.fromEntries(pairs)})}rows=out}
  else if(step.operation==='append'){const more=options.lookups?.[p.dataset];if(!Array.isArray(more))throw new Error(`追加表がありません: ${p.dataset}`);const schema=keys(rows),other=keys(more);if(canonical([...schema].sort())!==canonical([...other].sort()))throw new Error('追加表の列が一致しません');rows=[...rows,...clone(more).map((r,i)=>({...r,_lineage:r._lineage||[{source:p.dataset,row:i+1}]}))]}
  else if(step.operation==='dedupe'){if(!['first','error'].includes(p.keep))throw new Error('重複時の処理を明示してください');const seen=new Set(),out=[];for(const r of rows){const k=canonical((p.columns||[]).map(c=>need(r,c)));if(seen.has(k)){if(p.keep==='error')throw new Error(`重複があります: ${k}`);continue}seen.add(k);out.push(r)}rows=out}
  else if(step.operation==='group'){const map=new Map(),group=p.by||[];for(const r of rows){const k=canonical(group.map(c=>need(r,c)));if(!map.has(k))map.set(k,{values:group.map(c=>r[c]),rows:[]});map.get(k).rows.push(r)}rows=[...map.values()].map(g=>{const n=Object.fromEntries(group.map((c,i)=>[c,g.values[i]]));for(const a of p.aggregates||[])n[a.into]=aggregate(g.rows.map(r=>({value:a.column?need(r,a.column):null})),a.operation);n._lineage=g.rows.flatMap(lin);return n})}
  else if(step.operation==='pivot'){const group=p.by||[],map=new Map();for(const r of rows){const k=canonical(group.map(c=>need(r,c)));if(!map.has(k))map.set(k,{values:group.map(c=>r[c]),rows:[]});map.get(k).rows.push(r)}rows=[...map.values()].map(g=>{const n=Object.fromEntries(group.map((c,i)=>[c,g.values[i]]));for(const r of g.rows){const k=String(need(r,p.keyColumn));if(Object.hasOwn(n,k))throw new Error(`pivotキーが重複しています: ${k}`);n[k]=need(r,p.valueColumn)}n._lineage=g.rows.flatMap(lin);return n})}
  else if(step.operation==='unpivot'){const fixed=p.fixed||[],out=[];for(const r of rows)for(const c of (p.columns||keys([r]).filter(k=>!fixed.includes(k))))out.push({...Object.fromEntries(fixed.map(k=>[k,need(r,k)])),[p.keyInto||'attribute']:c,[p.valueInto||'value']:r[c],_lineage:lin(r)});rows=out}
  if(rows.length>10000||keys(rows).length>200||rows.some(r=>lin(r).length>100))throw new Error(`step ${index+1}: 出力上限を超えました`);traces.push({stepId:step.step_id||`step_${index+1}`,operation:step.operation,beforeRows:before,afterRows:rows.length});
 }
 const schema=keys(rows).filter(key=>key!=='_source').map(key=>({key,type:rows.find(r=>r[key]!=null)?.[key]===undefined?'unknown':typeof rows.find(r=>r[key]!=null)?.[key]}));return {rows,schema,traces,lineage:rows.map((r,i)=>({row:i+1,sources:lin(r)}))};
}
export const allowedOperations=[...OPS];
