import React,{useEffect,useState} from 'react';
import {LEGACY_EXPENSE_COLUMNS} from './expense-columns.mjs';
import {DataGrid} from '../ui/DataGrid.jsx';
import {Notice} from '../ui/Notice.jsx';
import {Field,Button,opts,num,post,latest,today,useAction,ExpenseEntry} from './ExpenseFields.jsx';
import {fileBase64} from './ExpenseInvoices.jsx';
export function ExpenseImports({request,options,onSaved}){const [file,setFile]=useState(null),[preview,setPreview]=useState(null),[state,setState]=useState({}),[revision,setRevision]=useState(0),[supplement,set]=useState({project_id:'',incurred_on:'',tax_category_version_id:'',withholding_category_version_id:'',common_expense:false,each_row_invoice:false}),[reason,setReason]=useState(''),[group,setGroup]=useState({from:2,to:2,key:'1',invoice_number:'',document_kind:'invoice'}),[groups,setGroups]=useState([]),[hold,setHold]=useState(null),[manual,setManual]=useState(null),[override,setOverride]=useState({}),[corrected,setCorrected]=useState(null),[cancelOn,setCancelOn]=useState(today()),action=useAction(()=>{setRevision(n=>n+1);});
 useEffect(()=>{let live=true;Promise.all([request('/expense-imports'),request('/expense-imports/holds'),request('/expense-pending')]).then(([b,h,m])=>live&&setState({batches:b.rows,holds:h.rows,pending:m.rows})).catch(error=>live&&setState({error}));return()=>{live=false;};},[request,revision]);
 const field=(key,label,type='text',values)=><Field label={label} value={supplement[key]} type={type} options={values} onChange={v=>set({...supplement,[key]:v})}/>;
 const supplementBody=()=>({...supplement,project_id:num(supplement.project_id),tax_category_version_id:num(supplement.tax_category_version_id),withholding_category_version_id:num(supplement.withholding_category_version_id),groups,overrides:hold?{[hold.row_no]:{...Object.fromEntries(Object.entries(override).filter(([,v])=>v!=='').map(([k,v])=>[k,k==='tax_difference_note'?v:num(v)])),...(corrected?{corrected_values:corrected}:{})}}:undefined});
 return <section className="card stack"><h3>取込と保留</h3><div className="es-tabs"><a href="/api/expense-sheet/template.xlsx?layout=legacy22" download>22列の雛形をダウンロード</a><a href="/api/expense-sheet/template.xlsx?layout=standard25" download>25列の雛形をダウンロード</a></div><p>Excel・CSVの22列または25列を受け付けます。案件・発生日・税区分・請求書のまとまりを確認して下見してください。</p>{state.error&&<Notice error={state.error}/>}
 <label>取込ファイル<input aria-label="取込ファイル" type="file" accept=".xlsx,.csv" onChange={e=>{setFile(e.target.files[0]??null);setPreview(null);setHold(null);}}/></label><div className="es-fields">{field('project_id','取込先の案件','text',opts(options.projects))}{field('incurred_on','取込の発生日','date')}{field('tax_category_version_id','取込の税区分','text',opts(latest(options.settings?.taxes,'tax_category_id').filter(r=>r.active)))}{field('withholding_category_version_id','取込の源泉区分','text',opts(latest(options.settings?.withholding,'withholding_category_id').filter(r=>r.active)))}{field('closing_on','不足時の締め日','date')}{field('due_on','不足時の出金予定日','date')}{field('override_note','取込の日付変更理由')}</div><label><input type="checkbox" aria-label="作品なしの共通経費として確認" checked={supplement.common_expense} onChange={e=>set({...supplement,common_expense:e.target.checked})}/>作品なしの共通経費として確認</label><label><input type="checkbox" aria-label="各行を別の領収書として確認" checked={supplement.each_row_invoice} onChange={e=>set({...supplement,each_row_invoice:e.target.checked})}/>各行を別の領収書として確認</label>
 <details><summary>請求書の行範囲を指定</summary><div className="es-fields">{[['from','開始行'],['to','終了行'],['key','まとまりのコード'],['invoice_number','取込の請求書番号']].map(([key,label])=><Field key={key} label={label} type={['from','to'].includes(key)?'number':'text'} value={group[key]} onChange={v=>setGroup({...group,[key]:v})}/>)}</div><Button onClick={()=>setGroups([...groups,{...group,from:num(group.from),to:num(group.to)}])}>行範囲を追加</Button><Button onClick={()=>setGroups([])}>行範囲を解除</Button>{groups.map((g,n)=><p key={n}>{g.from}〜{g.to}行：{g.invoice_number||g.key}</p>)}</details>
 <Field label="取込・解消・取消の理由" value={reason} onChange={setReason}/>{hold&&<div className="es-detail"><h4>保留行 {hold.row_no} の解消</h4><details><summary>受領値を確認して訂正</summary><p>原行は残し、この訂正値を次の下見の版へ保存します。</p><Button onClick={()=>setCorrected([...hold.values])}>受領値の訂正を始める</Button>{corrected&&<div className="es-fields">{corrected.map((value,n)=><Field key={n} label={'訂正：'+([...LEGACY_EXPENSE_COLUMNS,'締め日','出金予定日','出金日'][n])} value={value} onChange={v=>setCorrected(corrected.map((x,k)=>k===n?(v===''?null:v):x))}/>)}</div>}</details><div className="es-fields">{[['partner_id','解消する支払先',opts(options.partners)],['actual_ex_tax','確認した税抜額'],['tax_amount','確認した税額'],['source_withholding','確認した源泉（控除は負数）'],['payable_yen','確認した差引支払額'],['tax_difference_note','税額差の確認根拠']].map(([key,label,values])=><Field key={key} label={label} options={values} type={values||key==='tax_difference_note'?'text':'number'} value={override[key]} onChange={v=>setOverride({...override,[key]:v})}/>)}</div></div>}
 <Button disabled={action.busy} onClick={async()=>{const r=await action.run(async()=>{if(hold||preview)return post(request,`/expense-imports/${hold?.batch_id??preview.id}/preview`,{expectedVersion:preview?.version??hold.version,reason,supplement:supplementBody()});if(!file)throw Error('ファイルを選んでください');return post(request,'/expense-imports/preview',{expectedVersion:0,reason,file_name:file.name,original_base64:await fileBase64(file),supplement:supplementBody()});});if(r)setPreview(r);}}>取込の下見</Button>
 {preview&&<><p role="status">登録可 {preview.ready}件／保留 {preview.held}件／除外 {preview.excluded}件／税抜の既知額 {preview.known_ex_tax}円／金額未確認 {preview.unknown}件</p><DataGrid ariaLabel="取込の下見" rows={preview.rows} columns={[{key:'row_no',label:'行'},{key:'status',label:'確認結果'},{key:'issues',label:'確認する内容',value:r=>r.issues.map(x=>x.reason).join('／')}]} rowKey="row_no"/>{action.notice}<Button disabled={action.busy} onClick={async()=>{const r=await action.run(()=>post(request,hold?`/expense-imports/rows/${hold.id}/resolve`:`/expense-imports/${preview.id}/commit`,{expectedVersion:preview.version,hash:preview.hash,reason}));if(r){setPreview(null);setHold(null);}}}>{hold?'保留を解消して登録':'この下見で登録'}</Button></>}{!preview&&action.notice}
 <h4>保留の一覧</h4><DataGrid ariaLabel="保留の一覧" rows={state.holds??[]} columns={[{key:'batch_id',label:'取込の束'},{key:'row_no',label:'行'},{key:'status',label:'状態'},{key:'issues',label:'保留理由',value:r=>r.issues?.map(x=>x.reason).join('／')}]} rowKey="id" onRowClick={r=>{setHold(r);setPreview(null);set(Object.fromEntries(Object.entries(r.supplement).filter(([key])=>['project_id','incurred_on','tax_category_version_id','withholding_category_version_id','common_expense','each_row_invoice','closing_on','due_on','override_note'].includes(key))));setGroups(r.supplement.groups??[]);setOverride({});setCorrected(r.supplement.corrected_values??null);}}/>
 <h4>手入力の保留</h4>{state.pending?.map(p=><Button key={p.id} onClick={()=>setManual(p)}>{p.payload.description??p.code}</Button>)}{manual&&<ExpenseEntry key={manual.id} request={request} options={options} pending={manual} onSaved={()=>{setManual(null);setRevision(n=>n+1);}}/>}<h4>取込の束の履歴</h4><Field label="束の取消日" type="date" value={cancelOn} onChange={setCancelOn}/>{state.batches?.map(b=><div key={b.id}><p>{b.file_name}／版{b.version}／{b.events.some(e=>e.kind==='cancelled')?'取消済み':b.events.some(e=>e.kind==='committed')?'登録済み':'下見中'}</p><Button onClick={()=>action.run(async()=>{const r=await request('/expense-imports/'+b.id),v=r.versions.at(-1),p=JSON.parse(v.payload_json);setPreview({id:b.id,version:v.version_no,hash:v.hash,...p});setHold(null);set(p.supplement??{});setGroups(p.supplement?.groups??[]);})}>この束の下見を開く</Button><Button disabled={!b.events.some(e=>e.kind==='committed')||b.events.some(e=>e.kind==='cancelled')} onClick={()=>action.run(()=>post(request,`/expense-imports/${b.id}/cancel`,{expectedVersion:b.version,voided_on:cancelOn,reason}))}>この束を取り消す</Button></div>)}
 </section>;
}
