import React,{useEffect,useState} from 'react';
import {Notice} from '../ui/Notice.jsx';
export const today=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);
export const num=v=>v===''||v==null?null:Number(v);
export const post=(request,path,body)=>request(path,{method:'POST',body:JSON.stringify(body)});
export const latest=(rows=[],key)=>rows.filter(r=>!rows.some(x=>x[key]===r[key]&&x.version_no>r.version_no));
export const opts=(rows,label='name')=>(rows??[]).map(r=>({value:r.id,label:r[label]??r.name??r.title??r.code??String(r.id)}));
export function Field({label,value,onChange,options,type='text',required=false,readOnly=false}){return <label className="es-field"><span>{label}</span>{options?<select aria-label={label} value={value??''} onChange={e=>onChange(e.target.value)} required={required} disabled={readOnly}><option value="">選んでください</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input aria-label={label} type={type} value={value??''} onChange={e=>onChange(e.target.value)} required={required} readOnly={readOnly}/>}</label>;}
export function Button({children,...props}){return <button type="button" aria-label={typeof children==='string'?children:undefined} {...props}>{children}</button>;}
export function useExpenseOptions(request){const [state,set]=useState({});useEffect(()=>{let live=true;Promise.all([request('/expense-sheet/options'),request('/expense-accounting/settings'),request('/expense-cards')]).then(([o,s,c])=>live&&set({...o,settings:s.settings,cards:c.rows})).catch(error=>live&&set({error}));return()=>{live=false;};},[request]);return state;}
export function useAction(onSaved){const [notice,setNotice]=useState(null),[busy,setBusy]=useState(false);async function run(fn){setBusy(true);setNotice(null);try{const result=await fn();setNotice({message:'登録しました',tone:'ok'});onSaved?.();return result;}catch(error){setNotice({error});return null;}finally{setBusy(false);}}return {run,busy,notice:notice&&<Notice {...notice}/>};}
export function InvoiceFields({draft,set,request,options,lockedPartner=false}){const [origin,setOrigin]=useState(null),[error,setError]=useState(null);const field=(key,label,type='text',values)=> <Field label={label} value={draft[key]} onChange={v=>set({...draft,[key]:v})} type={type} options={values} required={['partner_id','invoice_on','closing_on','due_on'].includes(key)}/>;
 async function preview(){try{setError(null);const r=await post(request,'/expense-invoices/date-preview',{partner_id:num(draft.partner_id),invoice_on:draft.invoice_on});set({...draft,closing_on:r.dates.closing_on??'',due_on:r.dates.due_on??''});setOrigin(r.dates.payment_term_version_id?`支払条件の版 ${r.dates.payment_term_version_id} から算出。変更した日付には変更理由を残します。`:'支払条件がありません。締め日・出金予定日を入力してください。');}catch(e){setError(e);}}
 return <fieldset><legend>請求書・領収書</legend><div className="es-fields">{!lockedPartner&&field('partner_id','支払先','text',opts(options.partners))}{field('code','証憑コード')}{field('invoice_number','請求書番号')}{field('document_kind','証憑の種類','text',[{value:'invoice',label:'請求書'},{value:'receipt',label:'領収書'},{value:'credit_note',label:'減額証憑'},{value:'other',label:'その他'}])}{field('invoice_on','請求日','date')}{field('closing_on','締め日','date')}{field('due_on','出金予定日','date')}{field('override_note','日付の変更理由')}</div><Button onClick={preview}>支払条件から日付を確認</Button>{origin&&<p role="status">{origin}</p>}{error&&<Notice error={error}/>}</fieldset>;
}
export function AccountingFields({draft,set,options}){const s=options.settings??{};return <div className="es-fields"><Field label="費用区分" required options={opts(latest(s.categories,'category_id').filter(r=>r.active))} value={draft.category_version_id} onChange={v=>set({...draft,category_version_id:v})}/><Field label="税区分" required options={opts(latest(s.taxes,'tax_category_id').filter(r=>r.active))} value={draft.tax_category_version_id} onChange={v=>set({...draft,tax_category_version_id:v})}/><Field label="源泉区分" required options={opts(latest(s.withholding,'withholding_category_id').filter(r=>r.active))} value={draft.withholding_category_version_id} onChange={v=>set({...draft,withholding_category_version_id:v})}/><Field label="源泉の確認" options={[{value:'unverified',label:'未確認'},{value:'confirmed',label:'確認済み'}]} value={draft.withholding_state} onChange={v=>set({...draft,withholding_state:v})}/><Field label="源泉控除額（円）" type="number" value={draft.withholding_yen} onChange={v=>set({...draft,withholding_yen:v})}/></div>;}
export function accountingPayload(d){return {...d,expectedVersion:0,category_version_id:num(d.category_version_id),tax_category_version_id:num(d.tax_category_version_id),withholding_category_version_id:num(d.withholding_category_version_id),withholding_yen:num(d.withholding_yen)};}
export function ExpenseEntry({request,options,onSaved,work,repair,existingInvoice,pending}){const [draft,set]=useState({...pending?.payload,project_id:repair?.project_id??pending?.project_id??work?.project_id??'',work_id:repair?.work_id??pending?.payload.work_id??work?.id??'',incurred_on:repair?.incurred_on??pending?.payload.incurred_on??'',accounting_month:repair?.accounting_month??pending?.payload.accounting_month??'',description:repair?.description??pending?.payload.description??'',budget_yen:repair?.budget_yen??pending?.payload.budget_yen??'',actual_ex_tax:repair?.actual_ex_tax??pending?.payload.actual_ex_tax??'',tax_amount:repair?.tax_amount??pending?.payload.tax_amount??'',reason:'',recorded_on:pending?.payload.recorded_on??''}),[invoice,setInvoice]=useState({partner_id:repair?.partner_id??pending?.payload.partner_id??existingInvoice?.partner_id??'',code:'',document_kind:existingInvoice?.current.document_kind??'invoice',invoice_on:'',closing_on:'',due_on:'',...pending?.payload.invoice}),[accounting,setAccounting]=useState({withholding_state:'unverified',withholding_yen:'',...pending?.payload.accounting}),[credit,setCredit]=useState({}),action=useAction(onSaved);
 const field=(key,label,type='text',values)=><Field label={label} type={type} options={values} value={draft[key]} onChange={v=>set({...draft,[key]:v})} required={!['budget_yen','work_id','recorded_on'].includes(key)}/>;
 return <form aria-label={repair?'経費の整備':'経費の登録'} className="card stack" onSubmit={async e=>{e.preventDefault();const cat=options.settings?.categories.find(c=>c.id===num(accounting.category_version_id)),body={...draft,project_id:num(draft.project_id),work_id:num(draft.work_id),partner_id:num(invoice.partner_id),budget_yen:num(draft.budget_yen),actual_ex_tax:num(draft.actual_ex_tax),tax_amount:num(draft.tax_amount),actual_inc_tax:num(draft.actual_ex_tax)==null||num(draft.tax_amount)==null?null:num(draft.actual_ex_tax)+num(draft.tax_amount),category:cat?.name,invoice:{...invoice,partner_id:undefined,closing_on:invoice.closing_on||undefined,due_on:invoice.due_on||undefined,expectedVersion:0},accounting:accountingPayload(accounting),details:{recorded_on:draft.recorded_on||null},...(repair?{expectedExpenseVersion:repair.version}:{}),...(existingInvoice?{invoice_id:existingInvoice.id,expectedVersion:existingInvoice.current.version_no}:{}),...(invoice.document_kind==='credit_note'?{credit:{original_expense_id:num(credit.original_expense_id),original_invoice_id:num(credit.original_invoice_id)}}:{})};await action.run(()=>post(request,repair?`/expenses/${repair.id}/repair`:pending?`/expense-pending/${pending.id}/resolve`:'/expenses',{...body,...(pending?{expectedVersion:0}:{})}));}}>
 <h3>{repair?'経費の整備':'経費の登録'}</h3>{!existingInvoice&&<InvoiceFields draft={invoice} set={setInvoice} request={request} options={options}/>}
 <div className="es-fields">{field('project_id','案件','text',opts(options.projects))}{field('work_id','作品','text',opts((options.works??[]).filter(w=>w.project_id===num(draft.project_id)),'title'))}{field('incurred_on','発生日','date')}{field('accounting_month','計上月','month')}{field('recorded_on','計上日','date')}{field('description','内容')}{field('budget_yen','予算（円）','number')}{field('actual_ex_tax','実績税抜（円）','number')}{field('tax_amount','税額（円）','number')}<Field label="実績税込（自動）" value={num(draft.actual_ex_tax)==null||num(draft.tax_amount)==null?'':num(draft.actual_ex_tax)+num(draft.tax_amount)} readOnly/>{field('reason','登録理由')}</div><AccountingFields draft={accounting} set={setAccounting} options={options}/>
 {invoice.document_kind==='credit_note'&&<div className="es-fields"><Field label="元の経費ID" type="number" required value={credit.original_expense_id} onChange={v=>setCredit({...credit,original_expense_id:v})}/><Field label="元の請求書ID" type="number" required value={credit.original_invoice_id} onChange={v=>setCredit({...credit,original_invoice_id:v})}/></div>}{action.notice}<Button type="submit" disabled={action.busy}>登録</Button>{!repair&&!pending&&<Button disabled={action.busy} onClick={()=>action.run(()=>post(request,'/expense-pending',{project_id:num(draft.project_id),code:'PENDING-'+crypto.randomUUID(),reason:draft.reason,payload:{...draft,partner_id:num(invoice.partner_id),actual_ex_tax:num(draft.actual_ex_tax),tax_amount:num(draft.tax_amount),invoice,accounting:accountingPayload(accounting),amount_state:'unverified'}}))}>未確認のまま保留に保存</Button>}</form>;
}
