import React,{useState} from 'react';
import {Field,Button,post,num,opts,latest,useAction} from './ExpenseFields.jsx';
import {DataGrid} from '../ui/DataGrid.jsx';

function ExpenseAdoption({request,onSaved}){
 const [preview,setPreview]=useState(null),[reason,setReason]=useState(''),action=useAction();
 return <section aria-label="今の費目の対応を下見して採用"><h4>今の費目の対応を下見して採用</h4><p>既存の費目を旧規則で下見し、完全一致の対応として固定します。既存の対応や明細の会計版は上書きしません。</p>
 <Button onClick={()=>action.run(async()=>{setPreview(await request('/expense-accounting/adoption-preview'));})}>今の費目の対応を下見</Button>
 {preview&&<><DataGrid ariaLabel="費目の対応の下見" columns={[{key:'alias',label:'今の費目'},{key:'name',label:'対応する科目'},{key:'timing',label:'費用にする時期',render:r=>r.timing==='release_month_once'?'公開月に一括':'発生月'},{key:'state',label:'採用状況',render:r=>r.conflict??(r.adopted?'採用済み':'未採用')}]} rows={preview.rows} rowKey="alias" showTotals={false}/><Field label="対応を採用する理由" value={reason} onChange={setReason}/><Button disabled={action.busy||!reason.trim()||preview.conflicts.length>0} onClick={()=>action.run(async()=>{const r=await post(request,'/expense-accounting/adopt',{token:preview.token,reason});setPreview(null);onSaved?.();return r;})}>この対応を採用</Button></>}{action.notice}</section>;
}
const choices=(items)=>items.map(([value,label])=>({value,label}));
const RULES=choices([['month_end','月末'],['day','指定日']]);
const terms=[['effective_from','適用開始日','date'],['closing_rule','締め方',RULES],['closing_day','締めの指定日','number'],['payment_month_offset','支払月（何か月後）','number'],['payment_rule','支払日',RULES],['payment_day','支払の指定日','number']];
export const SETTING_LABELS={'account-classes':'勘定科目の分類',categories:'費用区分',aliases:'費用区分の別名',taxes:'税区分',withholding:'源泉区分','payment-terms':'取引先の支払条件',cards:'カード'};
export function settingsFields(kind,options){const classes=opts((options.settings?.['account-classes']??[]).filter(r=>r.active).map(c=>({...c,name:`${options.gl_accounts?.find(a=>a.id===c.account_id)?.name??c.account_id}（版${c.version_no}）`}))),cash=classes.filter(c=>options.settings['account-classes'].find(r=>r.id===c.value)?.settlement_role==='cash');
 const schema={
  'account-classes':[['account_id','勘定科目',opts(options.gl_accounts)],['normal_side','通常残高',choices([['debit','借方'],['credit','貸方']])],['balance_class','貸借の分類',choices([['none','損益'],['current','流動'],['noncurrent','固定']])],['settlement_role','決済の役割',choices([['cash','現預金'],['payable','未払金'],['card_payable','カード未払'],['receivable','売掛金'],['refund_receivable','返金未収'],['prepaid','前払金'],['input_tax','仮払消費税'],['output_tax','仮受消費税'],['withholding','源泉預り'],['wip','制作中の作品']])]],
  categories:[['code','費用区分コード'],['name','費用区分名'],['account_class_version_id','勘定科目の版',classes],['recognition_timing','費用にする時期',choices([['incurred_month','発生月'],['release_month_once','公開月に一括']])]],
  aliases:[['alias_text','別名'],['category_version_id','対応する費用区分',opts(latest(options.settings?.categories,'category_id'))]],
  taxes:[['code','税区分コード'],['name','税区分名'],['tax_kind','課税の分類',choices([['taxable','課税'],['exempt','非課税'],['non_taxable','不課税'],['out_of_scope','対象外']])],['rate_bps','税率',choices([[1000,'10%'],[800,'8%']])],['rounding','端数処理',choices([['floor','切り捨て'],['nearest','四捨五入'],['ceil','切り上げ']])]],
  withholding:[['code','源泉区分コード'],['name','源泉区分名'],['treatment','取扱い',choices([['not_applicable','対象外'],['manual_confirmed','控除額を明示して確認']])],['basis','確認の根拠']],
  'payment-terms':[['partner_id','支払先',opts(options.partners)],...terms,['payment_method','支払方法',choices([['transfer','振込'],['cash','現金'],['card','カード'],['offset','相殺'],['other','その他']])]],
  cards:[['code','カードコード'],['name','カード名'],...terms,['cash_account_class_version_id','引落の現預金科目',cash]],
 };return schema[kind];}
export function ExpenseSettings({request,options,admin,onSaved}){const [kind,setKind]=useState('categories'),[draft,set]=useState({active:1,expectedVersion:0,reason:''}),action=useAction(onSaved),fields=settingsFields(kind,options),rows=kind==='cards'?options.cards??[]:options.settings?.[kind]??[];
 return <section className="card stack"><h3>会計の設定</h3>{admin&&<ExpenseAdoption request={request} onSaved={onSaved}/>}<Field label="設定する項目" value={kind} onChange={v=>{setKind(v);set({active:1,expectedVersion:0,reason:''});}} options={choices(Object.entries(SETTING_LABELS))}/><p>過去の経費は参照した版を保持します。次の版の追加には理由が必要です。</p><div className="es-tabs">{rows.map(r=><Button key={r.id} onClick={()=>set({...r,expectedVersion:r.version_no,reason:''})}>{`${r.name??r.code??r.alias_text??r.partner_id??r.account_id}／版${r.version_no}`}</Button>)}</div>
 {admin?<form aria-label="会計の設定の版追加" onSubmit={async e=>{e.preventDefault();const body={expectedVersion:Number(draft.expectedVersion),reason:draft.reason,active:Number(draft.active)};for(const [key,,type] of fields){const v=draft[key];body[key]=key.endsWith('_id')||type==='number'||key==='rate_bps'?num(v):v||null;}if(body.tax_kind&&body.tax_kind!=='taxable')body.rate_bps=null;for(const prefix of ['closing','payment'])if(body[prefix+'_rule']==='month_end')body[prefix+'_day']=null;await action.run(()=>post(request,kind==='cards'?'/expense-cards':'/expense-accounting/'+kind,body));}}><div className="es-fields">{fields.map(([key,label,type])=><Field key={key} label={label} value={draft[key]} type={typeof type==='string'?type:'text'} options={Array.isArray(type)?type:undefined} onChange={v=>set({...draft,[key]:v})}/>)}<Field label="登録状態" value={draft.active} onChange={v=>set({...draft,active:v})} options={choices([[1,'使用する'],[0,'廃止する']])}/><Field label="変更理由" required value={draft.reason} onChange={v=>set({...draft,reason:v})}/></div><p>現在の版 {draft.expectedVersion} → 新しい版 {Number(draft.expectedVersion)+1}</p>{action.notice}<Button type="submit" disabled={action.busy}>版を追加</Button></form>:<p>設定を変更できるのは管理者です。</p>}</section>;
}
