import React,{useEffect,useState} from 'react';
import {DataGrid} from '../ui/DataGrid.jsx';
import {Notice} from '../ui/Notice.jsx';
import {InvoiceFields,ExpenseEntry,Field,Button,post,num,useAction} from './ExpenseFields.jsx';
export async function fileBase64(file){const bytes=new Uint8Array(await file.arrayBuffer());let text='';for(let n=0;n<bytes.length;n+=8192)text+=String.fromCharCode(...bytes.slice(n,n+8192));return btoa(text);}
export function saveBlob(bytes,type,name){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function InvoiceFiles({request,invoiceId,version,files=[],onSaved}){const [file,setFile]=useState(null),[fileId,setFileId]=useState(''),[reason,setReason]=useState(''),action=useAction(onSaved);return <section className="stack"><h4>原本</h4>{files.map(f=><div key={f.id}><Button onClick={()=>action.run(async()=>{const r=await request('/expense-source-files/'+f.file_id);saveBlob(Uint8Array.from(atob(r.file.original_base64),c=>c.charCodeAt(0)),r.file.media_type,r.file.file_name);})}>{f.file_name}</Button><Button onClick={()=>action.run(()=>post(request,`/expense-file-links/${f.id}/unlink`,{expectedVersion:version,reason}))}>この紐づけを取り消す</Button></div>)}<label>原本ファイル<input aria-label="原本ファイル" type="file" onChange={e=>setFile(e.target.files[0]??null)}/></label><Field label="登録済みの原本ID" type="number" value={fileId} onChange={setFileId}/><Field label="原本の紐づけ理由" value={reason} onChange={setReason}/>{action.notice}<Button disabled={action.busy} onClick={()=>action.run(async()=>{let id=num(fileId);if(!id){if(!file)throw Error('原本を選んでください');const r=await post(request,'/expense-source-files',{file_name:file.name,media_type:file.type||'application/octet-stream',original_base64:await fileBase64(file),reason});id=r.id;setFileId(String(id));}return post(request,`/expense-invoices/${invoiceId}/files`,{file_id:id,expectedVersion:version,purpose:'supporting',reason});})}>原本を紐づける</Button></section>;}
export function ExpenseInvoices({request,options,onSaved}){const [state,setState]=useState({}),[revision,setRevision]=useState(0),[selected,setSelected]=useState(null),[draft,setDraft]=useState({code:'',partner_id:'',document_kind:'invoice',invoice_on:'',closing_on:'',due_on:'',reason:''}),[detail,setDetail]=useState(null),[line,setLine]=useState(false),action=useAction(()=>{setRevision(n=>n+1);onSaved?.();});
 useEffect(()=>{let live=true;request('/expense-invoices').then(r=>{if(!live)return;setState(r);const id=typeof window==='undefined'?null:new URLSearchParams(window.location.search).get('invoiceId');const row=r.rows?.find(x=>x.id===Number(id));if(row){setSelected(row);setDraft({...row.current,code:row.code,partner_id:row.partner_id,reason:''});}}).catch(error=>live&&setState({error}));return()=>{live=false;};},[request,revision]);
 useEffect(()=>{let live=true;if(selected)request('/expense-invoices/'+selected.id).then(r=>live&&setDetail(r)).catch(error=>live&&setState({error}));else setDetail(null);return()=>{live=false;};},[request,selected,revision]);
 return <section className="card stack"><h3>請求書</h3>{state.error&&<Notice error={state.error}/>}<DataGrid ariaLabel="請求書の一覧" columns={[{key:'code',label:'証憑コード'},{key:'partner_id',label:'支払先',render:r=>options.partners?.find(p=>p.id===r.partner_id)?.name},{key:'invoice_number',label:'請求書番号',value:r=>r.current.invoice_number},{key:'invoice_on',label:'請求日',value:r=>r.current.invoice_on},{key:'closing_on',label:'締め日',value:r=>r.current.closing_on},{key:'due_on',label:'出金予定日',value:r=>r.current.due_on}]} rows={state.rows??[]} rowKey="id" onRowClick={r=>{setSelected(r);setDraft({...r.current,code:r.code,partner_id:r.partner_id,reason:''});setLine(false);}}/>
 <Button onClick={()=>{setSelected(null);setDraft({code:'',partner_id:'',document_kind:'invoice',reason:''});setLine(false);}}>新しい請求書</Button><form aria-label="請求書の登録・訂正" onSubmit={async e=>{e.preventDefault();const r=await action.run(()=>post(request,selected?`/expense-invoices/${selected.id}/versions`:'/expense-invoices',{...draft,partner_id:num(draft.partner_id),closing_on:draft.closing_on||undefined,due_on:draft.due_on||undefined,expectedVersion:selected?.current.version_no??0}));if(r){setSelected(null);setDraft({code:'',partner_id:'',document_kind:'invoice',reason:''});}}}><InvoiceFields draft={draft} set={setDraft} options={options} request={request} lockedPartner={!!selected}/><Field label="請求書の登録・訂正理由" value={draft.reason} onChange={v=>setDraft({...draft,reason:v})}/>{action.notice}<Button type="submit" disabled={action.busy}>{selected?'請求書の訂正版を追加':'請求書を登録'}</Button></form>
 {detail&&<><h4>請求書の版と日付の由来</h4>{detail.versions.map(v=><p key={v.id}>版{v.version_no}：請求日 {v.invoice_on}／締め日 {v.closing_on}／予定日 {v.due_on}／{({term:'支払条件から算出',manual:'手入力',override:'請求書ごとに変更'})[v.closing_origin]}／{v.reason}</p>)}<h4>明細</h4>{detail.details.map(d=><p key={d.expense_id}>経費ID {d.expense_id}／税込 {d.actual_inc_tax}円</p>)}<Button onClick={()=>setLine(v=>!v)}>この請求書へ明細を追加</Button>{line&&<ExpenseEntry key={selected.id} request={request} options={options} existingInvoice={selected} onSaved={()=>{setLine(false);setRevision(n=>n+1);onSaved?.();}}/>}<InvoiceFiles request={request} invoiceId={selected.id} version={selected.current.version_no} files={detail.files??[]} onSaved={()=>setRevision(n=>n+1)}/></>}
 </section>;
}
