import {creditStatements,paymentExtras,expenseChangeGuard} from '../expense-accounting/settlement-service.mjs';
import {fail,str,integer,day,expected,choice,METHODS,invoiceValues,expenseValues,detailValues,calculateDates,paymentBalance,DATE_RULE_VERSION} from './expense-model.mjs';
import {accountingValues} from '../expense-accounting/accounting-model.mjs';
export const insert=(table,row)=>({sql:`INSERT INTO ${table}(${Object.keys(row).join(',')}) VALUES(${Object.keys(row).map(()=>'?').join(',')})`,params:Object.values(row)});
export const guard=(sql,params=[])=>({sql:`INSERT INTO transaction_guards(value) SELECT 0 WHERE ${sql}`,params});
export const newId=()=>Number.parseInt(crypto.randomUUID().replaceAll('-','').slice(0,12),16);
export function expenseService({db,permittedProjects}){
 const meta=(i,b)=>({org_id:i.org_id,created_by:i.user_id,reason:str(b.reason,1000,true)});
 const audit=(i,type,id,b)=>insert('audit_log',{org_id:i.org_id,user_id:i.user_id,action:'create',entity_type:type,entity_id:String(id),detail_json:JSON.stringify({reason:str(b.reason,1000,true),expectedVersion:b.expectedVersion??null,ruleVersion:DATE_RULE_VERSION})});
 async function batch(statements){if(statements.length>480)fail('1回の登録は480文以内にしてください',413);for(const s of statements){if(s.params.length>100)fail('束縛値の上限を超えています',413);for(const v of s.params)if(typeof v==='string'&&new TextEncoder().encode(v).length>=128*1024&&!s.sql.startsWith('INSERT INTO expense_source_files('))fail('値の大きさが上限を超えています',413);}return db.batch(statements);}
 async function finance(i,project=null){if(i.role==='production')fail('経費は財務担当の画面です',403);const ids=new Set((await permittedProjects(db,i,true)).map(x=>x.id));if((project!=null&&!ids.has(project))||(project==null&&i.role!=='admin'&&!ids.size))fail('案件の財務編集権限がありません',403);return ids;}
 async function ref(i,table,id,active=false){const row=await db.get(`SELECT * FROM ${table} WHERE org_id=? AND id=?`,[i.org_id,id]);if(!row)fail('組織内の参照先を選んでください');if(active&&row.active!==1)fail('有効な版を選んでください');return row;}
 async function invoice(i,id){const row=await ref(i,'expense_invoices',id),ids=await finance(i);const lines=await db.all('SELECT e.project_id FROM expense_details d JOIN expenses e ON e.org_id=d.org_id AND e.id=d.expense_id WHERE d.org_id=? AND d.invoice_id=?',[i.org_id,id]);if(lines.some(x=>!ids.has(x.project_id))||(!lines.length&&row.created_by!==i.user_id&&i.role!=='admin'))fail('請求書に含まれる全案件の財務権限が必要です',403);return row;}
 const latest=(i,table,parent,id)=>db.get(`SELECT * FROM ${table} WHERE org_id=? AND ${parent}=? ORDER BY version_no DESC LIMIT 1`,[i.org_id,id]);
 async function term(i,partnerId,on,versionId=null){day(on);await ref(i,'partners',partnerId);if(versionId!=null){const selected=await ref(i,'partner_payment_term_versions',integer(versionId,1),true);if(selected.partner_id!==partnerId||selected.effective_from>on)fail('請求日に適用できる同じ支払先の条件版を選んでください');return selected;}const row=await db.get('SELECT * FROM partner_payment_term_versions WHERE org_id=? AND partner_id=? AND effective_from<=? ORDER BY effective_from DESC,version_no DESC LIMIT 1',[i.org_id,partnerId,on]);return row?.active===1?row:null;}
 const versionGuard=(i,table,parent,id,base)=>guard(`?<>(SELECT COALESCE(MAX(version_no),0) FROM ${table} WHERE org_id=? AND ${parent}=?)`,[base,i.org_id,id]);
 async function invoiceStatements(i,b,existing=null){const base=expected(b);if(existing&&b.partner_id!=null&&b.partner_id!==existing.partner_id)fail('支払先を変える場合は別の請求書を作ってください',409);if(!existing&&base!==0)fail('初回の版は0を指定してください',409);const id=existing?.id??newId(),partner=existing?.partner_id??integer(b.partner_id,1);await ref(i,'partners',partner);const t=await term(i,partner,b.invoice_on,b.payment_term_version_id),v=invoiceValues(b,t);if(v.invoice_number){const duplicate=await db.get(`SELECT i.id FROM expense_invoices i JOIN expense_invoice_versions v ON v.org_id=i.org_id AND v.invoice_id=i.id WHERE i.org_id=? AND i.partner_id=? AND i.id<>? AND v.invoice_number=? AND v.active=1 AND v.version_no=(SELECT MAX(x.version_no) FROM expense_invoice_versions x WHERE x.org_id=i.org_id AND x.invoice_id=i.id)`,[i.org_id,partner,id,v.invoice_number]);if(duplicate)fail('同じ支払先・番号の請求書があります。証憑を確認してください',409);}
 const statements=[versionGuard(i,'expense_invoice_versions','invoice_id',id,base)];
 if(v.invoice_number)statements.push(guard('EXISTS(SELECT 1 FROM expense_invoices i JOIN expense_invoice_versions v ON v.org_id=i.org_id AND v.invoice_id=i.id WHERE i.org_id=? AND i.partner_id=? AND i.id<>? AND v.invoice_number=? AND v.active=1 AND v.version_no=(SELECT MAX(x.version_no) FROM expense_invoice_versions x WHERE x.org_id=i.org_id AND x.invoice_id=i.id))',[i.org_id,partner,id,v.invoice_number]));
 if(!existing)statements.push(insert('expense_invoices',{id,code:str(b.code,60,true),partner_id:partner,...meta(i,b)}));statements.push(insert('expense_invoice_versions',{id:newId(),invoice_id:id,version_no:base+1,...v,...meta(i,b)}),audit(i,'expense_invoice',id,b));return {id,statements,version:base+1};}
 async function accountingStatements(i,expenseId,b){const base=expected(b),values=accountingValues(b);await ref(i,'expense_categories',(await ref(i,'expense_category_versions',values.category_version_id,true)).category_id);await ref(i,'expense_tax_category_versions',values.tax_category_version_id,true);if(values.withholding_category_version_id)await ref(i,'expense_withholding_category_versions',values.withholding_category_version_id,true);return [versionGuard(i,'expense_accounting_versions','expense_id',expenseId,base),insert('expense_accounting_versions',{id:newId(),expense_id:expenseId,version_no:base+1,...values,...meta(i,b)}),audit(i,'expense_accounting',expenseId,b)];}
 async function expense(i,id){const row=await ref(i,'expenses',id);await finance(i,row.project_id);return row;}
 async function makeExpense(i,b,{legacy=null,replace=null,prepare=false,preparedId=null,preparedInvoice=null}={}){await finance(i,legacy?.project_id??b.project_id);if(!legacy&&!b.accounting)fail('費用区分と税区分を確認してください。未確認の入力は保留へ保存できます');const values=legacy?{...legacy,partner_id:legacy.partner_id??integer(b.partner_id,1)}:expenseValues(b),id=legacy?.id??preparedId??(await db.get('SELECT COALESCE(MAX(id),0)+1 AS id FROM expenses')).id;const statements=[];let invoiceId=b.invoice_id;
 if(invoiceId){const inv=preparedInvoice??await invoice(i,integer(invoiceId,1));if(inv.partner_id!==values.partner_id)fail('経費と請求書の支払先を一致させてください');const base=expected(b);if(!preparedInvoice)statements.push(versionGuard(i,'expense_invoice_versions','invoice_id',invoiceId,base));}
 else{const inv=await invoiceStatements(i,{...b.invoice,partner_id:values.partner_id,reason:b.invoice?.reason??b.reason});invoiceId=inv.id;statements.push(...inv.statements);}
 const d=detailValues(b.details);if(d.recorded_on&&d.recorded_on.slice(0,7)!==values.accounting_month)fail('計上日と計上月を一致させてください');if(d.product_id)await ref(i,'products',d.product_id);
 if(!legacy)statements.push(insert('expenses',{id,org_id:i.org_id,...values}));else{if(await db.get('SELECT 1 FROM expense_details WHERE org_id=? AND expense_id=?',[i.org_id,id]))fail('整備済みです。訂正は取消と新しい経費で行ってください',409);statements.push(guard('NOT EXISTS(SELECT 1 FROM expenses WHERE org_id=? AND id=? AND version=?)',[i.org_id,id,integer(b.expectedExpenseVersion,1)]));}
 statements.push(insert('expense_details',{expense_id:id,invoice_id:invoiceId,...d,...meta(i,b)}));statements.push(...await creditStatements(service,i,b,{...values,id},invoiceId));if(b.accounting)statements.push(...await accountingStatements(i,id,{...b.accounting,reason:b.accounting.reason??b.reason}));
 if(replace){statements.push(versionGuard(i,'expense_accounting_versions','expense_id',replace.id,expected({expectedVersion:b.expectedAccountingVersion})),insert('expense_line_voids',{expense_id:replace.id,voided_on:day(b.voided_on),replacement_expense_id:id,...meta(i,b)}),audit(i,'expense_void',replace.id,b));}
 statements.push(audit(i,legacy?'expense_repair':'expense',id,b),guard('NOT EXISTS(SELECT 1 FROM expenses e JOIN expense_details d ON d.org_id=e.org_id AND d.expense_id=e.id JOIN expense_invoices i ON i.org_id=d.org_id AND i.id=d.invoice_id AND (i.partner_id=e.partner_id OR e.partner_id IS NULL) JOIN expense_invoice_versions v ON v.org_id=i.org_id AND v.invoice_id=i.id WHERE e.org_id=? AND e.id=? AND v.active=1 AND v.version_no=(SELECT MAX(x.version_no) FROM expense_invoice_versions x WHERE x.org_id=i.org_id AND x.invoice_id=i.id))',[i.org_id,id]));statements.unshift(await expenseChangeGuard(service,i,{created:{...values,id,invoice_id:invoiceId,recorded_on:d.recorded_on,original_expense_id:b.credit?.original_expense_id??null,accounting:b.accounting},voids:replace?[{id:replace.id,on:b.voided_on}]:[]}));if(prepare)return {id,invoice_id:invoiceId,statements};await batch(statements);return {id,invoice_id:invoiceId};}
 async function payments(i,id){return db.all('SELECT p.*,a.accounting_version_id,a.withheld_yen,a.cash_account_class_version_id FROM expense_payments p LEFT JOIN expense_payment_accounting a ON a.org_id=p.org_id AND a.payment_id=p.id WHERE p.org_id=? AND p.expense_id=? ORDER BY p.paid_on,p.id',[i.org_id,id]);}
 async function recordPayment(i,b,reverseId=null,{prepare=false}={}){let origin=null;const id=newId();if(reverseId)origin=await ref(i,'expense_payments',reverseId);const e=await expense(i,origin?.expense_id??integer(b.expenseId,1)),a=await latest(i,'expense_accounting_versions','expense_id',e.id);const base=expected(b);if(!a||a.withholding_state!=='confirmed'||a.active!==1)fail('会計区分と源泉を確認してください',409);if(await db.get('SELECT 1 FROM expense_line_voids WHERE org_id=? AND expense_id=?',[i.org_id,e.id]))fail('取消済みの経費です',409);
 const previous=origin?await db.get('SELECT * FROM expense_payment_accounting WHERE org_id=? AND payment_id=?',[i.org_id,origin.id]):null;if(origin&&!previous)fail('元の出金に会計の確認がありません',409);
 const withheld=origin?-previous.withheld_yen:integer(b.withheldYen),cashClass=origin?previous.cash_account_class_version_id:b.cashAccountClassVersionId??null;
 if(cashClass)await ref(i,'gl_account_class_versions',cashClass,!origin);const paidOn=day(origin?b.reversedOn:b.paidOn),amount=origin?-origin.amount_yen:integer(b.amountYen,1),method=choice(origin?.method??b.method??'transfer',METHODS);
 if(origin&&paidOn<origin.paid_on)fail('取消日は出金日以後にしてください');
 if(!origin){const balance=paymentBalance(e,a,await payments(i,e.id));if(balance.cash_due_yen==null)fail('既存の出金の源泉区分を確認してください',409);if(amount+withheld>balance.debt_yen||amount>balance.cash_due_yen||withheld>balance.withholding_due_yen)fail(`出金額が経費の税込額（${e.actual_inc_tax.toLocaleString('ja-JP')}円）を超えます。源泉と登録済みの出金を確認してください`,409);}
 const extras=await paymentExtras(service,i,b,{id,expense_id:e.id,paid_on:paidOn,amount_yen:amount,withheld_yen:withheld,cash_account_class_version_id:cashClass,method,reverses_id:origin?.id??null});
 const statements=[extras.stamp,versionGuard(i,'expense_accounting_versions','expense_id',e.id,base),insert('expense_payments',{id,org_id:i.org_id,expense_id:e.id,paid_on:paidOn,amount_yen:amount,method,note:str(b.note??b.reason,500),reverses_id:origin?.id??null,created_by:i.user_id}),insert('expense_payment_accounting',{payment_id:id,accounting_version_id:previous?.accounting_version_id??a.id,withheld_yen:withheld,cash_account_class_version_id:cashClass,...meta(i,b)}),...extras.statements,audit(i,'expense_payment',id,b)];if(prepare)return {id,statements};await batch(statements);return {id,balance:paymentBalance(e,a,await payments(i,e.id))};}
 const service={db,meta,audit,batch,finance,ref,invoice,latest,term,versionGuard,invoiceStatements,accountingStatements,expense,makeExpense,payments,recordPayment};return service;
}
