// Worker / local 共通。日付は時差に依存せず、金額の加減は整数で扱う。
export const DATE_RULE_VERSION='req6-dates-v1';
export function fail(message,status=400){throw Object.assign(new Error(message),{status});}
export function str(v,max=1000,required=false){if(v==null||v===''){if(required)fail('必須の項目が空です');return null;}if(typeof v!=='string'||!v.trim()||v.trim().length>max)fail(`文字は1〜${max}文字で入力してください`);return v.trim();}
export function integer(v,min=0,max=Number.MAX_SAFE_INTEGER){if(!Number.isSafeInteger(v)||v<min||v>max)fail('整数の範囲を確認してください');return v;}
export function day(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)fail('実在する日付を YYYY-MM-DD で入力してください');return v;}
export function choice(v,list){if(!list.includes(v))fail('区分を選んでください');return v;}
export const METHODS=['transfer','cash','card','offset','other'];
export function expected(b){if(b.expectedVersion==null)fail('expectedVersion が必要です',428);return integer(b.expectedVersion);}
export function addYen(...values){const n=values.reduce((a,b)=>a+BigInt(integer(b,-Number.MAX_SAFE_INTEGER)),0n);if(n>BigInt(Number.MAX_SAFE_INTEGER)||n< -BigInt(Number.MAX_SAFE_INTEGER))fail('金額が上限を超えています');return Number(n);}
function monthDay(year,month,rule,d){const date=new Date(0);date.setUTCFullYear(year,month,0);const last=date.getUTCDate();date.setUTCDate(rule==='month_end'?last:Math.min(d,last));return day(date.toISOString().slice(0,10));}
export function calculateDates(invoiceOn,term){day(invoiceOn);if(!term)return {invoice_on:invoiceOn,closing_on:null,due_on:null,payment_term_version_id:null,rule_version:DATE_RULE_VERSION};let [y,m]=invoiceOn.split('-').map(Number);let closing=monthDay(y,m,term.closing_rule,term.closing_day);if(closing<invoiceOn)closing=monthDay(y,++m,term.closing_rule,term.closing_day);const [cy,cm]=closing.split('-').map(Number);return {invoice_on:invoiceOn,closing_on:closing,due_on:monthDay(cy,cm+term.payment_month_offset,term.payment_rule,term.payment_day),payment_term_version_id:term.id,payment_method:term.payment_method,rule_version:DATE_RULE_VERSION};}
export function invoiceValues(b,term){const dates=calculateDates(day(b.invoice_on),term);const closing=day(b.closing_on??dates.closing_on),due=day(b.due_on??dates.due_on);if(closing<b.invoice_on||due<closing)fail('請求日、締め日、出金予定日の順序を確認してください');const origin=(key)=>!term?'manual':b[key]!=null&&b[key]!==dates[key]?'override':'term';const closing_origin=origin('closing_on'),due_origin=origin('due_on');return {invoice_number:str(b.invoice_number,120),document_kind:choice(b.document_kind??'invoice',['invoice','receipt','credit_note','other']),invoice_on:b.invoice_on,closing_on:closing,due_on:due,payment_term_version_id:term?.id??null,closing_origin,due_origin,override_note:str(b.override_note,1000,closing_origin==='override'||due_origin==='override'),payment_method:choice(b.payment_method??term?.payment_method??'transfer',METHODS),active:integer(b.active??1,0,1)};}
export function expenseValues(b){const out={project_id:integer(b.project_id,1),work_id:b.work_id==null?null:integer(b.work_id,1),partner_id:integer(b.partner_id,1),incurred_on:day(b.incurred_on),accounting_month:b.accounting_month,category:str(b.category,100,true),description:str(b.description,1000,true),budget_yen:b.budget_yen==null?null:integer(b.budget_yen),actual_ex_tax:integer(b.actual_ex_tax,-Number.MAX_SAFE_INTEGER),tax_amount:integer(b.tax_amount,-Number.MAX_SAFE_INTEGER),actual_inc_tax:integer(b.actual_inc_tax,-Number.MAX_SAFE_INTEGER)};if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(out.accounting_month)||addYen(out.actual_ex_tax,out.tax_amount)!==out.actual_inc_tax)fail('計上月または税抜・税額・税込の内訳を確認してください');return out;}
export function detailValues(b={}){const out={recorded_on:b.recorded_on==null?null:day(b.recorded_on),distribution_type_code:str(b.distribution_type_code,60),product_id:b.product_id==null?null:integer(b.product_id,1)};for(const key of ['source_product_number','source_product_name','source_client_name','supplier_text','specification','memo'])out[key]=str(b[key],['specification','memo'].includes(key)?1000:240);for(const key of ['quantity_x10000','unit_price_x10000'])out[key]=b[key]==null?null:integer(b[key]);return out;}
export function paymentBalance(expense,accounting,payments,asOf='9999-12-31'){const rows=payments.filter(p=>p.paid_on<=asOf),cash=addYen(...rows.map(p=>p.amount_yen)),withheld=addYen(...rows.map(p=>p.withheld_yen??0));const known=accounting?.withholding_state==='confirmed'&&rows.every(p=>p.withheld_yen!=null);const debt=addYen(expense.actual_inc_tax,-cash,-withheld);return {cash_paid_yen:cash,withheld_yen:known?withheld:null,debt_yen:rows.every(p=>p.withheld_yen!=null)?debt:null,cash_due_yen:known?addYen(expense.actual_inc_tax,-accounting.withholding_yen,-cash):null,withholding_due_yen:known?addYen(accounting.withholding_yen,-withheld):null,last_paid_on:rows.filter(p=>!p.reverses_id&&!rows.some(r=>r.reverses_id===p.id)).map(p=>p.paid_on).sort().at(-1)??null};}
// 仕訳は保存しない。科目は版で指定されたものだけを使い、名称から推測しない。
export function journalForExpense({expense,accounting,category,accountClass,payments=[],roles={},releaseMonth=null,voided=false}){if(voided)return [];if(!accounting||accounting.active===0||!category||!accountClass)return [{expense_id:expense.id,status:'未整備',lines:[]}];const rows=[],line=(account,side,amount)=>({account_class_version_id:account??null,side,amount_yen:amount,status:account?'確認済み':'未整備'}),post=(kind,on,lines,paymentId=null)=>rows.push({kind,on,expense_id:expense.id,payment_id:paymentId,tax_category_version_id:accounting.tax_category_version_id,lines});const deferred=category.recognition_timing==='release_month_once';post('accrual',expense.incurred_on,[line(deferred?roles.wip:accountClass.id,'debit',expense.actual_ex_tax),line(roles.input_tax,'debit',expense.tax_amount),line(roles.payable,'credit',expense.actual_inc_tax)]);if(deferred&&releaseMonth)post('recognition',releaseMonth+'-01',[line(accountClass.id,'debit',expense.actual_ex_tax),line(roles.wip,'credit',expense.actual_ex_tax)]);for(const p of payments){if(p.withheld_yen==null){rows.push({kind:'payment',on:p.paid_on,expense_id:expense.id,payment_id:p.id,status:'未整備',lines:[]});continue;}post(p.reverses_id?'payment_reversal':'payment',p.paid_on,[line(roles.payable,'debit',addYen(p.amount_yen,p.withheld_yen??0)),line(p.cash_account_class_version_id,'credit',p.amount_yen),line(roles.withholding,'credit',p.withheld_yen??0)
 ],p.id);}return rows;}
