import {ExpenseJournal} from './ExpenseJournal.jsx';
import React,{useEffect,useState} from 'react';
import {useShell} from '../shell/context.mjs';
import {DataGrid} from '../ui/DataGrid.jsx';
import {Notice} from '../ui/Notice.jsx';
import {SET_LABELS} from './sheet-model.mjs';
import {Field,Button,opts,today,useExpenseOptions,ExpenseEntry} from './ExpenseFields.jsx';
import {ExpenseInvoices,InvoiceFiles} from './ExpenseInvoices.jsx';
import {ExpenseImports} from './ExpenseImports.jsx';
import {ExpensePayout,PaymentForm,PaymentHistory} from './ExpensePayout.jsx';
import {ExpenseSettings} from './ExpenseSettings.jsx';
import './expense-sheet.css';
import '../sales-sheet/sales-sheet.css';
export const EXPENSE_TABS=['経費集計シート','請求書','取込と保留','出金予定','会計の設定','仕訳の見え方'];
export function ExpenseSheet({request:provided,work,embedded=false,onChanged}){const shell=useShell(),request=provided??shell.request;const [access,setAccess]=useState({}),[tab,setTab]=useState(()=>typeof window!=='undefined'&&new URLSearchParams(window.location.search).has('invoiceId')?'請求書':'経費集計シート'),[revision,setRevision]=useState(0),[entry,setEntry]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let live=true;request('/expense-sheet/access').then(r=>live&&setAccess(r)).catch(error=>live&&setAccess({error}));return()=>{live=false;};},[request]);
 if(access.error)return <Notice error={access.error}/>;if(!access.ok)return <p>経費の権限を確認しています。</p>;
 const saved=()=>{setMessage('登録しました');setRevision(n=>n+1);onChanged?.();};
 return <div className="stack">{message&&<Notice tone="ok" message={message}/>}<header className="card rp-head"><h2>経費集計シート</h2><p>請求書の日付・経費・出金をつないで確認します。</p><div className="es-tabs" role="group" aria-label="経費の業務">{EXPENSE_TABS.map(t=><Button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setEntry(false);}}>{t}</Button>)}</div></header><ExpenseContent key={revision} {...{request,work,embedded,tab,access,saved,entry,setEntry}}/></div>;
}
function ExpenseContent({request,work,tab,access,saved,entry,setEntry}){const options=useExpenseOptions(request);if(options.error)return <Notice error={options.error}/>;if(!options.settings)return <p>経費の設定を読み込んでいます。</p>;
 return <>{tab==='仕訳の見え方'&&<ExpenseJournal request={request} options={options} work={work}/>} {tab==='経費集計シート'&&<><Button onClick={()=>setEntry(!entry)}>経費を登録</Button>{entry&&<ExpenseEntry request={request} options={options} work={work} onSaved={()=>{setEntry(false);saved();}}/>}<ExpenseTable request={request} options={options} work={work} onSaved={saved}/></>}{tab==='請求書'&&<ExpenseInvoices request={request} options={options} onSaved={saved}/>} {tab==='取込と保留'&&<ExpenseImports request={request} options={options} onSaved={saved}/>} {tab==='出金予定'&&<ExpensePayout request={request} options={options} onSaved={saved}/>} {tab==='会計の設定'&&<ExpenseSettings request={request} options={options} admin={access.admin} onSaved={saved}/>}</>;
}
function ExpenseTable({request,options,work,onSaved}){const [filters,setFilters]=useState({workId:work?.id??'',projectId:'',partnerId:'',month:'',closingOn:'',dueOn:'',status:'',asOf:today()}),[setKey,setSetKey]=useState('basic'),[page,setPage]=useState(1),[state,setState]=useState({}),[detail,setDetail]=useState(null),[selected,setSelected]=useState(()=>typeof window==='undefined'?null:new URLSearchParams(window.location.search).get('expenseId')),[revision,setRevision]=useState(0),[repair,setRepair]=useState(false);
 const query=new URLSearchParams(Object.fromEntries(Object.entries({...filters,set:setKey,page,pageSize:100}).filter(([,v])=>v!==''))).toString();
 useEffect(()=>{let live=true;request('/expense-sheet?'+query).then(r=>live&&setState(r)).catch(error=>live&&setState({error}));return()=>{live=false;};},[request,query,revision]);
 useEffect(()=>{let live=true;if(selected)request(`/expense-sheet/${selected}?asOf=${filters.asOf}`).then(r=>live&&setDetail(r)).catch(error=>live&&setDetail({error}));return()=>{live=false;};},[request,selected,revision,filters.asOf]);
 const field=(key,label,type='text',values)=><Field label={label} type={type} options={values} value={filters[key]} onChange={v=>{setFilters({...filters,[key]:v});setPage(1);}}/>;
 return <section className="card ss-sheet stack"><div role="group" aria-label="列セット" className="es-tabs">{Object.entries(SET_LABELS).map(([key,label])=><Button key={key} aria-pressed={setKey===key} onClick={()=>setSetKey(key)}>{label}</Button>)}</div><div className="es-fields">{field('projectId','案件で絞る','text',opts(options.projects))}{field('workId','作品で絞る','text',opts(options.works,'title'))}{field('partnerId','支払先で絞る','text',opts(options.partners))}{field('month','計上月で絞る','month')}{field('closingOn','締め日で絞る','date')}{field('dueOn','出金予定日で絞る','date')}{field('status','状態で絞る','text',['未整備','未払い','一部払い','払い済み','源泉未確認'].map(value=>({value,label:value})))}{field('asOf','基準日','date')}</div>
 <div className="es-tabs"><a href={'/api/expense-sheet/export.xlsx?'+query} download>Excelで書き出し</a><a href={'/api/expense-sheet/export.csv?'+query} download>CSVで書き出し</a></div>{state.error&&<Notice error={state.error}/>}<p>条件に合う明細 {state.total??0}件</p>{state.totals&&<p>税抜合計 {state.totals.actual_ex_tax.known.toLocaleString('ja-JP')}円（未確認 {state.totals.actual_ex_tax.unknown}件）／差引支払額 {state.totals.payable_yen.known.toLocaleString('ja-JP')}円（未確認 {state.totals.payable_yen.unknown}件）／支払残額 {state.totals.cash_due_yen.known.toLocaleString('ja-JP')}円（未確認 {state.totals.cash_due_yen.unknown}件）</p>}
 <DataGrid key={setKey} ariaLabel="経費集計シート" columns={(state.columns??[]).map((c,n)=>({...c,sticky:n<2,total:'none',render:r=>{const value=setKey==='legacy'&&c.key==='withholding_yen'&&r[c.key]!=null?-r[c.key]:r[c.key];return value==null?'未確認':typeof value==='number'&&c.key!=='id'?value.toLocaleString('ja-JP'):String(value);}}))} rows={state.rows??[]} rowKey="id" onRowClick={r=>{setSelected(r.id);setRepair(false);}}/><div className="es-tabs"><Button disabled={page<=1} onClick={()=>setPage(page-1)}>前のページ</Button><span>{page}ページ</span><Button disabled={page*100>=(state.total??0)} onClick={()=>setPage(page+1)}>次のページ</Button></div>
 {detail?.error&&<Notice error={detail.error}/>} {detail?.row&&<div className="es-detail" aria-label="経費の詳細"><h3>{detail.row.description}</h3><dl>{[['請求書番号',detail.row.invoice?.invoice_number],['証憑の種類',({invoice:'請求書',receipt:'領収書',credit_note:'減額証憑',other:'その他'})[detail.row.invoice?.document_kind]],['請求日',detail.row.invoice_on],['締め日',detail.row.closing_on],['出金予定日',detail.row.due_on],['出金日',detail.row.paid_on],['締め日の由来',({term:'支払条件',manual:'手入力',override:'個別に変更'})[detail.row.invoice?.closing_origin]],['予定日の由来',({term:'支払条件',manual:'手入力',override:'個別に変更'})[detail.row.invoice?.due_origin]],['日付の変更理由',detail.row.invoice?.override_note],['源泉の控除',detail.row.withholding_yen==null?'未確認':detail.row.withholding_yen+'円'],['状態',detail.row.status]].map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{value??'未確認'}</dd></React.Fragment>)}</dl><PaymentHistory request={request} row={detail.row} onSaved={()=>{setRevision(n=>n+1);onSaved?.();}}/><PaymentForm request={request} row={detail.row} options={options} onSaved={()=>{setRevision(n=>n+1);onSaved?.();}}/><h4>会計の版</h4>{detail.accountingVersions.map(v=><p key={v.id}>版{v.version_no}／{v.reason}／{v.created_at}</p>)}<h4>取込の束</h4>{detail.imports.length?detail.imports.map(r=><p key={r.batch_id}>{r.batch_id}／元の行 {r.row_no}／下見版 {r.version_id}</p>):<p>手入力</p>}{detail.row.invoice_id&&<InvoiceFiles request={request} invoiceId={detail.row.invoice_id} version={detail.row.invoice.version_no} files={detail.files} onSaved={()=>{setRevision(n=>n+1);onSaved?.();}}/>}{detail.row.status==='未整備'&&<><Button onClick={()=>setRepair(!repair)}>整備</Button>{repair&&<ExpenseEntry request={request} options={options} repair={detail.row} onSaved={onSaved}/>}</>}</div>}
 </section>;
}
