import {isDbConflict} from '../data-platform/db-errors.mjs';
import {adoptionPreview,adoptExpenseCategories} from '../expense-accounting/adoption.mjs';
import {importService} from './import-service.mjs';
import {registerSheetRoutes} from './sheet-routes.mjs';
import {expenseChangeGuard} from '../expense-accounting/settlement-service.mjs';
import {registerSettlementRoutes,allFinance} from '../expense-accounting/settlement-routes.mjs';
import {loadSettlement,settlementProjection} from '../expense-accounting/settlement-model.mjs';
import {expenseService,insert,newId} from './expense-service.mjs';
import {fail,str,integer,day,expected,calculateDates,paymentBalance} from './expense-model.mjs';
import {ACCOUNTING_SPECS,accountingSetting} from '../expense-accounting/accounting-model.mjs';
import {EXPENSE_COLUMN_VERSION,EXPENSE_COLUMN_SETS} from './expense-columns.mjs';
export function registerExpenseRoutes(app,deps){
 const {db,bad,body}=deps,s=expenseService(deps);
 const wrap=fn=>async(c,next)=>{try{return await fn(c,next);}catch(e){return bad(c,e.message,e.status??(isDbConflict(e)||/immutable|mismatch|stale|locked|balance|void all|paid|duplicate/i.test(e.message)?409:400),undefined,e);}};
 const input=async c=>{const b=await body(c);if(!b||Array.isArray(b)||typeof b!=='object')fail('入力を確認してください');if(new TextEncoder().encode(JSON.stringify(b)).length>65536&&!c.req.path.endsWith('/expense-source-files')&&!c.req.path.startsWith('/api/expense-imports/'))fail('入力は64KiB以内にしてください',413);return b;};
 const identity=c=>c.get('identity');
 const id=c=>integer(Number(c.req.param('id')),1);
 const admin=async i=>{await s.finance(i);if(i.role!=='admin')fail('会計の設定は管理者だけが変更できます',403);};
 registerSettlementRoutes(app,s,{wrap,input,identity});
 registerSheetRoutes(app,s,{wrap,input,identity});
 app.get('/api/expense-accounting/settings',wrap(async c=>{const i=identity(c);await s.finance(i);const settings={};for(const [key,spec] of Object.entries(ACCOUNTING_SPECS))settings[key]=await db.all(`SELECT v.*${spec.identity?',m.code':''} FROM ${spec.table} v ${spec.identity?`JOIN ${spec.identity} m ON m.org_id=v.org_id AND m.id=v.${spec.parent}`:''} WHERE v.org_id=? ORDER BY v.version_no`,[i.org_id]);return c.json({ok:true,settings,columnVersion:EXPENSE_COLUMN_VERSION,columnSets:EXPENSE_COLUMN_SETS});}));
 app.get('/api/expense-accounting/adoption-preview',wrap(async c=>{const i=identity(c);await admin(i);return c.json({ok:true,...await adoptionPreview(db,i.org_id)});}));
 app.post('/api/expense-accounting/adopt',wrap(async c=>{const i=identity(c);await admin(i);return c.json({ok:true,...await adoptExpenseCategories(s,i,await input(c))},201);}));
 app.post('/api/expense-accounting/:kind',wrap(async c=>{const i=identity(c);await admin(i);const kind=c.req.param('kind'),spec=ACCOUNTING_SPECS[kind];if(!spec)fail('設定がありません',404);const b=await input(c),base=expected(b),values=accountingSetting(kind,b),statements=[];let parent;
 if(spec.identity){const code=str(b.code,60,true),old=await db.get(`SELECT id FROM ${spec.identity} WHERE org_id=? AND code=?`,[i.org_id,code]);parent=old?.id??newId();if(!old)statements.push(insert(spec.identity,{id:parent,code,...s.meta(i,b)}));}
 else if(kind==='aliases')parent=str(b.alias_text,100,true).normalize('NFKC').trim();else {parent=integer(b[spec.parent],1);await s.ref(i,spec.reference,parent);}
 for(const [field,table] of [['account_class_version_id','gl_account_class_versions'],['category_version_id','expense_category_versions']])if(values[field])await s.ref(i,table,values[field],true);
 if(kind==='categories'){const cl=await s.ref(i,'gl_account_class_versions',values.account_class_version_id,true),account=await s.ref(i,'gl_accounts',cl.account_id);if(!['cogs','sga','non_operating_expense','extraordinary_loss','income_tax'].includes(account.section))fail('費用の勘定科目を選んでください');}
 const versionId=newId();statements.push(s.versionGuard(i,spec.table,spec.parent,parent,base),insert(spec.table,{id:versionId,[spec.parent]:parent,version_no:base+1,...values,...s.meta(i,b)}),s.audit(i,spec.table,parent,b));await s.batch(statements);return c.json({ok:true,id:versionId,parent_id:parent,version:base+1},201);}));
 app.post('/api/expense-invoices/date-preview',wrap(async c=>{const i=identity(c);await s.finance(i);const b=await input(c),partner=integer(b.partner_id,1);return c.json({ok:true,dates:calculateDates(day(b.invoice_on),await s.term(i,partner,b.invoice_on,b.payment_term_version_id))});}));
 app.post('/api/expense-invoices',wrap(async c=>{const i=identity(c);await s.finance(i);const result=await s.invoiceStatements(i,await input(c));await s.batch(result.statements);return c.json({ok:true,id:result.id,version:result.version},201);}));
 app.post('/api/expense-invoices/:id/versions',wrap(async c=>{const i=identity(c),inv=await s.invoice(i,id(c)),b=await input(c),result=await s.invoiceStatements(i,b,inv);if(b.active===0){const lines=await db.all('SELECT expense_id FROM expense_details WHERE org_id=? AND invoice_id=? AND expense_id NOT IN (SELECT expense_id FROM expense_line_voids WHERE org_id=?)',[i.org_id,inv.id,i.org_id]);result.statements.unshift(await expenseChangeGuard(s,i,{voids:lines.map(l=>({id:l.expense_id,on:day(b.voided_on)}))}),...lines.map(l=>insert('expense_line_voids',{expense_id:l.expense_id,voided_on:day(b.voided_on),replacement_expense_id:null,...s.meta(i,b)})));}await s.batch(result.statements);return c.json({ok:true,id:inv.id,version:result.version},201);}));
 app.get('/api/expense-invoices/:id',wrap(async c=>{const i=identity(c),inv=await s.invoice(i,id(c));return c.json({ok:true,invoice:inv,versions:await db.all('SELECT * FROM expense_invoice_versions WHERE org_id=? AND invoice_id=? ORDER BY version_no',[i.org_id,inv.id]),files:await db.all('SELECT l.id,l.file_id,f.file_name FROM expense_invoice_file_links l JOIN expense_source_files f ON f.org_id=l.org_id AND f.id=l.file_id WHERE l.org_id=? AND l.invoice_id=? AND NOT EXISTS(SELECT 1 FROM expense_invoice_file_unlinks u WHERE u.org_id=l.org_id AND u.link_id=l.id)',[i.org_id,inv.id]),details:await db.all('SELECT d.*,e.actual_ex_tax,e.tax_amount,e.actual_inc_tax FROM expense_details d JOIN expenses e ON e.org_id=d.org_id AND e.id=d.expense_id WHERE d.org_id=? AND d.invoice_id=?',[i.org_id,inv.id])});}));
 app.get('/api/expense-invoices',wrap(async c=>{const i=identity(c);await s.finance(i);const rows=[];for(const inv of await db.all('SELECT id FROM expense_invoices WHERE org_id=?',[i.org_id])){try{const row=await s.invoice(i,inv.id);rows.push({...row,current:await s.latest(i,'expense_invoice_versions','invoice_id',inv.id)});}catch(e){if(e.status!==403)throw e;}}return c.json({ok:true,rows});}));
 app.post('/api/expenses',wrap(async c=>{const i=identity(c),b=await input(c);return c.json({ok:true,...await s.makeExpense(i,b)},201);}));
 app.post('/api/expense-pending',wrap(async c=>{const i=identity(c),b=await input(c);await s.finance(i,integer(b.project_id,1));const row={id:newId(),project_id:b.project_id,code:str(b.code,60,true),raw_payload_json:JSON.stringify(b.payload??{}),...s.meta(i,b)};await s.batch([insert('expense_pending_rows',row),s.audit(i,'expense_pending',row.id,b)]);return c.json({ok:true,id:row.id,status:'保留'},201);}));
 app.post('/api/expenses/:id/repair',wrap(async c=>{const i=identity(c),legacy=await s.expense(i,id(c)),b=await input(c);return c.json({ok:true,...await s.makeExpense(i,b,{legacy})},201);}));
 app.post('/api/expenses/:id/correct',wrap(async c=>{const i=identity(c),replace=await s.expense(i,id(c)),b=await input(c),d=await db.get('SELECT invoice_id FROM expense_details WHERE org_id=? AND expense_id=?',[i.org_id,replace.id]);if(!d)fail('先に請求書を整備してください',409);return c.json({ok:true,...await s.makeExpense(i,{...b,invoice_id:d.invoice_id},{replace})},201);}));
 app.post('/api/expenses/:id/accounting',wrap(async c=>{const i=identity(c),e=await s.expense(i,id(c)),b=await input(c);await s.batch(await s.accountingStatements(i,e.id,b));return c.json({ok:true,version:b.expectedVersion+1},201);}));
 app.post('/api/expenses/:id/void',wrap(async c=>{const i=identity(c),e=await s.expense(i,id(c)),b=await input(c),d=await db.get('SELECT * FROM expense_details WHERE org_id=? AND expense_id=?',[i.org_id,e.id]);if(!d)fail('請求書の整備が必要です',409);await s.invoice(i,d.invoice_id);const base=expected(b);await s.batch([await expenseChangeGuard(s,i,{voids:[{id:e.id,on:day(b.voided_on)}]}),s.versionGuard(i,'expense_accounting_versions','expense_id',e.id,base),insert('expense_line_voids',{expense_id:e.id,voided_on:day(b.voided_on),replacement_expense_id:b.replacement_expense_id==null?null:integer(b.replacement_expense_id,1),...s.meta(i,b)}),s.audit(i,'expense_void',e.id,b)]);return c.json({ok:true},201);}));
 app.post('/api/expense-payments',wrap(async(c,next)=>{const b=await input(c),i=identity(c);await s.finance(i);const d=await db.get('SELECT 1 FROM expense_details WHERE org_id=? AND expense_id=?',[i.org_id,b.expenseId]);if(!d)return next();return c.json({ok:true,...await s.recordPayment(i,b)},201);}));
 app.post('/api/expense-payments/:id/reverse',wrap(async(c,next)=>{const i=identity(c);await s.finance(i);const p=await db.get('SELECT 1 FROM expense_payment_accounting WHERE org_id=? AND payment_id=?',[i.org_id,id(c)]);if(!p)return next();return c.json({ok:true,...await s.recordPayment(i,await input(c),id(c))},201);}));
 app.post('/api/expense-payments/:id/accounting',wrap(async c=>{const i=identity(c),p=await s.ref(i,'expense_payments',id(c)),e=await s.expense(i,p.expense_id),b=await input(c),a=await s.latest(i,'expense_accounting_versions','expense_id',e.id);if(!a)fail('明細の会計確認が必要です',409);const cash=b.cashAccountClassVersionId==null?null:integer(b.cashAccountClassVersionId,1);if(cash)await s.ref(i,'gl_account_class_versions',cash,true);await s.batch([s.versionGuard(i,'expense_accounting_versions','expense_id',e.id,expected(b)),insert('expense_payment_accounting',{payment_id:p.id,accounting_version_id:a.id,withheld_yen:integer(b.withheldYen,-Number.MAX_SAFE_INTEGER),cash_account_class_version_id:cash,...s.meta(i,b)}),s.audit(i,'expense_payment_accounting',p.id,b)]);return c.json({ok:true,id:p.id},201);}));
 app.post('/api/expense-source-files',wrap(async c=>{const i=identity(c);await s.finance(i);const b=await input(c),raw=b.original_base64;if(typeof raw!=='string'||raw.length>16*1024*1024||!/^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(raw)||!raw.length)fail('原本は16MiB以下の正しいbase64で指定してください');const bytes=Uint8Array.from(atob(raw),x=>x.charCodeAt(0));if(btoa(String.fromCharCode(...bytes.slice(0,Math.min(bytes.length,3)))).slice(0,4)!==raw.slice(0,4))fail('原本の形式を確認してください');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');if(await db.get('SELECT 1 FROM expense_source_files WHERE org_id=? AND raw_sha256=?',[i.org_id,hash]))fail('同じ原本が登録済みです',409);const row={id:newId(),file_name:str(b.file_name,240,true),media_type:str(b.media_type,100,true),byte_length:bytes.length,raw_sha256:hash,original_base64:raw,...s.meta(i,b)};await s.batch([insert('expense_source_files',row),s.audit(i,'expense_source_file',row.id,b)]);return c.json({ok:true,id:row.id,sha256:hash},201);}));
 async function fileAccess(i,file){await s.finance(i);for(const b of await db.all('SELECT id FROM expense_import_batches WHERE org_id=? AND file_id=?',[i.org_id,file]))await importService(s).access(i,b.id);const f=await s.ref(i,'expense_source_files',file),links=await db.all('SELECT l.invoice_id FROM expense_invoice_file_links l WHERE l.org_id=? AND l.file_id=? AND NOT EXISTS(SELECT 1 FROM expense_invoice_file_unlinks u WHERE u.org_id=l.org_id AND u.link_id=l.id)',[i.org_id,file]);for(const l of links)await s.invoice(i,l.invoice_id);if(!links.length&&f.created_by!==i.user_id&&i.role!=='admin')fail('原本の権限がありません',403);return f;}
 app.get('/api/expense-source-files/:id',wrap(async c=>{const f=await fileAccess(identity(c),id(c));return c.json({ok:true,file:f});}));
 app.post('/api/expense-invoices/:id/files',wrap(async c=>{const i=identity(c),inv=await s.invoice(i,id(c)),b=await input(c),file=integer(b.file_id,1);await fileAccess(i,file);const link=newId();await s.batch([s.versionGuard(i,'expense_invoice_versions','invoice_id',inv.id,expected(b)),insert('expense_invoice_file_links',{id:link,invoice_id:inv.id,file_id:file,purpose:str(b.purpose,20,true),...s.meta(i,b)}),s.audit(i,'expense_file_link',link,b)]);return c.json({ok:true,id:link},201);}));
 app.post('/api/expense-file-links/:id/unlink',wrap(async c=>{const i=identity(c),l=await s.ref(i,'expense_invoice_file_links',id(c)),b=await input(c);await s.invoice(i,l.invoice_id);await fileAccess(i,l.file_id);await s.batch([s.versionGuard(i,'expense_invoice_versions','invoice_id',l.invoice_id,expected(b)),insert('expense_invoice_file_unlinks',{link_id:l.id,...s.meta(i,b)}),s.audit(i,'expense_file_unlink',l.id,b)]);return c.json({ok:true},201);}));
 app.get('/api/expense-journal',wrap(async c=>{
  const i=identity(c),allowed=await s.finance(i),data=await loadSettlement(db,i.org_id),q=c.req.query();
  const from=q.from?day(q.from):'0001-01-01',to=q.to?day(q.to):q.asOf?day(q.asOf):'9999-12-31';if(from>to)fail('仕訳の期間を確認してください');
  const work=q.workId?integer(Number(q.workId),1):null,partner=q.partnerId?integer(Number(q.partnerId),1):null;
  if(work){const w=await s.ref(i,'works',work);await s.finance(i,w.project_id);}if(partner)await s.ref(i,'partners',partner);
  data.expenses=data.expenses.filter(e=>allowed.has(e.project_id)&&(!work||e.work_id===work)&&(!partner||e.partner_id===partner));
  const ids=new Set(data.expenses.map(e=>e.id));data.payments=data.payments.filter(p=>ids.has(p.expense_id));
  data.records.expense_refund_receipts=data.records.expense_refund_receipts.filter(r=>ids.has(r.credit_expense_id));
  const all=await db.all('SELECT id FROM projects WHERE org_id=?',[i.org_id]);
  if(work||partner||all.some(p=>!allowed.has(p.id))){data.records.expense_withholding_remittances=[];data.records.expense_card_debits=[];data.allocations=[];}
  const result=settlementProjection(data,to),classes=await db.all('SELECT c.id,g.name FROM gl_account_class_versions c JOIN gl_accounts g ON g.org_id=c.org_id AND g.id=c.account_id WHERE c.org_id=?',[i.org_id]);
  const names=new Map(classes.map(c=>[c.id,c.name]));const rows=result.journal.filter(r=>r.on>=from).map(r=>({...r,invoice_id:data.expenses.find(e=>e.id===r.expense_id)?.invoice_id??null,lines:r.lines.map(l=>({...l,account_name:names.get(l.account_class_version_id)??'科目未整備'}))}));
  const sum=side=>rows.flatMap(r=>r.lines).filter(l=>l.side===side).reduce((n,l)=>n+l.amount_yen,0);
  return c.json({ok:true,rows,unready:result.unready,debitYen:sum('debit'),creditYen:sum('credit')});
 }));
 return s;
}
