import {reversalDateError} from '../pl-bs/payment-actions.mjs';
import React,{useEffect,useState} from 'react';
import {DataGrid} from '../ui/DataGrid.jsx';
import {Notice} from '../ui/Notice.jsx';
import {Field,Button,post,num,opts,latest,today,useAction} from './ExpenseFields.jsx';
function SettlementRecords({request,kind,revision,onSaved}){const [state,setState]=useState({}),[on,setOn]=useState(today()),[reason,setReason]=useState(''),action=useAction(onSaved);useEffect(()=>{let live=true;request('/expense-'+kind).then(r=>live&&setState(r)).catch(error=>live&&setState({error}));return()=>{live=false;};},[request,kind,revision]);return <section><h4>決済の履歴と取消</h4>{state.error&&<Notice error={state.error}/>}<Field label="決済の取消日" type="date" value={on} onChange={setOn}/><Field label="決済の取消理由" value={reason} onChange={setReason}/>{state.rows?.map(r=><p key={r.id}>{r.code}／{r.occurred_on}／{r.amount_yen.toLocaleString('ja-JP')}円 {r.voided_on?'取消日 '+r.voided_on:<Button disabled={action.busy} onClick={()=>action.run(()=>post(request,`/expense-${kind}/${r.id}/void`,{expectedVersion:1,voided_on:on,reason}))}>この決済を取り消す</Button>}</p>)}{action.notice}</section>;}
export function PaymentForm({request,row,options,onSaved}){const [draft,set]=useState({paidOn:today(),amountYen:'',withheldYen:'',method:'transfer',reason:''}),action=useAction(onSaved);const field=(key,label,type='text',values)=><Field label={label} value={draft[key]} onChange={v=>set({...draft,[key]:v})} type={type} options={values}/>;const classes=options.settings?.['account-classes']??[],accountOptions=role=>opts(classes.filter(c=>c.active&&role.includes(c.settlement_role)).map(c=>({...c,name:`${options.gl_accounts?.find(a=>a.id===c.account_id)?.name??c.account_id}（版${c.version_no}）`})));
 return <form aria-label="出金の記録" className="stack" onSubmit={async e=>{e.preventDefault();await action.run(()=>post(request,'/expense-payments',{...draft,expenseId:row.id,expectedVersion:row.accounting?.version_no,amountYen:num(draft.amountYen),withheldYen:num(draft.withheldYen),cashAccountClassVersionId:num(draft.cashAccountClassVersionId),cardVersionId:num(draft.cardVersionId),counterAccountClassVersionId:num(draft.counterAccountClassVersionId),billingInvoiceId:num(draft.billingInvoiceId)}));}}><h4>出金の記録</h4><p>支払残額 {row.cash_due_yen??'未確認'}円／未控除の源泉 {row.balance?.withholding_due_yen??'未確認'}円</p><div className="es-fields">{field('paidOn','出金日','date')}{field('amountYen','出金額（円）','number')}{field('withheldYen','今回の源泉控除額（円）','number')}{field('method','支払方法','text',[{value:'transfer',label:'振込'},{value:'cash',label:'現金'},{value:'card',label:'カード'},{value:'offset',label:'相殺'},{value:'other',label:'その他'}])}{!['card','offset'].includes(draft.method)&&field('cashAccountClassVersionId','現預金科目','text',accountOptions(['cash']))}{draft.method==='card'&&field('cardVersionId','カードの条件版','text',opts(latest(options.cards,'card_id').filter(c=>c.active)))}{draft.method==='offset'&&<>{field('counterAccountClassVersionId','相殺する債権科目','text',accountOptions(['receivable','refund_receivable']))}{field('counterDescription','相殺の摘要')}{field('billingInvoiceId','売上請求書ID（任意）','number')}</>}{field('reason','出金の理由')}</div>{action.notice}<Button type="submit" disabled={action.busy||row.cash_due_yen==null||!row.accounting}>出金を記録</Button></form>;
}
export function PaymentHistory({request,row,onSaved}){const [selected,setSelected]=useState(null),[on,setOn]=useState(today()),[reason,setReason]=useState(''),action=useAction(onSaved);return <section aria-label="支払の履歴"><h4>支払の履歴</h4>{!row.payments?.length&&<p>出金の記録はまだありません。</p>}{row.payments?.map(p=><p key={p.id} id={`payment-${p.id}`}>{p.paid_on}／{p.amount_yen.toLocaleString('ja-JP')}円／源泉 {p.withheld_yen??'未確認'}円 {p.reverses_id?'取消の記録':<Button onClick={()=>{setSelected(p);setOn(p.paid_on);}}>この出金を取り消す</Button>}</p>)}{selected&&<form aria-label="出金の取消" onSubmit={async e=>{e.preventDefault();const r=await action.run(()=>{const error=reversalDateError({paidOn:selected.paid_on,reversedOn:on});if(error)throw Error(error);return post(request,`/expense-payments/${selected.id}/reverse`,{expectedVersion:row.accounting.version_no,reversedOn:on,reason});});if(r)setSelected(null);}}><Field label="取消日" type="date" value={on} onChange={setOn}/><Field label="取消理由" value={reason} onChange={setReason}/><Button type="submit" disabled={action.busy}>取消を記録</Button></form>}{action.notice}</section>;}
export function ExpensePayout({request,options,onSaved}){const [group,setGroup]=useState('partner'),[asOf,setAsOf]=useState(today()),[result,setResult]=useState({}),[revision,setRevision]=useState(0),[selected,setSelected]=useState(null),[kind,setKind]=useState('withholding-remittances'),[draft,set]=useState({code:'',occurred_on:today(),amount_yen:'',reason:''}),[balances,setBalances]=useState({}),[invoice,setInvoice]=useState(null),action=useAction(()=>{setRevision(n=>n+1);onSaved?.();});
 useEffect(()=>{let live=true;request(`/expense-payouts?groupBy=${group}&asOf=${asOf}`).then(r=>live&&setResult(r)).catch(error=>live&&setResult({error}));request(`/expense-accounting/balances?asOf=${asOf}`).then(r=>live&&setBalances(r)).catch(error=>live&&setBalances({error}));return()=>{live=false;};},[request,group,asOf,revision]);
 const current=result.rows?.flatMap(g=>g.lines).find(r=>r.id===selected);const field=(key,label,type='text',values)=><Field label={label} type={type} options={values} value={draft[key]} onChange={v=>set({...draft,[key]:v})}/>;
 return <section className="card stack"><h3>出金予定</h3><div className="es-fields"><Field label="集計の切り口" options={[{value:'partner',label:'支払先別'},{value:'closing',label:'締め日別'}]} value={group} onChange={setGroup}/><Field label="出金予定の基準日" type="date" value={asOf} onChange={setAsOf}/></div>{result.error&&<Notice error={result.error}/>}<p>除外：未整備 {result.excluded?.unready??0}件／源泉未確認 {result.excluded?.withholding??0}件（既知の税込額 {result.excluded?.known_yen??0}円）</p><DataGrid ariaLabel="出金予定の集計" columns={[{key:'label',label:group==='partner'?'支払先':'締め日'},{key:'count',label:'件数',type:'int'},{key:'cash_due_yen',label:'支払残額',type:'yen'},{key:'withholding_due_yen',label:'未控除の源泉',type:'yen'}]} rows={result.rows??[]} rowKey="id" showTotals/>
 <DataGrid ariaLabel="出金予定の明細" rows={result.rows?.flatMap(g=>g.lines)??[]} columns={[{key:'partner_name',label:'支払先'},{key:'description',label:'請求項目'},{key:'closing_on',label:'締め日'},{key:'due_on',label:'出金予定日'},{key:'paid_on',label:'出金日'},{key:'cash_due_yen',label:'支払残額',type:'yen'}]} rowKey="id" onRowClick={r=>{setSelected(r.id);setInvoice(null);}}/>
 {current&&<div className="es-detail"><h4>{current.description}</h4><PaymentHistory request={request} row={current} onSaved={()=>{setRevision(n=>n+1);onSaved?.();}}/><PaymentForm request={request} row={current} options={options} onSaved={()=>{setRevision(n=>n+1);onSaved?.();}}/><Button onClick={async()=>{try{const r=await request('/expense-sheet?pageSize=500&asOf='+asOf);setInvoice(r.rows.filter(x=>x.invoice_id===current.invoice_id&&x.cash_due_yen>0));}catch(error){setResult({...result,error});}}}>請求書一括支払の下見</Button></div>}
 {invoice&&<InvoicePayment request={request} rows={invoice} options={options} onSaved={()=>{setInvoice(null);setRevision(n=>n+1);onSaved?.();}}/>}
 <a href={`/api/expense-payouts/export.xlsx?groupBy=${group}&asOf=${asOf}`} download>出金予定をExcelで書き出し</a><h4>源泉の納付・カードの引落・返金の入金</h4>{balances.error?<Notice error={balances.error}/>:<><p>未納付の預り金 {balances.totals?.withholding??0}円／カード未払 {balances.totals?.card_payable??0}円／返金未収 {balances.totals?.refund_receivable??0}円</p>{balances.cards?.map(c=><p key={c.card_id}>{options.cards?.find(x=>x.card_id===c.card_id)?.name??'カード'}：未引落 {c.amount_yen}円</p>)}{balances.pendingOffsets?.map(p=><p key={p.payment_id}>相殺の反映待ち：{p.counter_description}／{p.amount_yen}円</p>)}{balances.withholdingMonths?.map(m=><p key={m.payment_month}>{m.payment_month} 支払分：未納付 {m.amount_yen}円</p>)}</>}
 <form aria-label="決済の記録" onSubmit={async e=>{e.preventDefault();const body={...draft,expectedVersion:0,amount_yen:num(draft.amount_yen),cash_account_class_version_id:num(draft.cash_account_class_version_id),card_id:num(draft.card_id),credit_expense_id:num(draft.credit_expense_id),partner_id:num(draft.partner_id)};await action.run(()=>post(request,'/expense-'+kind,body));}}><Field label="記録する決済" value={kind} onChange={setKind} options={[{value:'withholding-remittances',label:'源泉の納付'},{value:'card-debits',label:'カードの引落'},{value:'refund-receipts',label:'返金の入金'}]}/><div className="es-fields">{field('code','決済コード')}{field('occurred_on','決済日','date')}{field('amount_yen','決済額（円）','number')}{field('cash_account_class_version_id','決済の現預金科目','text',opts((options.settings?.['account-classes']??[]).filter(c=>c.settlement_role==='cash').map(c=>({...c,name:options.gl_accounts?.find(a=>a.id===c.account_id)?.name}))))}{kind==='withholding-remittances'&&<>{field('month_from','対象支払月（開始）','month')}{field('month_to','対象支払月（終了）','month')}</>}{kind==='card-debits'&&field('card_id','引落するカード','text',latest(options.cards,'card_id').map(c=>({value:c.card_id,label:c.name})))}{kind==='refund-receipts'&&<>{field('credit_expense_id','減額の経費ID','number')}{field('partner_id','返金の支払先','text',opts(options.partners))}</>}{field('reason','決済の理由')}</div>{action.notice}<Button type="submit" disabled={action.busy}>決済を記録</Button></form><SettlementRecords request={request} kind={kind} revision={revision} onSaved={()=>{setRevision(n=>n+1);onSaved?.();}}/>
 </section>;
}
function InvoicePayment({request,rows,options,onSaved}){const [on,setOn]=useState(today()),[cash,setCash]=useState(''),[reason,setReason]=useState(''),action=useAction(onSaved);const total=rows.reduce((n,r)=>n+r.cash_due_yen,0);return <form aria-label="請求書一括支払" className="es-detail" onSubmit={async e=>{e.preventDefault();await action.run(()=>post(request,`/expense-invoices/${rows[0].invoice_id}/pay`,{paidOn:on,totalYen:total,method:'transfer',cashAccountClassVersionId:num(cash),reason,allocations:rows.map(r=>({expenseId:r.id,expectedVersion:r.accounting.version_no,amountYen:r.cash_due_yen,withheldYen:r.balance.withholding_due_yen}))}));}}><h4>請求書一括支払の下見</h4>{rows.map(r=><p key={r.id}>{r.description}：支払 {r.cash_due_yen}円／控除 {r.balance.withholding_due_yen}円</p>)}<p>合計 {total}円</p><Field label="一括支払の出金日" type="date" value={on} onChange={setOn}/><Field label="一括支払の現預金科目" value={cash} onChange={setCash} options={opts((options.settings?.['account-classes']??[]).filter(c=>c.settlement_role==='cash').map(c=>({...c,name:options.gl_accounts?.find(a=>a.id===c.account_id)?.name})))}/><Field label="一括支払の理由" value={reason} onChange={setReason}/>{action.notice}<Button type="submit" disabled={action.busy}>この内訳で一括支払を記録</Button></form>;}
