import {insert,newId,guard} from './expense-service.mjs';
import {day,integer,fail,expected,invoiceValues,expenseValues,detailValues,addYen} from './expense-model.mjs';
import {accountingValues} from '../expense-accounting/accounting-model.mjs';
import {expenseChangeGuard} from '../expense-accounting/settlement-service.mjs';
import {decodeExpenseFile} from './expense-workbook.mjs';
import {integer as readInteger} from '../csv.mjs';
export const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof value==='string'?new TextEncoder().encode(value):value)),x=>x.toString(16).padStart(2,'0')).join('');
// 複数行の同じINSERTをJSONの1束縛値へまとめる。業務行は最終の1batchまで一切作らない。
// 親→子の順序と最後の請求書必須検査を保ち、値は120KB未満に分割する。
export function compactImport(statements){
 const order=['expense_invoices','expense_invoice_versions','expenses','expense_details','expense_credit_links','expense_accounting_versions','expense_invoice_file_links','expense_import_row_commits','expense_import_events','audit_log'];
 const before=[],after=[],groups=new Map();
 for(const statement of statements){const m=statement.sql.match(/^INSERT INTO (\w+)\(([^)]+)\) VALUES\(/);if(!m){(statement.sql.includes('NOT EXISTS(SELECT 1 FROM expenses e JOIN expense_details')?after:before).push(statement);continue;}if(!order.includes(m[1]))fail('未対応の取込処理です');const key=m[1]+'|'+m[2],g=groups.get(key)??{table:m[1],columns:m[2],rows:[]};g.rows.push(statement.params);groups.set(key,g);}
 const out=[...before];for(const table of order)for(const g of [...groups.values()].filter(g=>g.table===table)){let chunk=[];const flush=()=>{if(!chunk.length)return;out.push({sql:`INSERT INTO ${g.table}(${g.columns}) SELECT ${g.columns.split(',').map((_,n)=>`json_extract(value,'$[${n}]')`).join(',')} FROM json_each(?)`,params:[JSON.stringify(chunk)]});chunk=[];};for(const row of g.rows){if(new TextEncoder().encode(JSON.stringify([...chunk,row])).length>=120000)flush();chunk.push(row);}flush();}return [...out,...after];
}
const present=v=>v!==null&&v!==undefined&&v!=='';
function dateCell(v){if(typeof v==='number'){integer(v,1);return day(new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10));}return day(String(v??'').replaceAll('/','-'));}
function money(v){if(!present(v)||typeof v==='string'&&!v.trim())fail('金額が未確認です');return integer(typeof v==='number'?v:readInteger(v,{signed:true}),-Number.MAX_SAFE_INTEGER);}
function calculatedTax(amount,tax){const numerator=BigInt(amount)*BigInt(tax.rate_bps??0),base=10000n,quotient=numerator/base,remainder=numerator%base;let result=quotient;if(tax.rounding==='floor'&&remainder<0n)result--;if(tax.rounding==='ceil'&&remainder>0n)result++;if(tax.rounding==='nearest'){if(remainder>=5000n)result++;if(remainder< -5000n)result--;}return integer(Number(result),-Number.MAX_SAFE_INTEGER);}
export function importService(s){const db=s.db;
 async function access(i,id){await s.finance(i);const b=await s.ref(i,'expense_import_batches',id);if(i.role!=='admin'&&b.created_by!==i.user_id)fail('取込の作成者と管理者だけが確認できます',403);const version=await s.latest(i,'expense_import_versions','batch_id',id);if(version){const payload=JSON.parse(version.payload_json);for(const r of payload.rows)if(r.supplement.project_id)await s.finance(i,r.supplement.project_id);}return b;}
 async function references(i){const result={};for(const t of ['partners','works','products','expense_category_versions','expense_category_alias_versions','expense_tax_category_versions','expense_withholding_category_versions','partner_payment_term_versions','expense_invoice_versions'])result[t]=await db.all(`SELECT * FROM ${t} WHERE org_id=? ORDER BY id`,[i.org_id]);return digest(JSON.stringify(result));}
 async function evaluate(i,raw,supplement,batchId){const rows=[];
  for(const rawRow of raw){const extra={...supplement,...(supplement.overrides?.[rawRow.row_no]??{})};delete extra.overrides;const v=extra.corrected_values??rawRow.values;if(!Array.isArray(v)||![22,25].includes(v.length))fail('訂正する行の列数を確認してください');const issues=[];let payload=null;
   try{
    await s.finance(i,integer(extra.project_id,1));day(extra.incurred_on);
    const partner=extra.partner_id?await s.ref(i,'partners',integer(extra.partner_id,1)):await db.get('SELECT * FROM partners WHERE org_id=? AND code=?',[i.org_id,String(v[19]??'')]);if(!partner)fail('支払先が見つかりません。支払先コードを確認してください');
    const work=present(v[2])?await db.get('SELECT * FROM works WHERE org_id=? AND code=?',[i.org_id,String(v[2])]):null;if(present(v[2])&&!work)fail('作品が見つかりません');if(work&&work.project_id!==extra.project_id)fail('作品と案件が一致しません');if(!work&&!extra.common_expense)fail('作品なしの共通経費か確認してください');
    const product=present(v[3])?await db.get('SELECT * FROM products WHERE org_id=? AND sku=?',[i.org_id,String(v[3])]):null;if(present(v[3])&&!product)fail('商品が見つかりません');if(product&&((present(v[4])&&v[4]!==product.sku)||(present(v[5])&&v[5]!==product.name)))fail('商品の受領表記を確認してください');
    const category=extra.category_version_id?await s.ref(i,'expense_category_versions',integer(extra.category_version_id,1),true):await db.get(`SELECT v.* FROM expense_category_versions v WHERE v.org_id=? AND v.active=1 AND v.version_no=(SELECT MAX(x.version_no) FROM expense_category_versions x WHERE x.org_id=v.org_id AND x.category_id=v.category_id) AND (v.name=? OR v.id=(SELECT category_version_id FROM expense_category_alias_versions WHERE org_id=? AND alias_text=? ORDER BY version_no DESC LIMIT 1))`,[i.org_id,String(v[21]??''),i.org_id,String(v[21]??'')]);if(!category)fail('費用区分が見つかりません');
    const tax=await s.ref(i,'expense_tax_category_versions',integer(extra.tax_category_version_id,1),true),wh=await s.ref(i,'expense_withholding_category_versions',integer(extra.withholding_category_version_id,1),true);
    const ex=money(extra.actual_ex_tax??v[12]),taxAmount=money(extra.tax_amount??v[13]),withheld=-money(extra.source_withholding??v[14]),payable=money(extra.payable_yen??v[15]);if(withheld<0)fail('源泉の控除は負数で記入してください');if(wh.treatment==='not_applicable'&&withheld!==0)fail('源泉対象外には0を明示してください');
    const recalc=calculatedTax(ex,tax);if(taxAmount!==recalc&&!extra.tax_difference_note?.trim())fail(`税額不一致：受領 ${taxAmount}円、再計算 ${recalc}円。根拠を確認してください`);if(payable!==addYen(ex,taxAmount,-withheld))fail('差引支払額が税抜＋税−源泉と一致しません');if(present(v[24]))fail('出金日は参照専用です。出金予定で別途記録してください');
    const group=(supplement.groups??[]).filter(g=>rawRow.row_no>=g.from&&rawRow.row_no<=g.to);if(group.length>1)fail('請求書の行範囲が重複しています');if(!group.length&&!extra.each_row_invoice)fail('請求書のまとまりを指定してください');
    const grouping=group[0]??{key:'ROW-'+rawRow.row_no,document_kind:extra.document_kind??'receipt'};
    const invoiceOn=dateCell(v[17]),term=await s.term(i,partner.id,invoiceOn);const invoice={code:`IMP-${batchId}-${grouping.key}`,invoice_number:grouping.invoice_number??null,document_kind:grouping.document_kind??'invoice',invoice_on:invoiceOn,closing_on:present(v[22])?dateCell(v[22]):extra.closing_on||undefined,due_on:present(v[23])?dateCell(v[23]):extra.due_on||undefined,override_note:extra.override_note,expectedVersion:0,reason:extra.reason};const dates=invoiceValues(invoice,term);
    const recorded=dateCell(v[6]);payload={project_id:extra.project_id,work_id:work?.id??null,partner_id:partner.id,incurred_on:extra.incurred_on,accounting_month:recorded.slice(0,7),category:category.name,description:String(v[9]??''),actual_ex_tax:ex,tax_amount:taxAmount,actual_inc_tax:addYen(ex,taxAmount),reason:extra.reason,invoice:{...invoice,closing_on:dates.closing_on,due_on:dates.due_on},details:{recorded_on:recorded,product_id:product?.id??null,source_product_number:v[4]||null,source_product_name:v[5]||null,source_client_name:v[7]||null,specification:v[8]||null,supplier_text:v[16]||null,memo:[v[18]||null,extra.tax_difference_note?'税額差の確認根拠：'+extra.tax_difference_note:null].filter(Boolean).join('／')||null,quantity_x10000:present(v[10])?Math.round(Number(v[10])*10000):null,unit_price_x10000:present(v[11])?Math.round(Number(v[11])*10000):null},accounting:{category_version_id:category.id,tax_category_version_id:tax.id,withholding_category_version_id:wh.id,withholding_state:'confirmed',withholding_yen:withheld,expectedVersion:0},credit:extra.credit};
    if(present(v[1])){const dist=await db.get('SELECT code FROM distribution_types WHERE code=? OR label=?',[v[1],v[1]]);if(!dist)fail('流通区分が見つかりません');payload.details.distribution_type_code=dist.code;}
    expenseValues(payload);detailValues(payload.details);accountingValues(payload.accounting);
   }catch(e){if(e.status===403)throw e;issues.push({row:rawRow.row_no,column:/支払先/.test(e.message)?'仕入先ID':/税額/.test(e.message)?'消費税(自動)':/金額/.test(e.message)?'金額(税別)':/源泉/.test(e.message)?'源泉徴収税額':/出金日/.test(e.message)?'出金日':'補足入力',original_values:v,reason:e.message});}
   rows.push({...rawRow,supplement:extra,payload:issues.length?null:payload,issues,status:issues.length?'保留':'登録可'});
  }
  const groups=new Map();for(const row of rows){if(!row.payload)continue;const key=row.payload.invoice.code,signature=JSON.stringify([row.payload.partner_id,row.payload.invoice]);if(groups.has(key)&&groups.get(key)!==signature){for(const r of rows.filter(r=>r.payload?.invoice.code===key)){r.issues.push({row:r.row_no,column:'請求書',reason:'同じ請求書の支払先・日付が一致しません'});r.status='保留';r.payload=null;}}else groups.set(key,signature);}
  const taxGroups=new Map();for(const r of rows.filter(r=>r.payload)){const key=r.payload.invoice.code+':'+r.payload.accounting.tax_category_version_id;const members=taxGroups.get(key)??[];members.push(r);taxGroups.set(key,members);}
  for(const members of taxGroups.values()){const tax=await s.ref(i,'expense_tax_category_versions',members[0].payload.accounting.tax_category_version_id),expectedTax=calculatedTax(addYen(...members.map(r=>r.payload.actual_ex_tax)),tax),receivedTax=addYen(...members.map(r=>r.payload.tax_amount));if(expectedTax!==receivedTax&&!members.every(r=>r.supplement.tax_difference_note?.trim()))for(const r of members){r.issues.push({row:r.row_no,column:'消費税(自動)',original_value:r.values[13],reason:`請求書の税率別合計で丸め差があります（受領 ${receivedTax}円／再計算 ${expectedTax}円）。配賦せず根拠を確認してください`});r.status='保留';r.payload=null;}}
  return {rows,ready:rows.filter(r=>r.payload).length,held:rows.filter(r=>!r.payload).length,excluded:0,known_ex_tax:addYen(...rows.map(r=>{try{return money(r.values[12]);}catch{return 0;}})),unknown:rows.filter(r=>{try{money(r.values[12]);return false;}catch{return true;}}).length};
 }
 async function preview(i,b){await s.finance(i);expected(b);const bytes=Uint8Array.from(atob(b.original_base64??''),x=>x.charCodeAt(0));if(!bytes.length||bytes.length>90000)fail('1ファイルは90KB以内に分けてください',413);const decoded=decodeExpenseFile(bytes,b.file_name),hash=await digest(bytes);if(decoded.rows.length>100)fail('1回の下見は100行以内に分けてください',413);
  let batch=await db.get('SELECT * FROM expense_import_batches WHERE org_id=? AND raw_sha256=?',[i.org_id,hash]);const statements=[];if(batch)await access(i,batch.id);else{batch={id:newId()};let file=await db.get('SELECT id FROM expense_source_files WHERE org_id=? AND raw_sha256=?',[i.org_id,hash]);if(!file){file={id:newId()};statements.push(insert('expense_source_files',{id:file.id,file_name:b.file_name,media_type:/\.csv$/i.test(b.file_name)?'text/csv':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',byte_length:bytes.length,raw_sha256:hash,original_base64:b.original_base64,...s.meta(i,b)}));}statements.push(insert('expense_import_batches',{id:batch.id,file_id:file.id,raw_sha256:hash,layout:decoded.layout,...s.meta(i,b)}));for(const r of decoded.rows)statements.push(insert('expense_import_rows',{id:newId(),batch_id:batch.id,row_no:r.row_no,raw_json:JSON.stringify(r.values),...s.meta(i,b)}));}
  return savePreview(i,b,batch.id,decoded.rows,statements);
 }
 async function savePreview(i,b,batchId,raw,statements=[]){const old=await s.latest(i,'expense_import_versions','batch_id',batchId);if(expected(b)!==(old?.version_no??0))fail('下見の版が変わりました',409);if(await db.get("SELECT 1 FROM expense_import_events WHERE org_id=? AND batch_id=? AND kind='cancelled'",[i.org_id,batchId]))fail('取消済みの束です',409);
  const result=await evaluate(i,raw,{...b.supplement,reason:b.reason},batchId),payload={...result,supplement:b.supplement,referenceHash:await references(i)},json=JSON.stringify(payload);if(new TextEncoder().encode(json).length>=120000)fail('下見が大きいためファイルを分けてください',413);const id=newId(),hash=await digest(json),version=(old?.version_no??0)+1;
  statements.push(s.versionGuard(i,'expense_import_versions','batch_id',batchId,version-1),insert('expense_import_versions',{id,batch_id:batchId,version_no:version,hash,expires_at:new Date(Date.now()+1800000).toISOString(),payload_json:json,...s.meta(i,b)}),s.audit(i,'expense_import_preview',batchId,b));await s.batch(statements);return {id:batchId,version,hash,...result};
 }
 async function check(i,id,b){const batch=await access(i,id),v=await s.latest(i,'expense_import_versions','batch_id',id);if(expected(b)!==v.version_no||b.hash!==v.hash)fail('下見が変わりました。読み直してください',409);if(v.expires_at<new Date().toISOString())fail('下見の期限が切れました。再下見してください',409);if(i.user_id!==v.created_by)fail('下見した利用者で登録してください',403);const payload=JSON.parse(v.payload_json);if(payload.referenceHash!==await references(i))fail('参照する設定が変わりました。再下見してください',409);return {batch,v,payload};}
 async function commit(i,id,b,rowId=null){const batch=await access(i,id),v=await s.latest(i,'expense_import_versions','batch_id',id);expected(b);if(b.hash!==v.hash||b.expectedVersion!==v.version_no)fail('下見が変わりました',409);
  if(await db.get("SELECT 1 FROM expense_import_events WHERE org_id=? AND batch_id=? AND kind='cancelled'",[i.org_id,id]))fail('取消済みです',409);const event=await db.get("SELECT * FROM expense_import_events WHERE org_id=? AND batch_id=? AND kind='committed'",[i.org_id,id]);if(!rowId&&event)return {id,receipt:event.id,replayed:true};
  const checked=await check(i,id,b),payload=checked.payload;if(await db.get("SELECT 1 FROM expense_import_events WHERE org_id=? AND batch_id=? AND kind='cancelled'",[i.org_id,id]))fail('取消済みです',409);
  const raw=await db.all('SELECT * FROM expense_import_rows WHERE org_id=? AND batch_id=?',[i.org_id,id]);const selected=payload.rows.filter(r=>r.payload&&(!rowId||raw.find(x=>x.row_no===r.row_no)?.id===rowId));if(rowId&&!selected.length)fail('保留理由を解消して再下見してください',409);if(rowId&&!event)fail('先に取込の登録をしてください',409);
  const statements=[],stamps=[],invoiceGroups=new Map();for(const table of ['expense_category_versions','expense_tax_category_versions','expense_withholding_category_versions','partner_payment_term_versions','expense_invoice_versions']){const count=(await db.get(`SELECT COUNT(*) n FROM ${table} WHERE org_id=?`,[i.org_id])).n;stamps.push(guard(`(SELECT COUNT(*) FROM ${table} WHERE org_id=?)<>?`,[i.org_id,count]));}let next=(await db.get('SELECT COALESCE(MAX(id),0)+1 id FROM expenses')).id;
  for(const r of selected){const original=raw.find(x=>x.row_no===r.row_no);if(await db.get('SELECT 1 FROM expense_import_row_commits WHERE org_id=? AND row_id=?',[i.org_id,original.id])){if(rowId)fail('解消済みです',409);continue;}
   const p=structuredClone(r.payload),code=p.invoice.code;let inv=invoiceGroups.get(code)??await db.get('SELECT id FROM expense_invoices WHERE org_id=? AND code=?',[i.org_id,code]);
   if(inv){p.invoice_id=inv.id;p.expectedVersion=1;}const prepared=await s.makeExpense(i,p,{prepare:true,preparedId:next++,preparedInvoice:invoiceGroups.has(code)?{id:inv.id,partner_id:p.partner_id}:null});stamps.push(prepared.statements.shift());statements.push(...prepared.statements);invoiceGroups.set(code,{id:prepared.invoice_id});
   // 同じ請求書の2行目以後は準備中のため参照検査を別途扱う（下見では同一性を検査済み）。
   statements.push(insert('expense_import_row_commits',{id:newId(),row_id:original.id,version_id:v.id,expense_id:prepared.id,...s.meta(i,b)}));
   if(!inv)statements.push(insert('expense_invoice_file_links',{id:newId(),invoice_id:prepared.invoice_id,file_id:batch.file_id,purpose:'supporting',...s.meta(i,b)}));
  }
  const receipt=newId();if(!rowId)statements.push(insert('expense_import_events',{id:receipt,batch_id:id,kind:'committed',version_id:v.id,occurred_on:new Date().toISOString().slice(0,10),...s.meta(i,b)}));statements.push(s.audit(i,rowId?'expense_import_resolve':'expense_import_commit',rowId??id,b));
  await s.batch(compactImport([s.versionGuard(i,'expense_import_versions','batch_id',id,v.version_no),...stamps,...statements]));return {id,receipt,registered:selected.length,held:payload.held};
 }
 async function revise(i,id,b){await access(i,id);const previous=await s.latest(i,'expense_import_versions','batch_id',id),prior=previous?JSON.parse(previous.payload_json).supplement??{}:{};b={...b,supplement:{...prior,...b.supplement,overrides:{...prior.overrides,...b.supplement?.overrides}}};const raw=(await db.all('SELECT row_no,raw_json FROM expense_import_rows WHERE org_id=? AND batch_id=? ORDER BY row_no',[i.org_id,id])).map(r=>({row_no:r.row_no,values:JSON.parse(r.raw_json)}));return savePreview(i,b,id,raw);}
 async function cancel(i,id,b){await access(i,id);const v=await s.latest(i,'expense_import_versions','batch_id',id);if(expected(b)!==v.version_no)fail('版が変わりました',409);day(b.voided_on);const committed=await db.get("SELECT 1 FROM expense_import_events WHERE org_id=? AND batch_id=? AND kind='committed'",[i.org_id,id]);if(!committed)fail('未登録の下見です',409);const lines=await db.all('SELECT c.expense_id FROM expense_import_row_commits c JOIN expense_import_rows r ON r.org_id=c.org_id AND r.id=c.row_id WHERE r.org_id=? AND r.batch_id=?',[i.org_id,id]);for(const e of lines)await s.expense(i,e.expense_id);const statements=[await expenseChangeGuard(s,i,{voids:lines.map(e=>({id:e.expense_id,on:b.voided_on}))}),s.versionGuard(i,'expense_import_versions','batch_id',id,v.version_no)];for(const e of lines)statements.push(insert('expense_line_voids',{expense_id:e.expense_id,voided_on:b.voided_on,replacement_expense_id:null,...s.meta(i,b)}));statements.push(insert('expense_import_events',{id:newId(),batch_id:id,kind:'cancelled',version_id:v.id,occurred_on:b.voided_on,...s.meta(i,b)}),s.audit(i,'expense_import_cancel',id,b));await s.batch(statements);return {id,cancelled:lines.length};}
 return {access,preview,commit,revise,cancel};
}
